In [10]:

# Cell 2: Inspect dataset folder

import os

DATASET_DIR = "/kaggle/input/dataset"

print("Dataset path exists:", os.path.exists(DATASET_DIR))

for root, dirs, files in os.walk(DATASET_DIR):
    level = root.replace(DATASET_DIR, "").count(os.sep)

    print(f"\n{'  ' * level}{os.path.basename(root)}/")

    for filename in files[:15]:
        print(f"{'  ' * (level + 1)}{filename}")

    if level >= 3:
        dirs[:] = []

print("\nInspection finished.")

Dataset path exists: False

Inspection finished.

In [1]:

# Cell 2: Find mounted dataset folders

import os

INPUT_DIR = "/kaggle/input"

print("Input directory exists:", os.path.exists(INPUT_DIR))
print("Mounted items:")

for root, dirs, files in os.walk(INPUT_DIR):
    level = root.replace(INPUT_DIR, "").count(os.sep)

    print("  " * level + os.path.basename(root) + "/")

    for filename in files[:10]:
        print("  " * (level + 1) + filename)

    # Keep the listing manageable
    if level >= 2:
        dirs[:] = []

print("\nDone.")

Input directory exists: True
Mounted items:
input/
  datasets/
    prayashdas/
    ajithdari/

Done.

In [2]:

# Cell 3: Locate and inspect the mounted dataset

import os


BASE_DIR = "/kaggle/input/datasets/ajithdari"

for root, dirs, files in os.walk(BASE_DIR):
    level = root.replace(BASE_DIR, "").count(os.sep)

    print("  " * level + os.path.basename(root) + "/")

    for filename in files[:20]:
        print("  " * (level + 1) + filename)

    # Keep the initial inspection short
    if level >= 3:
        dirs[:] = []

print("\nInspection complete.")

ajithdari/
  autism-spectrum-disorder-multi-modal-dataset/
    Dataset_csv/
      test.csv
      train.csv
      valid.csv
    Dataset_img/
      test/
      train/
      valid/

Inspection complete.

In [3]:

# Cell 4: Inspect CSV schema and image counts

import os
import pandas as pd

DATASET_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

for split in ["train", "valid", "test"]:
    csv_path = os.path.join(DATASET_DIR, "Dataset_csv", f"{split}.csv")
    image_dir = os.path.join(DATASET_DIR, "Dataset_img", split)

    print(f"\n{'=' * 50}")
    print(f"SPLIT: {split.upper()}")

    if os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
        print("CSV shape:", df.shape)
        print("Columns:", df.columns.tolist())
        print("\nFirst 3 rows:")
        print(df.head(3).to_string(index=False))
    else:
        print("CSV missing:", csv_path)

    if os.path.isdir(image_dir):
        image_files = [
            f for f in os.listdir(image_dir)
            if os.path.isfile(os.path.join(image_dir, f))
        ]
        print("\nImages directly in folder:", len(image_files))
        print("Sample filenames:", image_files[:10])
    else:
        print("Image folder missing:", image_dir)

print("\nMetadata inspection complete.")

==================================================
SPLIT: TRAIN
CSV shape: (2526, 16)
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']

First 3 rows:
                                                                                      image_path  A1  A2  A3  A4  A5  A6  A7  A8  A9  A10  Age Sex Jauundice Family_ASD Class
/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0851.jpg   1   0   1   1   1   1   0   1   0    1    4   m        no         no   YES
/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0779.jpg   1   1   0   1   1   1   1   1   1    1   16   m        no         no   YES
/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1063.jpg   1   1   1   1   1   1   1   1   1    1   41   f       yes        yes   YES

Images directly in folder: 0
Sample filenames: []

==================================================
SPLIT: VALID
CSV shape: (200, 16)
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']

First 3 rows:
                                                                                     image_path  A1  A2  A3  A4  A5  A6  A7  A8  A9  A10  Age Sex Jauundice Family_ASD Class
/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/003.jpg   1   0   1   1   1   1   0   1   0    1    4   m        no         no   YES
/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/097.jpg   1   1   0   1   1   1   1   1   1    1   16   m        no         no   YES
/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/064.jpg   1   1   1   1   1   1   1   1   1    1   41   f       yes        yes   YES

Images directly in folder: 0
Sample filenames: []

==================================================
SPLIT: TEST
CSV shape: (200, 16)
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']

First 3 rows:
                                                                                    image_path  A1  A2  A3  A4  A5  A6  A7  A8  A9  A10  Age Sex Jauundice Family_ASD Class
/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/001.jpg   1   0   1   1   1   1   0   1   0    1    4   m        no         no   YES
/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/067.jpg   1   1   0   1   1   1   1   1   1    1   16   m        no         no   YES
/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/049.jpg   1   1   1   1   1   1   1   1   1    1   41   f       yes        yes   YES

Images directly in folder: 0
Sample filenames: []

Metadata inspection complete.

In [4]:

# Cell 5: Verify CSV image paths

import os
import pandas as pd

DATASET_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

for split in ["train", "valid", "test"]:
    csv_path = os.path.join(DATASET_DIR, "Dataset_csv", f"{split}.csv")
    df = pd.read_csv(csv_path)

    print(f"\n{'=' * 45}")
    print(split.upper(), "rows:", len(df))

    # Check the original paths embedded in the CSV
    exists_original = df["image_path"].astype(str).apply(os.path.isfile)
    print("Original CSV paths that exist:", int(exists_original.sum()))

    # Inspect actual images under this split
    image_root = os.path.join(DATASET_DIR, "Dataset_img", split)
    image_files = []

    for root, dirs, files in os.walk(image_root):
        for filename in files:
            if filename.lower().endswith(
                (".jpg", ".jpeg", ".png", ".bmp", ".webp")
            ):
                image_files.append(os.path.join(root, filename))

    print("Image files found recursively:", len(image_files))
    print("Sample actual image paths:", image_files[:5])

print("\nPath verification complete. No files modified.")

=============================================
TRAIN rows: 2526
Original CSV paths that exist: 2526
Image files found recursively: 2526
Sample actual image paths: ['/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0001.jpg', '/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0002.jpg', '/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0003.jpg', '/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0004.jpg', '/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0005.jpg']

=============================================
VALID rows: 200
Original CSV paths that exist: 200
Image files found recursively: 200
Sample actual image paths: ['/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/valid/autistic/001.jpg', '/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/valid/autistic/002.jpg', '/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/valid/autistic/003.jpg', '/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/valid/autistic/004.jpg', '/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/valid/autistic/005.jpg']

=============================================
TEST rows: 200
Original CSV paths that exist: 200
Image files found recursively: 200
Sample actual image paths: ['/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/test/autistic/001.jpg', '/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/test/autistic/002.jpg', '/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/test/autistic/003.jpg', '/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/test/autistic/004.jpg', '/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/test/autistic/005.jpg']

Path verification complete. No files modified.

In [5]:

# Cell 6: Audit CSV-to-image correspondence

import os
import pandas as pd
from collections import Counter

DATASET_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

for split in ["train", "valid", "test"]:
    df = pd.read_csv(
        os.path.join(DATASET_DIR, "Dataset_csv", f"{split}.csv")
    )

    image_root = os.path.join(DATASET_DIR, "Dataset_img", split)

    # Count images by class folder
    folder_counts = {}
    for label_folder in ["autistic", "non_autistic", "non-autistic", "typical"]:
        folder = os.path.join(image_root, label_folder)
        if os.path.isdir(folder):
            folder_counts[label_folder] = len([
                f for f in os.listdir(folder)
                if f.lower().endswith((".jpg", ".jpeg", ".png"))
            ])

    print(f"\n--- {split.upper()} ---")
    print("CSV rows:", len(df))
    print("CSV Class counts:")
    print(df["Class"].astype(str).str.strip().str.upper().value_counts().to_dict())
    print("Image counts by folder:", folder_counts)

    # Show how the first rows' stale filenames compare with actual files
    print("\nFirst 5 CSV image paths:")
    print(df["image_path"].head().tolist())

    print("\nFirst 5 actual image names per class folder:")
    for folder_name in folder_counts:
        folder = os.path.join(image_root, folder_name)
        names = sorted(os.listdir(folder))[:5]
        print(folder_name, names)

print("\nAudit only; no files modified.")

--- TRAIN ---
CSV rows: 2526
CSV Class counts:
{'YES': 1263, 'NO': 1263}
Image counts by folder: {'autistic': 1263, 'non_autistic': 1263}

First 5 CSV image paths:
['/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0851.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0779.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1063.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0164.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1080.jpg']

First 5 actual image names per class folder:
autistic ['0001.jpg', '0002.jpg', '0003.jpg', '0004.jpg', '0005.jpg']
non_autistic ['0001.jpg', '0002.jpg', '0003.jpg', '0004.jpg', '0005.jpg']

--- VALID ---
CSV rows: 200
CSV Class counts:
{'YES': 100, 'NO': 100}
Image counts by folder: {'autistic': 100, 'non_autistic': 100}

First 5 CSV image paths:
['/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/003.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/097.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/064.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/071.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/005.jpg']

First 5 actual image names per class folder:
autistic ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
non_autistic ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']

--- TEST ---
CSV rows: 200
CSV Class counts:
{'YES': 100, 'NO': 100}
Image counts by folder: {'autistic': 100, 'non_autistic': 100}

First 5 CSV image paths:
['/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/001.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/067.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/049.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/074.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/089.jpg']

First 5 actual image names per class folder:
autistic ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
non_autistic ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']

Audit only; no files modified.

In [6]:

# Cell 7: Verify labels against image folders

import os
import pandas as pd

DATASET_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

for split in ["train", "valid", "test"]:
    csv_path = os.path.join(DATASET_DIR, "Dataset_csv", f"{split}.csv")
    image_root = os.path.join(DATASET_DIR, "Dataset_img", split)
    df = pd.read_csv(csv_path)

    # Map CSV class labels to expected folder names
    expected_folder = (
        df["Class"].astype(str).str.strip().str.upper()
        .map({"YES": "autistic", "NO": "non_autistic"})
    )

    # Count actual images in each class folder
    actual_counts = {}
    for folder_name in ["autistic", "non_autistic"]:
        folder = os.path.join(image_root, folder_name)
        actual_counts[folder_name] = len([
            f for f in os.listdir(folder)
            if f.lower().endswith((".jpg", ".jpeg", ".png"))
        ])

    print(f"\n{split.upper()}")
    print("CSV rows:", len(df))
    print("Unknown CSV class labels:", int(expected_folder.isna().sum()))
    print("Image counts:", actual_counts)
    print("CSV label counts:",
          df["Class"].astype(str).str.strip().str.upper().value_counts().to_dict())

print("\nThis checks class counts only, not individual row-to-image pairing.")

TRAIN
CSV rows: 2526
Unknown CSV class labels: 0
Image counts: {'autistic': 1263, 'non_autistic': 1263}
CSV label counts: {'YES': 1263, 'NO': 1263}

VALID
CSV rows: 200
Unknown CSV class labels: 0
Image counts: {'autistic': 100, 'non_autistic': 100}
CSV label counts: {'YES': 100, 'NO': 100}

TEST
CSV rows: 200
Unknown CSV class labels: 0
Image counts: {'autistic': 100, 'non_autistic': 100}
CSV label counts: {'YES': 100, 'NO': 100}

This checks class counts only, not individual row-to-image pairing.

In [7]:

# Cell 8: Inspect questionnaire patterns and original filenames

import os
import pandas as pd

DATASET_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

df = pd.read_csv(os.path.join(DATASET_DIR, "Dataset_csv", "train.csv"))

print("Columns and data types:")
print(df.dtypes.to_string())

print("\nQuestionnaire and demographic sample:")
print(df[["A1", "A2", "A3", "A4", "A5",
          "A6", "A7", "A8", "A9", "A10",
          "Age", "Sex", "Jauundice", "Family_ASD", "Class"]]
      .head(10).to_string(index=False))

print("\nQuestionnaire answer totals by class:")
items = [f"A{i}" for i in range(1, 11)]
print(df.groupby("Class")[items].agg(["mean", "sum"]).round(3))

print("\nOriginal image filename examples:")
print(df["image_path"].astype(str).head(10).tolist())

print("\nThis is a provenance check, not proof of individual pairing.")

Columns and data types:
image_path    object
A1             int64
A2             int64
A3             int64
A4             int64
A5             int64
A6             int64
A7             int64
A8             int64
A9             int64
A10            int64
Age            int64
Sex           object
Jauundice     object
Family_ASD    object
Class         object

Questionnaire and demographic sample:
 A1  A2  A3  A4  A5  A6  A7  A8  A9  A10  Age Sex Jauundice Family_ASD Class
  1   0   1   1   1   1   0   1   0    1    4   m        no         no   YES
  1   1   0   1   1   1   1   1   1    1   16   m        no         no   YES
  1   1   1   1   1   1   1   1   1    1   41   f       yes        yes   YES
  0   1   1   1   1   1   0   1   1    1   33   m        no        yes   YES
  1   1   1   1   1   1   1   1   1    1   22   m       yes         no   YES
  1   1   0   1   1   1   1   1   1    0   26   f        no        yes   YES
  1   0   0   1   1   1   1   1   1    1   20   f        no         no   YES
  1   0   1   1   1   1   1   1   1    1    4   m        no         no   YES
  1   1   1   1   1   0   0   1   1    1   33   m        no         no   YES
  1   1   1   1   1   1   0   1   1    1   17   f        no         no   YES

Questionnaire answer totals by class:
          A1           A2          A3           A4           A5           A6  \
        mean   sum   mean  sum   mean   sum   mean   sum   mean   sum   mean
Class
NO     0.618   780  0.401  506  0.424   536  0.416   525  0.403   509  0.292
YES    0.873  1102  0.664  839  0.859  1085  0.873  1102  0.903  1140  0.821

                A7          A8          A9          A10
        sum   mean  sum   mean  sum   mean   sum   mean   sum
Class
NO      369  0.412  520  0.455  575  0.273   345  0.466   588
YES    1037  0.714  902  0.762  962  0.796  1005  0.896  1132

Original image filename examples:
['/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0851.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0779.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1063.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0164.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1080.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0179.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0010.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0265.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1173.jpg', '/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0884.jpg']

This is a provenance check, not proof of individual pairing.

In [11]:

# Cell 9: Questionnaire duplication and label audit

import os
import pandas as pd

DATASET_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

items = [f"A{i}" for i in range(1, 11)]

for split in ["train", "valid", "test"]:
    df = pd.read_csv(
        os.path.join(DATASET_DIR, "Dataset_csv", f"{split}.csv")
    )

    # Count repeated answer patterns
    repeated_patterns = df.duplicated(subset=items, keep=False)

    # Check whether identical answer patterns have conflicting labels
    label_counts = df.groupby(items)["Class"].nunique()
    conflicting_patterns = int((label_counts > 1).sum())

    print(f"\n--- {split.upper()} ---")
    print("Rows:", len(df))
    print("Unique A1-A10 patterns:", df[items].drop_duplicates().shape[0])
    print("Rows belonging to repeated patterns:", int(repeated_patterns.sum()))
    print("Patterns associated with multiple labels:", conflicting_patterns)
    print("\nClass counts:")
    print(df["Class"].value_counts().to_dict())

print("\nAudit complete; no files modified.")

--- TRAIN ---
Rows: 2526
Unique A1-A10 patterns: 622
Rows belonging to repeated patterns: 2274
Patterns associated with multiple labels: 56

Class counts:
{'YES': 1263, 'NO': 1263}

--- VALID ---
Rows: 200
Unique A1-A10 patterns: 131
Rows belonging to repeated patterns: 95
Patterns associated with multiple labels: 4

Class counts:
{'YES': 100, 'NO': 100}

--- TEST ---
Rows: 200
Unique A1-A10 patterns: 131
Rows belonging to repeated patterns: 95
Patterns associated with multiple labels: 4

Class counts:
{'YES': 100, 'NO': 100}

Audit complete; no files modified.

In [10]:

# Cell 10: Cross-split questionnaire pattern overlap

import os
import pandas as pd


DATASET_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

items = [f"A{i}" for i in range(1, 11)]
data = {}

for split in ["train", "valid", "test"]:
    data[split] = pd.read_csv(
        os.path.join(DATASET_DIR, "Dataset_csv", f"{split}.csv")
    )

patterns = {
    split: set(map(tuple, df[items].to_numpy()))
    for split, df in data.items()
}

for a, b in [("train", "valid"), ("train", "test"), ("valid", "test")]:
    shared = patterns[a] & patterns[b]
    print(f"{a} vs {b}:")
    print("  Unique patterns in first split:", len(patterns[a]))
    print("  Unique patterns in second split:", len(patterns[b]))
    print("  Shared unique patterns:", len(shared))

print("\nNo files modified.")

train vs valid:
  Unique patterns in first split: 622
  Unique patterns in second split: 131
  Shared unique patterns: 131
train vs test:
  Unique patterns in first split: 622
  Unique patterns in second split: 131
  Shared unique patterns: 131
valid vs test:
  Unique patterns in first split: 131
  Unique patterns in second split: 131
  Shared unique patterns: 131

No files modified.

In [12]:

# Cell 11: Check original filenames against mounted images

import os
import pandas as pd

DATASET_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

for split in ["train", "valid", "test"]:
    csv_path = os.path.join(DATASET_DIR, "Dataset_csv", f"{split}.csv")
    df = pd.read_csv(csv_path)

    image_root = os.path.join(DATASET_DIR, "Dataset_img", split)

    # Collect actual image basenames separately by class
    actual = {}
    for folder_name in ["autistic", "non_autistic"]:
        folder = os.path.join(image_root, folder_name)
        actual[folder_name] = {
            f.lower() for f in os.listdir(folder)
            if f.lower().endswith((".jpg", ".jpeg", ".png"))
        }

    original_names = df["image_path"].astype(str).apply(
        lambda p: os.path.basename(p).lower()
    )

    print(f"\n{split.upper()}")
    for label, folder_name in [("YES", "autistic"), ("NO", "non_autistic")]:
        names = original_names[
            df["Class"].astype(str).str.strip().str.upper() == label
        ]
        matches = sum(name in actual[folder_name] for name in names)
        print(f"{label}: CSV filenames matching actual filenames "
              f"in expected class folder: {matches}/{len(names)}")

print("\nRead-only check complete.")

TRAIN
YES: CSV filenames matching actual filenames in expected class folder: 1263/1263
NO: CSV filenames matching actual filenames in expected class folder: 1263/1263

VALID
YES: CSV filenames matching actual filenames in expected class folder: 100/100
NO: CSV filenames matching actual filenames in expected class folder: 100/100

TEST
YES: CSV filenames matching actual filenames in expected class folder: 100/100
NO: CSV filenames matching actual filenames in expected class folder: 100/100

Read-only check complete.

In [13]:

# Cell 12: Audit image filename uniqueness and split overlap
# Read-only diagnostic cell — safe to rerun

import os
import pandas as pd

DATASET_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

split_data = {}

for split in ["train", "valid", "test"]:
    csv_path = os.path.join(DATASET_DIR, "Dataset_csv", f"{split}.csv")
    df = pd.read_csv(csv_path)

    # Keep the filename and label for each CSV row
    df["filename"] = df["image_path"].astype(str).apply(
        lambda p: os.path.basename(p).lower()
    )
    df["label_clean"] = df["Class"].astype(str).str.strip().str.upper()
    split_data[split] = df

    print(f"\n{split.upper()}")
    print("Rows:", len(df))
    print("Unique filenames:", df["filename"].nunique())
    print("Duplicate filename rows:", df["filename"].duplicated().sum())
    print("Filename-label conflicts:",
          (df.groupby("filename")["label_clean"].nunique() > 1).sum())

print("\nCROSS-SPLIT FILENAME OVERLAP")
for split_a, split_b in [
    ("train", "valid"),
    ("train", "test"),
    ("valid", "test"),
]:
    names_a = set(split_data[split_a]["filename"])
    names_b = set(split_data[split_b]["filename"])
    overlap = names_a & names_b
    print(f"{split_a} vs {split_b}: {len(overlap)} shared filenames")

print("\nRead-only audit complete.")

TRAIN
Rows: 2526
Unique filenames: 1263
Duplicate filename rows: 1263
Filename-label conflicts: 1263

VALID
Rows: 200
Unique filenames: 100
Duplicate filename rows: 100
Filename-label conflicts: 100

TEST
Rows: 200
Unique filenames: 100
Duplicate filename rows: 100
Filename-label conflicts: 100

CROSS-SPLIT FILENAME OVERLAP
train vs valid: 0 shared filenames
train vs test: 0 shared filenames
valid vs test: 100 shared filenames

Read-only audit complete.

In [14]:
    
# Cell 13: Verify actual image content for duplicated filenames
# Read-only diagnostic cell — safe to rerun

import os
import hashlib
from collections import defaultdict

DATASET_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

def file_hash(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

split_hashes = {}

for split in ["train", "valid", "test"]:
    root = os.path.join(DATASET_DIR, "Dataset_img", split)
    records = []

    for folder_name in ["autistic", "non_autistic"]:
        folder = os.path.join(root, folder_name)

        for name in os.listdir(folder):
            path = os.path.join(folder, name)

            if os.path.isfile(path) and name.lower().endswith(
                (".jpg", ".jpeg", ".png")
            ):
                records.append({
                    "filename": name.lower(),
                    "class_folder": folder_name,
                    "hash": file_hash(path),
                })

    split_hashes[split] = records

    by_filename = defaultdict(list)
    for row in records:
        by_filename[row["filename"]].append(row)

    duplicate_names = {
        name: rows for name, rows in by_filename.items()
        if len(rows) > 1
    }

    same_name_same_content = sum(
        len({r["hash"] for r in rows}) == 1
        for rows in duplicate_names.values()
    )

    print(f"\n{split.upper()}")
    print("Image files hashed:", len(records))
    print("Filenames occurring in both class folders:", len(duplicate_names))
    print("Repeated filenames with identical file content:",
          same_name_same_content)

print("\nCROSS-SPLIT EXACT IMAGE-CONTENT OVERLAP")

hash_sets = {
    split: {row["hash"] for row in records}
    for split, records in split_hashes.items()
}

for a, b in [("train", "valid"), ("train", "test"), ("valid", "test")]:
    print(f"{a} vs {b}: {len(hash_sets[a] & hash_sets[b])} shared image hashes")

print("\nRead-only audit complete.")

KeyboardInterrupt:

In [15]:

# Cell 14: Inspect CSV paths and actual image files
# Read-only diagnostic cell — safe to rerun

import os
import pandas as pd

DATASET_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

for split in ["train", "valid", "test"]:
    print(f"\n{'=' * 15} {split.upper()} {'=' * 15}")

    csv_path = os.path.join(
        DATASET_DIR, "Dataset_csv", f"{split}.csv"
    )
    df = pd.read_csv(csv_path)

    for label in ["YES", "NO"]:
        rows = df[
            df["Class"].astype(str).str.strip().str.upper() == label
        ].head(3)

        print(f"\nCSV label: {label}")

        for _, row in rows.iterrows():
            original_path = str(row["image_path"])
            original_exists = os.path.isfile(original_path)

            print("CSV path:", original_path)
            print("Original path exists:", original_exists)
            print("Questionnaire:", {
                col: row[col]
                for col in [
                    "A1", "A2", "A3", "A4", "A5",
                    "A6", "A7", "A8", "A9", "A10",
                    "Age", "Sex", "Jauundice", "Family_ASD", "Class"
                ]
                if col in row.index
            })

            # Show actual images in the CSV label's expected folder
            folder_name = "autistic" if label == "YES" else "non_autistic"
            folder = os.path.join(
                DATASET_DIR, "Dataset_img", split, folder_name
            )
            files = sorted(
                f for f in os.listdir(folder)
                if f.lower().endswith((".jpg", ".jpeg", ".png"))
            )
            print("Example files in expected class folder:", files[:5])
            print("-" * 40)

print("\nRead-only inspection complete.")

=============== TRAIN ===============

CSV label: YES
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0851.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 0, 'A3': 1, 'A4': 1, 'A5': 1, 'A6': 1, 'A7': 0, 'A8': 1, 'A9': 0, 'A10': 1, 'Age': 4, 'Sex': 'm', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'YES'}
Example files in expected class folder: ['0001.jpg', '0002.jpg', '0003.jpg', '0004.jpg', '0005.jpg']
----------------------------------------
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0779.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 1, 'A3': 0, 'A4': 1, 'A5': 1, 'A6': 1, 'A7': 1, 'A8': 1, 'A9': 1, 'A10': 1, 'Age': 16, 'Sex': 'm', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'YES'}
Example files in expected class folder: ['0001.jpg', '0002.jpg', '0003.jpg', '0004.jpg', '0005.jpg']
----------------------------------------
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1063.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 1, 'A3': 1, 'A4': 1, 'A5': 1, 'A6': 1, 'A7': 1, 'A8': 1, 'A9': 1, 'A10': 1, 'Age': 41, 'Sex': 'f', 'Jauundice': 'yes', 'Family_ASD': 'yes', 'Class': 'YES'}
Example files in expected class folder: ['0001.jpg', '0002.jpg', '0003.jpg', '0004.jpg', '0005.jpg']
----------------------------------------

CSV label: NO
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/0443.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 0, 'A3': 0, 'A4': 0, 'A5': 0, 'A6': 0, 'A7': 1, 'A8': 0, 'A9': 0, 'A10': 1, 'Age': 40, 'Sex': 'f', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'NO'}
Example files in expected class folder: ['0001.jpg', '0002.jpg', '0003.jpg', '0004.jpg', '0005.jpg']
----------------------------------------
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/0674.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 0, 'A3': 0, 'A4': 0, 'A5': 0, 'A6': 0, 'A7': 0, 'A8': 0, 'A9': 0, 'A10': 0, 'Age': 38, 'Sex': 'f', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'NO'}
Example files in expected class folder: ['0001.jpg', '0002.jpg', '0003.jpg', '0004.jpg', '0005.jpg']
----------------------------------------
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/0765.jpg
Original path exists: True
Questionnaire: {'A1': 0, 'A2': 0, 'A3': 0, 'A4': 0, 'A5': 0, 'A6': 0, 'A7': 0, 'A8': 0, 'A9': 0, 'A10': 0, 'Age': 27, 'Sex': 'f', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'NO'}
Example files in expected class folder: ['0001.jpg', '0002.jpg', '0003.jpg', '0004.jpg', '0005.jpg']
----------------------------------------

=============== VALID ===============

CSV label: YES
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/003.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 0, 'A3': 1, 'A4': 1, 'A5': 1, 'A6': 1, 'A7': 0, 'A8': 1, 'A9': 0, 'A10': 1, 'Age': 4, 'Sex': 'm', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'YES'}
Example files in expected class folder: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
----------------------------------------
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/097.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 1, 'A3': 0, 'A4': 1, 'A5': 1, 'A6': 1, 'A7': 1, 'A8': 1, 'A9': 1, 'A10': 1, 'Age': 16, 'Sex': 'm', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'YES'}
Example files in expected class folder: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
----------------------------------------
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/064.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 1, 'A3': 1, 'A4': 1, 'A5': 1, 'A6': 1, 'A7': 1, 'A8': 1, 'A9': 1, 'A10': 1, 'Age': 41, 'Sex': 'f', 'Jauundice': 'yes', 'Family_ASD': 'yes', 'Class': 'YES'}
Example files in expected class folder: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
----------------------------------------

CSV label: NO
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/non_autistic/007.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 0, 'A3': 0, 'A4': 0, 'A5': 0, 'A6': 0, 'A7': 1, 'A8': 0, 'A9': 0, 'A10': 1, 'Age': 40, 'Sex': 'f', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'NO'}
Example files in expected class folder: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
----------------------------------------
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/non_autistic/086.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 0, 'A3': 0, 'A4': 0, 'A5': 0, 'A6': 0, 'A7': 0, 'A8': 0, 'A9': 0, 'A10': 0, 'Age': 38, 'Sex': 'f', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'NO'}
Example files in expected class folder: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
----------------------------------------
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/non_autistic/080.jpg
Original path exists: True
Questionnaire: {'A1': 0, 'A2': 0, 'A3': 0, 'A4': 0, 'A5': 0, 'A6': 0, 'A7': 0, 'A8': 0, 'A9': 0, 'A10': 0, 'Age': 27, 'Sex': 'f', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'NO'}
Example files in expected class folder: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
----------------------------------------

=============== TEST ===============

CSV label: YES
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/001.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 0, 'A3': 1, 'A4': 1, 'A5': 1, 'A6': 1, 'A7': 0, 'A8': 1, 'A9': 0, 'A10': 1, 'Age': 4, 'Sex': 'm', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'YES'}
Example files in expected class folder: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
----------------------------------------
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/067.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 1, 'A3': 0, 'A4': 1, 'A5': 1, 'A6': 1, 'A7': 1, 'A8': 1, 'A9': 1, 'A10': 1, 'Age': 16, 'Sex': 'm', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'YES'}
Example files in expected class folder: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
----------------------------------------
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/049.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 1, 'A3': 1, 'A4': 1, 'A5': 1, 'A6': 1, 'A7': 1, 'A8': 1, 'A9': 1, 'A10': 1, 'Age': 41, 'Sex': 'f', 'Jauundice': 'yes', 'Family_ASD': 'yes', 'Class': 'YES'}
Example files in expected class folder: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
----------------------------------------

CSV label: NO
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/non_autistic/076.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 0, 'A3': 0, 'A4': 0, 'A5': 0, 'A6': 0, 'A7': 1, 'A8': 0, 'A9': 0, 'A10': 1, 'Age': 40, 'Sex': 'f', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'NO'}
Example files in expected class folder: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
----------------------------------------
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/non_autistic/046.jpg
Original path exists: True
Questionnaire: {'A1': 1, 'A2': 0, 'A3': 0, 'A4': 0, 'A5': 0, 'A6': 0, 'A7': 0, 'A8': 0, 'A9': 0, 'A10': 0, 'Age': 38, 'Sex': 'f', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'NO'}
Example files in expected class folder: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
----------------------------------------
CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/non_autistic/005.jpg
Original path exists: True
Questionnaire: {'A1': 0, 'A2': 0, 'A3': 0, 'A4': 0, 'A5': 0, 'A6': 0, 'A7': 0, 'A8': 0, 'A9': 0, 'A10': 0, 'Age': 27, 'Sex': 'f', 'Jauundice': 'no', 'Family_ASD': 'no', 'Class': 'NO'}
Example files in expected class folder: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg']
----------------------------------------

Read-only inspection complete.

In [16]:

# Cell 15: Check original dataset paths against mounted images
# Read-only diagnostic — safe to rerun

import os
import hashlib
import pandas as pd

MULTIMODAL_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)
INPUT_DIR = "/kaggle/input/datasets"

def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

# Find the original filenames used in the multimodal CSVs
original_paths = []
for split in ["train", "valid", "test"]:
    csv_path = os.path.join(
        MULTIMODAL_DIR, "Dataset_csv", f"{split}.csv"
    )
    df = pd.read_csv(csv_path)
    original_paths.extend(df["image_path"].dropna().astype(str).tolist())

sample_paths = list(dict.fromkeys(original_paths))[:12]

# Index mounted image files by filename
mounted_by_name = {}
for root, dirs, files in os.walk(INPUT_DIR):
    for name in files:
        if name.lower().endswith((".jpg", ".jpeg", ".png")):
            mounted_by_name.setdefault(name.lower(), []).append(
                os.path.join(root, name)
            )

print("Unique CSV original paths:", len(set(original_paths)))
print("Mounted image filenames indexed:", len(mounted_by_name))

for original_path in sample_paths:
    name = os.path.basename(original_path).lower()
    candidates = mounted_by_name.get(name, [])

    print(f"\nCSV path: {original_path}")
    print("Original path exists:", os.path.isfile(original_path))
    print("Mounted candidates with same filename:", len(candidates))

    if candidates:
        print("Candidate paths:")
        for candidate in candidates[:3]:
            print(" ", candidate)

print("\nDiagnostic complete. No files modified.")

Unique CSV original paths: 2926
Mounted image filenames indexed: 1363

CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0851.jpg
Original path exists: True
Mounted candidates with same filename: 4
Candidate paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0851.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/0851.jpg
  /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0851.jpg

CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0779.jpg
Original path exists: True
Mounted candidates with same filename: 4
Candidate paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0779.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/0779.jpg
  /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0779.jpg

CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1063.jpg
Original path exists: True
Mounted candidates with same filename: 4
Candidate paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1063.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/1063.jpg
  /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/1063.jpg

CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0164.jpg
Original path exists: True
Mounted candidates with same filename: 4
Candidate paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0164.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/0164.jpg
  /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0164.jpg

CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1080.jpg
Original path exists: True
Mounted candidates with same filename: 4
Candidate paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1080.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/1080.jpg
  /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/1080.jpg

CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0179.jpg
Original path exists: True
Mounted candidates with same filename: 4
Candidate paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0179.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/0179.jpg
  /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0179.jpg

CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0010.jpg
Original path exists: True
Mounted candidates with same filename: 4
Candidate paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0010.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/0010.jpg
  /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0010.jpg

CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0265.jpg
Original path exists: True
Mounted candidates with same filename: 4
Candidate paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0265.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/0265.jpg
  /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0265.jpg

CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1173.jpg
Original path exists: True
Mounted candidates with same filename: 4
Candidate paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1173.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/1173.jpg
  /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/1173.jpg

CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0884.jpg
Original path exists: True
Mounted candidates with same filename: 4
Candidate paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0884.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/0884.jpg
  /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0884.jpg

CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0868.jpg
Original path exists: True
Mounted candidates with same filename: 4
Candidate paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0868.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/0868.jpg
  /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0868.jpg

CSV path: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0078.jpg
Original path exists: True
Mounted candidates with same filename: 4
Candidate paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0078.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/non_autistic/0078.jpg
  /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_img/train/autistic/0078.jpg

Diagnostic complete. No files modified.

In [17]:

# Cell 16: Compare original CSV-referenced images with mounted images
# Read-only diagnostic — does not modify files

import os
import hashlib
import pandas as pd

MULTIMODAL_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

for split in ["train", "valid", "test"]:
    print(f"\n{'=' * 12} {split.upper()} {'=' * 12}")

    csv_path = os.path.join(
        MULTIMODAL_DIR, "Dataset_csv", f"{split}.csv"
    )
    df = pd.read_csv(csv_path)

    checked = 0
    exact_matches = 0
    missing = 0

    for _, row in df.head(12).iterrows():
        original_path = str(row["image_path"])
        label = str(row["Class"]).strip().upper()

        folder_name = "autistic" if label == "YES" else "non_autistic"
        mounted_path = os.path.join(
            MULTIMODAL_DIR, "Dataset_img", split,
            folder_name, os.path.basename(original_path)
        )

        if not os.path.isfile(original_path) or not os.path.isfile(mounted_path):
            missing += 1
            print("MISSING:", original_path, "->", mounted_path)
            continue

        same = sha256_file(original_path) == sha256_file(mounted_path)
        checked += 1
        exact_matches += int(same)

        print(
            f"{os.path.basename(original_path)} | label={label} | "
            f"exact_content_match={same}"
        )

    print(
        f"SUMMARY: checked={checked}, exact_matches={exact_matches}, "
        f"missing={missing}"
    )

print("\nRead-only comparison complete.")

============ TRAIN ============
0851.jpg | label=YES | exact_content_match=True
0779.jpg | label=YES | exact_content_match=True
1063.jpg | label=YES | exact_content_match=True
0164.jpg | label=YES | exact_content_match=True
1080.jpg | label=YES | exact_content_match=True
0179.jpg | label=YES | exact_content_match=True
0010.jpg | label=YES | exact_content_match=True
0265.jpg | label=YES | exact_content_match=True
1173.jpg | label=YES | exact_content_match=True
0884.jpg | label=YES | exact_content_match=True
0868.jpg | label=YES | exact_content_match=True
0078.jpg | label=YES | exact_content_match=True
SUMMARY: checked=12, exact_matches=12, missing=0

============ VALID ============
003.jpg | label=YES | exact_content_match=True
097.jpg | label=YES | exact_content_match=True
064.jpg | label=YES | exact_content_match=True
071.jpg | label=YES | exact_content_match=True
005.jpg | label=YES | exact_content_match=True
036.jpg | label=YES | exact_content_match=True
096.jpg | label=YES | exact_content_match=True
039.jpg | label=YES | exact_content_match=True
023.jpg | label=YES | exact_content_match=True
037.jpg | label=YES | exact_content_match=True
057.jpg | label=YES | exact_content_match=True
091.jpg | label=YES | exact_content_match=True
SUMMARY: checked=12, exact_matches=12, missing=0

============ TEST ============
001.jpg | label=YES | exact_content_match=True
067.jpg | label=YES | exact_content_match=True
049.jpg | label=YES | exact_content_match=True
074.jpg | label=YES | exact_content_match=True
089.jpg | label=YES | exact_content_match=True
011.jpg | label=YES | exact_content_match=True
047.jpg | label=YES | exact_content_match=True
013.jpg | label=YES | exact_content_match=True
093.jpg | label=YES | exact_content_match=True
079.jpg | label=YES | exact_content_match=True
075.jpg | label=YES | exact_content_match=True
022.jpg | label=YES | exact_content_match=True
SUMMARY: checked=12, exact_matches=12, missing=0

Read-only comparison complete.

In [18]:

# Cell 18: MobileNetV2 image-only baseline
# Training cell — uses GPU when available

import os

import json
import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow.keras import layers, Model
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

SEED = 42
tf.keras.utils.set_random_seed(SEED)

DATASET_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)
OUT_DIR = "/kaggle/working/asd_care_results"
os.makedirs(OUT_DIR, exist_ok=True)

IMG_SIZE = (224, 224)
BATCH_SIZE = 32
EPOCHS = 10

print("TensorFlow:", tf.__version__)
print("GPUs:", tf.config.list_physical_devices("GPU"))

def load_split(split):
    csv_path = os.path.join(
        DATASET_DIR, "Dataset_csv", f"{split}.csv"
    )
    df = pd.read_csv(csv_path)

    paths, labels_list = [], []

    for _, row in df.iterrows():
        label = str(row["Class"]).strip().upper()
        folder = "autistic" if label == "YES" else "non_autistic"
        path = os.path.join(
            DATASET_DIR, "Dataset_img", split,
            folder, os.path.basename(str(row["image_path"]))
        )

        if not os.path.isfile(path):
            raise FileNotFoundError(path)

        paths.append(path)
        labels_list.append(1 if label == "YES" else 0)

    return np.array(paths), np.array(labels_list, dtype=np.float32)

def make_dataset(paths, labels, training=False):
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))

    if training:
        ds = ds.shuffle(
            len(paths), seed=SEED, reshuffle_each_iteration=True
        )

    def load_image(path, label):
        image_bytes = tf.io.read_file(path)
        image = tf.io.decode_image(
            image_bytes, channels=3, expand_animations=False
        )
        image.set_shape([None, None, 3])
        image = tf.image.resize(image, IMG_SIZE)
        image = preprocess_input(tf.cast(image, tf.float32))
        return image, label

    ds = ds.map(load_image, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
    return ds

train_paths, y_train = load_split("train")
valid_paths, y_valid = load_split("valid")
test_paths, y_test = load_split("test")

train_ds = make_dataset(train_paths, y_train, training=True)
valid_ds = make_dataset(valid_paths, y_valid)
test_ds = make_dataset(test_paths, y_test)

print("Split sizes:", len(train_paths), len(valid_paths), len(test_paths))
print("Label counts — train:", np.unique(y_train, return_counts=True))
print("Label counts — valid:", np.unique(y_valid, return_counts=True))
print("Label counts — test:", np.unique(y_test, return_counts=True))

# Skip training if a completed best-model artifact already exists.
best_model_path = os.path.join(OUT_DIR, "mobilenetv2_best.keras")
history_path = os.path.join(OUT_DIR, "mobilenetv2_history.json")

if os.path.exists(best_model_path) and os.path.exists(history_path):
    print("\nExisting model and history found. No retraining performed.")
    print("Model:", best_model_path)
else:
    base = MobileNetV2(
        weights="imagenet",
        include_top=False,
        input_shape=(224, 224, 3)
    )
    base.trainable = False

    inputs = layers.Input(shape=(224, 224, 3))
    x = base(inputs, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.3)(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.2)(x)
    outputs = layers.Dense(1, activation="sigmoid")(x)

    model = Model(inputs, outputs, name="mobilenetv2_image_only")
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=[
            "accuracy",
            tf.keras.metrics.AUC(name="auc"),
            tf.keras.metrics.Precision(name="precision"),
            tf.keras.metrics.Recall(name="recall"),
        ],
    )

    callbacks = [
        tf.keras.callbacks.ModelCheckpoint(
            best_model_path,
            monitor="val_auc",
            mode="max",
            save_best_only=True,
            verbose=1,
        ),
        tf.keras.callbacks.EarlyStopping(
            monitor="val_auc",
            mode="max",
            patience=3,
            restore_best_weights=True,
            verbose=1,
        ),
        tf.keras.callbacks.CSVLogger(
            os.path.join(OUT_DIR, "mobilenetv2_training_log.csv")
        ),
    ]

    history = model.fit(
        train_ds,
        validation_data=valid_ds,
        epochs=EPOCHS,
        callbacks=callbacks,
        verbose=1,
    )

    with open(history_path, "w") as f:
        json.dump(
            {k: [float(v) for v in values]
             for k, values in history.history.items()},
            f,
            indent=2,
        )

    print("\nTraining complete.")
    print("Best model:", best_model_path)
    print("History:", history_path)

TensorFlow: 2.20.0
GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1792717861.906764      49 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13756 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1792717861.910511      49 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13756 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5

Split sizes: 2526 200 200
Label counts — train: (array([0., 1.], dtype=float32), array([1263, 1263]))
Label counts — valid: (array([0., 1.], dtype=float32), array([100, 100]))
Label counts — test: (array([0., 1.], dtype=float32), array([100, 100]))
Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224_no_top.h5
9406464/9406464 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Epoch 1/10

2026-10-23 01:11:21.622252: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:11:21.758698: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
I0000 00:00:1792717884.506570     145 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

78/79 ━━━━━━━━━━━━━━━━━━━━ 0s 386ms/step - accuracy: 0.6338 - auc: 0.6873 - loss: 0.6586 - precision: 0.6398 - recall: 0.6527

2026-10-23 01:12:03.841728: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:12:03.977807: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 540ms/step - accuracy: 0.6346 - auc: 0.6884 - loss: 0.6577 - precision: 0.6404 - recall: 0.6533

2026-10-23 01:12:21.744801: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:12:21.901021: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:12:22.036591: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

Epoch 1: val_auc improved from None to 0.83500, saving model to /kaggle/working/asd_care_results/mobilenetv2_best.keras

Epoch 1: finished saving model to /kaggle/working/asd_care_results/mobilenetv2_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 80s 768ms/step - accuracy: 0.6908 - auc: 0.7681 - loss: 0.5807 - precision: 0.6886 - recall: 0.6968 - val_accuracy: 0.7250 - val_auc: 0.8350 - val_loss: 0.5345 - val_precision: 0.8000 - val_recall: 0.6000
Epoch 2/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7526 - auc: 0.8291 - loss: 0.5082 - precision: 0.7540 - recall: 0.7709
Epoch 2: val_auc improved from 0.83500 to 0.84040, saving model to /kaggle/working/asd_care_results/mobilenetv2_best.keras

Epoch 2: finished saving model to /kaggle/working/asd_care_results/mobilenetv2_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.7696 - auc: 0.8467 - loss: 0.4863 - precision: 0.7687 - recall: 0.7712 - val_accuracy: 0.7800 - val_auc: 0.8404 - val_loss: 0.5003 - val_precision: 0.7745 - val_recall: 0.7900
Epoch 3/10
78/79 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7723 - auc: 0.8582 - loss: 0.4655 - precision: 0.7713 - recall: 0.7884
Epoch 3: val_auc improved from 0.84040 to 0.85115, saving model to /kaggle/working/asd_care_results/mobilenetv2_best.keras

Epoch 3: finished saving model to /kaggle/working/asd_care_results/mobilenetv2_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.7842 - auc: 0.8683 - loss: 0.4514 - precision: 0.7809 - recall: 0.7902 - val_accuracy: 0.8000 - val_auc: 0.8511 - val_loss: 0.4862 - val_precision: 0.7727 - val_recall: 0.8500
Epoch 4/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8078 - auc: 0.8914 - loss: 0.4137 - precision: 0.8080 - recall: 0.8122
Epoch 4: val_auc improved from 0.85115 to 0.85195, saving model to /kaggle/working/asd_care_results/mobilenetv2_best.keras

Epoch 4: finished saving model to /kaggle/working/asd_care_results/mobilenetv2_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.8029 - auc: 0.8867 - loss: 0.4223 - precision: 0.8043 - recall: 0.8005 - val_accuracy: 0.7750 - val_auc: 0.8520 - val_loss: 0.4980 - val_precision: 0.7957 - val_recall: 0.7400
Epoch 5/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8112 - auc: 0.8931 - loss: 0.4098 - precision: 0.8093 - recall: 0.8000
Epoch 5: val_auc improved from 0.85195 to 0.87430, saving model to /kaggle/working/asd_care_results/mobilenetv2_best.keras

Epoch 5: finished saving model to /kaggle/working/asd_care_results/mobilenetv2_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.8064 - auc: 0.8905 - loss: 0.4151 - precision: 0.8076 - recall: 0.8044 - val_accuracy: 0.8100 - val_auc: 0.8743 - val_loss: 0.4611 - val_precision: 0.7719 - val_recall: 0.8800
Epoch 6/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8246 - auc: 0.9006 - loss: 0.3987 - precision: 0.8212 - recall: 0.8310
Epoch 6: val_auc did not improve from 0.87430
79/79 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - accuracy: 0.8219 - auc: 0.9000 - loss: 0.3995 - precision: 0.8183 - recall: 0.8274 - val_accuracy: 0.8000 - val_auc: 0.8591 - val_loss: 0.4765 - val_precision: 0.8125 - val_recall: 0.7800
Epoch 7/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8291 - auc: 0.9078 - loss: 0.3869 - precision: 0.8398 - recall: 0.8254
Epoch 7: val_auc did not improve from 0.87430
79/79 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - accuracy: 0.8226 - auc: 0.9048 - loss: 0.3906 - precision: 0.8211 - recall: 0.8250 - val_accuracy: 0.8250 - val_auc: 0.8643 - val_loss: 0.4686 - val_precision: 0.8218 - val_recall: 0.8300
Epoch 8/10
78/79 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8303 - auc: 0.9154 - loss: 0.3656 - precision: 0.8339 - recall: 0.8192
Epoch 8: val_auc did not improve from 0.87430
79/79 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - accuracy: 0.8266 - auc: 0.9094 - loss: 0.3787 - precision: 0.8256 - recall: 0.8282 - val_accuracy: 0.7950 - val_auc: 0.8627 - val_loss: 0.4743 - val_precision: 0.8105 - val_recall: 0.7700
Epoch 8: early stopping
Restoring model weights from the end of the best epoch: 5.

Training complete.
Best model: /kaggle/working/asd_care_results/mobilenetv2_best.keras
History: /kaggle/working/asd_care_results/mobilenetv2_history.json

In [19]:

# Cell 19: Final test evaluation — MobileNetV2
# Loads the saved checkpoint; does not retrain

import os
import json
import numpy as np
import tensorflow as tf

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
)

OUT_DIR = "/kaggle/working/asd_care_results"
MODEL_PATH = os.path.join(OUT_DIR, "mobilenetv2_best.keras")

if not os.path.isfile(MODEL_PATH):
    raise FileNotFoundError(f"Saved model not found: {MODEL_PATH}")

best_model = tf.keras.models.load_model(MODEL_PATH)

# Use the test dataset created in Cell 18.
y_true = np.asarray(y_test).astype(int)
y_prob = best_model.predict(test_ds, verbose=1).reshape(-1)
y_pred = (y_prob >= 0.5).astype(int)

results = {
    "model": "MobileNetV2 image-only",
    "test_samples": int(len(y_true)),
    "accuracy": float(accuracy_score(y_true, y_pred)),
    "precision": float(precision_score(y_true, y_pred, zero_division=0)),
    "recall": float(recall_score(y_true, y_pred, zero_division=0)),
    "f1": float(f1_score(y_true, y_pred, zero_division=0)),
    "roc_auc": float(roc_auc_score(y_true, y_prob)),
    "confusion_matrix": confusion_matrix(y_true, y_pred).tolist(),
}

print("\nTEST RESULTS")
print(json.dumps(results, indent=2))
print("\nClassification report:")
print(classification_report(
    y_true, y_pred,
    target_names=["NO", "YES"],
    zero_division=0
))

# Save results separately; preserve all existing artifacts.
result_path = os.path.join(OUT_DIR, "mobilenetv2_test_results.json")
with open(result_path, "w") as f:
    json.dump(results, f, indent=2)

np.savez_compressed(
    os.path.join(OUT_DIR, "mobilenetv2_test_predictions.npz"),
    y_true=y_true,
    y_prob=y_prob,
    y_pred=y_pred,
)

print("\nSaved:", result_path)
print("Saved test predictions.")

7/7 ━━━━━━━━━━━━━━━━━━━━ 10s 891ms/step

TEST RESULTS
{
  "model": "MobileNetV2 image-only",
  "test_samples": 200,
  "accuracy": 0.85,
  "precision": 0.8571428571428571,
  "recall": 0.84,
  "f1": 0.8484848484848485,
  "roc_auc": 0.9307,
  "confusion_matrix": [
    [
      86,
      14
    ],
    [
      16,
      84
    ]
  ]
}

Classification report:
              precision    recall  f1-score   support

          NO       0.84      0.86      0.85       100
         YES       0.86      0.84      0.85       100

    accuracy                           0.85       200
   macro avg       0.85      0.85      0.85       200
weighted avg       0.85      0.85      0.85       200


Saved: /kaggle/working/asd_care_results/mobilenetv2_test_results.json
Saved test predictions.

In [20]:

# Cell 20: Questionnaire-only baseline
# Trains a separate model; preserves all image-model artifacts.

import os

import json
import numpy as np
import pandas as pd


import tensorflow as tf

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix,
    classification_report
)

SEED = 42
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

DATA_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset/Dataset_csv"
)
OUT_DIR = "/kaggle/working/asd_care_results"
os.makedirs(OUT_DIR, exist_ok=True)

TRAIN_CSV = os.path.join(DATA_DIR, "train.csv")
VALID_CSV = os.path.join(DATA_DIR, "valid.csv")
TEST_CSV  = os.path.join(DATA_DIR, "test.csv")

for path in [TRAIN_CSV, VALID_CSV, TEST_CSV]:
    if not os.path.isfile(path):
        raise FileNotFoundError(f"CSV not found: {path}")

train_df = pd.read_csv(TRAIN_CSV)
valid_df = pd.read_csv(VALID_CSV)
test_df  = pd.read_csv(TEST_CSV)

# These are the questionnaire/demographic features only.
FEATURES = [
    "A1", "A2", "A3", "A4", "A5",
    "A6", "A7", "A8", "A9", "A10",
    "Age", "Sex", "Jauundice", "Family_ASD"
]
TARGET = "Class"

for split_name, df in [
    ("train", train_df), ("valid", valid_df), ("test", test_df)
]:
    missing = [c for c in FEATURES + [TARGET] if c not in df.columns]
    if missing:
        raise ValueError(f"{split_name}.csv missing columns: {missing}")

# Convert feature columns to numeric, report unusable values.
for df in [train_df, valid_df, test_df]:
    for col in FEATURES:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# Fit imputation values on training data only.
train_medians = train_df[FEATURES].median()
for df in [train_df, valid_df, test_df]:
    df[FEATURES] = df[FEATURES].fillna(train_medians)

# Normalize using training data only.
scaler = StandardScaler()
X_train = scaler.fit_transform(train_df[FEATURES]).astype("float32")
X_valid = scaler.transform(valid_df[FEATURES]).astype("float32")
X_test  = scaler.transform(test_df[FEATURES]).astype("float32")

def encode_labels(series):
    # Supports YES/NO, ASD/TD, and binary numeric labels.
    s = series.astype(str).str.strip().str.upper()
    mapping = {
        "YES": 1, "NO": 0,
        "ASD": 1, "TD": 0,
        "AUTISTIC": 1, "NON_AUTISTIC": 0,
        "NON-AUTISTIC": 0,
        "TRUE": 1, "FALSE": 0,
        "1": 1, "0": 0
    }
    encoded = s.map(mapping)
    if encoded.isna().any():
        bad = sorted(s[encoded.isna()].unique().tolist())
        raise ValueError(f"Unrecognized {TARGET} labels: {bad}")
    return encoded.to_numpy(dtype="int32")

y_train = encode_labels(train_df[TARGET])
y_valid = encode_labels(valid_df[TARGET])
y_test_q = encode_labels(test_df[TARGET])

print("Feature count:", len(FEATURES))
print("Train:", X_train.shape, "labels:", np.bincount(y_train))
print("Valid:", X_valid.shape, "labels:", np.bincount(y_valid))
print("Test: ", X_test.shape, "labels:", np.bincount(y_test_q))

# Small dense network appropriate for tabular questionnaire features.
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(len(FEATURES),)),
    tf.keras.layers.Dense(32, activation="relu"),
    tf.keras.layers.Dropout(0.30),
    tf.keras.layers.Dense(16, activation="relu"),
    tf.keras.layers.Dropout(0.20),
    tf.keras.layers.Dense(1, activation="sigmoid")
], name="questionnaire_only_mlp")

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

MODEL_PATH = os.path.join(OUT_DIR, "questionnaire_mlp_best.keras")
HISTORY_PATH = os.path.join(OUT_DIR, "questionnaire_mlp_history.json")
SCALER_PATH = os.path.join(OUT_DIR, "questionnaire_scaler.json")

callbacks = [
    tf.keras.callbacks.ModelCheckpoint(
        MODEL_PATH, monitor="val_auc",
        mode="max", save_best_only=True, verbose=1
    ),
    tf.keras.callbacks.EarlyStopping(
        monitor="val_auc", mode="max",
        patience=5, restore_best_weights=True, verbose=1
    ),
    tf.keras.callbacks.CSVLogger(
        os.path.join(OUT_DIR, "questionnaire_mlp_training_log.csv")
    )
]

history = model.fit(
    X_train, y_train,
    validation_data=(X_valid, y_valid),
    epochs=50,
    batch_size=32,
    callbacks=callbacks,
    verbose=1
)

with open(HISTORY_PATH, "w") as f:
    json.dump(
        {k: [float(v) for v in vals]
         for k, vals in history.history.items()},
        f, indent=2
    )

# Save preprocessing details for reproducible inference.
with open(SCALER_PATH, "w") as f:
    json.dump({
        "features": FEATURES,
        "mean": scaler.mean_.tolist(),
        "scale": scaler.scale_.tolist(),
        "imputation_medians": train_medians.to_dict()
    }, f, indent=2)

print("\nTraining complete.")
print("Best model:", MODEL_PATH)
print("History:", HISTORY_PATH)
print("Scaler details:", SCALER_PATH)

Feature count: 14
Train: (2526, 14) labels: [1263 1263]
Valid: (200, 14) labels: [100 100]
Test:  (200, 14) labels: [100 100]
Epoch 1/50

/usr/local/lib/python3.13/dist-packages/sklearn/utils/extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.13/dist-packages/sklearn/utils/extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.13/dist-packages/sklearn/utils/extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5086 - auc: 0.5000 - loss: nan - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1: val_auc improved from None to 0.50000, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 1: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 7s 47ms/step - accuracy: 0.5000 - auc: 0.5000 - loss: nan - precision: 0.0000e+00 - recall: 0.0000e+00 - val_accuracy: 0.5000 - val_auc: 0.5000 - val_loss: nan - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/50
66/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5105 - auc: 0.5000 - loss: nan - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 2: val_auc did not improve from 0.50000
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5000 - auc: 0.5000 - loss: nan - precision: 0.0000e+00 - recall: 0.0000e+00 - val_accuracy: 0.5000 - val_auc: 0.5000 - val_loss: nan - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/50
65/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5107 - auc: 0.5000 - loss: nan - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 3: val_auc did not improve from 0.50000
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5000 - auc: 0.5000 - loss: nan - precision: 0.0000e+00 - recall: 0.0000e+00 - val_accuracy: 0.5000 - val_auc: 0.5000 - val_loss: nan - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 4/50
65/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5107 - auc: 0.5000 - loss: nan - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 4: val_auc did not improve from 0.50000
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5000 - auc: 0.5000 - loss: nan - precision: 0.0000e+00 - recall: 0.0000e+00 - val_accuracy: 0.5000 - val_auc: 0.5000 - val_loss: nan - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 5/50
63/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5111 - auc: 0.5000 - loss: nan - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 5: val_auc did not improve from 0.50000
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5000 - auc: 0.5000 - loss: nan - precision: 0.0000e+00 - recall: 0.0000e+00 - val_accuracy: 0.5000 - val_auc: 0.5000 - val_loss: nan - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 6/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5109 - auc: 0.5000 - loss: nan - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 6: val_auc did not improve from 0.50000
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5000 - auc: 0.5000 - loss: nan - precision: 0.0000e+00 - recall: 0.0000e+00 - val_accuracy: 0.5000 - val_auc: 0.5000 - val_loss: nan - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 6: early stopping
Restoring model weights from the end of the best epoch: 1.

Training complete.
Best model: /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
History: /kaggle/working/asd_care_results/questionnaire_mlp_history.json
Scaler details: /kaggle/working/asd_care_results/questionnaire_scaler.json

In [21]:

# Cell 20B: FIXED questionnaire-only model
# Correctly encodes categorical features.
# Does NOT overwrite MobileNetV2 artifacts.

import os
import json
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix,
    classification_report
)

SEED = 42
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

DATA_DIR = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset/Dataset_csv"
)
OUT_DIR = "/kaggle/working/asd_care_results"
os.makedirs(OUT_DIR, exist_ok=True)

train_df = pd.read_csv(os.path.join(DATA_DIR, "train.csv"))
valid_df = pd.read_csv(os.path.join(DATA_DIR, "valid.csv"))
test_df  = pd.read_csv(os.path.join(DATA_DIR, "test.csv"))

NUMERIC_FEATURES = [
    "A1", "A2", "A3", "A4", "A5",
    "A6", "A7", "A8", "A9", "A10", "Age"
]
CATEGORICAL_FEATURES = ["Sex", "Jauundice", "Family_ASD"]
FEATURES = NUMERIC_FEATURES + CATEGORICAL_FEATURES
TARGET = "Class"

# Confirm expected columns.
for name, df in [
    ("train", train_df), ("valid", valid_df), ("test", test_df)
]:
    missing = [c for c in FEATURES + [TARGET] if c not in df.columns]
    if missing:
        raise ValueError(f"{name}.csv missing columns: {missing}")

# Convert genuine numeric columns only.
for df in [train_df, valid_df, test_df]:
    for col in NUMERIC_FEATURES:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# Impute numeric missing values using training medians only.
numeric_medians = train_df[NUMERIC_FEATURES].median()
if numeric_medians.isna().any():
    raise ValueError(
        "At least one numeric feature is entirely missing in training data."
    )

for df in [train_df, valid_df, test_df]:
    df[NUMERIC_FEATURES] = df[NUMERIC_FEATURES].fillna(numeric_medians)

# Normalize numerical features using training data only.
scaler = StandardScaler()
X_train_num = scaler.fit_transform(
    train_df[NUMERIC_FEATURES]
).astype("float32")
X_valid_num = scaler.transform(
    valid_df[NUMERIC_FEATURES]
).astype("float32")
X_test_num = scaler.transform(
    test_df[NUMERIC_FEATURES]
).astype("float32")

# One-hot encode categories using training categories only.
train_cat = train_df[CATEGORICAL_FEATURES].fillna("unknown").astype(str)
valid_cat = valid_df[CATEGORICAL_FEATURES].fillna("unknown").astype(str)
test_cat  = test_df[CATEGORICAL_FEATURES].fillna("unknown").astype(str)

cat_columns = []
category_levels = {}

for col in CATEGORICAL_FEATURES:
    levels = sorted(train_cat[col].unique().tolist())
    category_levels[col] = levels

    # Fixed columns ensure identical feature layout for every split.
    for level in levels:
        safe_level = level.replace(" ", "_")
        new_col = f"{col}__{safe_level}"
        cat_columns.append((col, level, new_col))

def encode_categories(frame):
    encoded = []
    for col, level, new_col in cat_columns:
        encoded.append(
            (frame[col] == level).to_numpy(dtype="float32")
        )
    return np.column_stack(encoded).astype("float32")

X_train_cat = encode_categories(train_cat)
X_valid_cat = encode_categories(valid_cat)
X_test_cat  = encode_categories(test_cat)

X_train = np.concatenate([X_train_num, X_train_cat], axis=1)
X_valid = np.concatenate([X_valid_num, X_valid_cat], axis=1)
X_test  = np.concatenate([X_test_num, X_test_cat], axis=1)

def encode_labels(series):
    s = series.astype(str).str.strip().str.upper()
    mapping = {
        "YES": 1, "NO": 0,
        "ASD": 1, "TD": 0,
        "AUTISTIC": 1, "NON_AUTISTIC": 0,
        "NON-AUTISTIC": 0,
        "TRUE": 1, "FALSE": 0,
        "1": 1, "0": 0
    }
    result = s.map(mapping)
    if result.isna().any():
        raise ValueError(
            f"Unexpected labels: {sorted(s[result.isna()].unique())}"
        )
    return result.to_numpy(dtype="int32")

y_train = encode_labels(train_df[TARGET])
y_valid = encode_labels(valid_df[TARGET])
y_test_q = encode_labels(test_df[TARGET])

# Safety checks before training.
for name, X in [
    ("train", X_train), ("validation", X_valid), ("test", X_test)
]:
    if not np.isfinite(X).all():
        raise ValueError(f"{name} features still contain NaN or infinity.")

print("Train:", X_train.shape, "labels:", np.bincount(y_train))
print("Valid:", X_valid.shape, "labels:", np.bincount(y_valid))
print("Test: ", X_test.shape, "labels:", np.bincount(y_test_q))
print("All feature matrices are finite.")

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(32, activation="relu"),
    tf.keras.layers.Dropout(0.30),
    tf.keras.layers.Dense(16, activation="relu"),
    tf.keras.layers.Dropout(0.20),
    tf.keras.layers.Dense(1, activation="sigmoid")
], name="questionnaire_only_mlp")

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

MODEL_PATH = os.path.join(OUT_DIR, "questionnaire_mlp_best.keras")

callbacks = [
    tf.keras.callbacks.ModelCheckpoint(
        MODEL_PATH, monitor="val_auc", mode="max",
        save_best_only=True, verbose=1
    ),
    tf.keras.callbacks.EarlyStopping(
        monitor="val_auc", mode="max",
        patience=5, restore_best_weights=True, verbose=1
    ),
    tf.keras.callbacks.CSVLogger(
        os.path.join(OUT_DIR, "questionnaire_mlp_training_log.csv")
    )
]

history = model.fit(
    X_train, y_train,
    validation_data=(X_valid, y_valid),
    epochs=50,
    batch_size=32,
    callbacks=callbacks,
    verbose=1
)

with open(os.path.join(OUT_DIR, "questionnaire_mlp_history.json"), "w") as f:
    json.dump(
        {k: [float(v) for v in vals]
         for k, vals in history.history.items()},
        f, indent=2
    )

with open(os.path.join(OUT_DIR, "questionnaire_preprocessing.json"), "w") as f:
    json.dump({
        "numeric_features": NUMERIC_FEATURES,
        "categorical_features": CATEGORICAL_FEATURES,
        "category_levels": category_levels,
        "numeric_medians": numeric_medians.to_dict(),
        "scaler_mean": scaler.mean_.tolist(),
        "scaler_scale": scaler.scale_.tolist(),
        "encoded_feature_count": int(X_train.shape[1])
    }, f, indent=2)

print("\nQuestionnaire training complete.")
print("Best model saved:", MODEL_PATH)

Train: (2526, 17) labels: [1263 1263]
Valid: (200, 17) labels: [100 100]
Test:  (200, 17) labels: [100 100]
All feature matrices are finite.
Epoch 1/50
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6827 - auc: 0.7734 - loss: 0.5846 - precision: 0.7071 - recall: 0.5930
Epoch 1: val_auc improved from None to 0.94005, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 1: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.7546 - auc: 0.8471 - loss: 0.5183 - precision: 0.7718 - recall: 0.7229 - val_accuracy: 0.8700 - val_auc: 0.9401 - val_loss: 0.3541 - val_precision: 0.8491 - val_recall: 0.9000
Epoch 2/50
65/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8652 - auc: 0.9256 - loss: 0.3645 - precision: 0.8435 - recall: 0.8897
Epoch 2: val_auc improved from 0.94005 to 0.95775, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 2: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8761 - auc: 0.9322 - loss: 0.3323 - precision: 0.8539 - recall: 0.9074 - val_accuracy: 0.9200 - val_auc: 0.9577 - val_loss: 0.2452 - val_precision: 0.8684 - val_recall: 0.9900
Epoch 3/50
62/79 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9121 - auc: 0.9559 - loss: 0.2598 - precision: 0.8846 - recall: 0.9435
Epoch 3: val_auc improved from 0.95775 to 0.96460, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 3: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9070 - auc: 0.9564 - loss: 0.2522 - precision: 0.8774 - recall: 0.9462 - val_accuracy: 0.9350 - val_auc: 0.9646 - val_loss: 0.2106 - val_precision: 0.8919 - val_recall: 0.9900
Epoch 4/50
63/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9107 - auc: 0.9630 - loss: 0.2293 - precision: 0.8837 - recall: 0.9414
Epoch 4: val_auc improved from 0.96460 to 0.96780, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 4: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9082 - auc: 0.9597 - loss: 0.2368 - precision: 0.8833 - recall: 0.9406 - val_accuracy: 0.9400 - val_auc: 0.9678 - val_loss: 0.1917 - val_precision: 0.9000 - val_recall: 0.9900
Epoch 5/50
65/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9198 - auc: 0.9608 - loss: 0.2271 - precision: 0.8924 - recall: 0.9500
Epoch 5: val_auc improved from 0.96780 to 0.97045, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 5: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9256 - auc: 0.9633 - loss: 0.2177 - precision: 0.8979 - recall: 0.9604 - val_accuracy: 0.9500 - val_auc: 0.9704 - val_loss: 0.1770 - val_precision: 0.9167 - val_recall: 0.9900
Epoch 6/50
66/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9315 - auc: 0.9642 - loss: 0.2087 - precision: 0.9003 - recall: 0.9673
Epoch 6: val_auc improved from 0.97045 to 0.97560, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 6: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9303 - auc: 0.9655 - loss: 0.2046 - precision: 0.9005 - recall: 0.9675 - val_accuracy: 0.9500 - val_auc: 0.9756 - val_loss: 0.1622 - val_precision: 0.9167 - val_recall: 0.9900
Epoch 7/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9323 - auc: 0.9645 - loss: 0.2037 - precision: 0.9072 - recall: 0.9594
Epoch 7: val_auc improved from 0.97560 to 0.98020, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 7: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9335 - auc: 0.9674 - loss: 0.1972 - precision: 0.9053 - recall: 0.9683 - val_accuracy: 0.9500 - val_auc: 0.9802 - val_loss: 0.1500 - val_precision: 0.9167 - val_recall: 0.9900
Epoch 8/50
66/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9388 - auc: 0.9758 - loss: 0.1722 - precision: 0.9074 - recall: 0.9744
Epoch 8: val_auc improved from 0.98020 to 0.98325, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 8: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9398 - auc: 0.9754 - loss: 0.1717 - precision: 0.9112 - recall: 0.9747 - val_accuracy: 0.9500 - val_auc: 0.9832 - val_loss: 0.1394 - val_precision: 0.9167 - val_recall: 0.9900
Epoch 9/50
65/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9366 - auc: 0.9743 - loss: 0.1730 - precision: 0.9022 - recall: 0.9763
Epoch 9: val_auc improved from 0.98325 to 0.98715, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 9: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9382 - auc: 0.9754 - loss: 0.1703 - precision: 0.9097 - recall: 0.9731 - val_accuracy: 0.9500 - val_auc: 0.9872 - val_loss: 0.1301 - val_precision: 0.9167 - val_recall: 0.9900
Epoch 10/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9439 - auc: 0.9755 - loss: 0.1657 - precision: 0.9069 - recall: 0.9866
Epoch 10: val_auc improved from 0.98715 to 0.98915, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 10: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9406 - auc: 0.9795 - loss: 0.1593 - precision: 0.9095 - recall: 0.9786 - val_accuracy: 0.9500 - val_auc: 0.9891 - val_loss: 0.1235 - val_precision: 0.9167 - val_recall: 0.9900
Epoch 11/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9496 - auc: 0.9841 - loss: 0.1417 - precision: 0.9143 - recall: 0.9898
Epoch 11: val_auc improved from 0.98915 to 0.99350, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 11: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9481 - auc: 0.9836 - loss: 0.1419 - precision: 0.9199 - recall: 0.9818 - val_accuracy: 0.9500 - val_auc: 0.9935 - val_loss: 0.1135 - val_precision: 0.9167 - val_recall: 0.9900
Epoch 12/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9480 - auc: 0.9824 - loss: 0.1461 - precision: 0.9091 - recall: 0.9931
Epoch 12: val_auc improved from 0.99350 to 0.99575, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 12: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9509 - auc: 0.9843 - loss: 0.1381 - precision: 0.9209 - recall: 0.9865 - val_accuracy: 0.9500 - val_auc: 0.9958 - val_loss: 0.1076 - val_precision: 0.9167 - val_recall: 0.9900
Epoch 13/50
65/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9475 - auc: 0.9856 - loss: 0.1303 - precision: 0.9189 - recall: 0.9790
Epoch 13: val_auc improved from 0.99575 to 0.99640, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 13: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9489 - auc: 0.9872 - loss: 0.1276 - precision: 0.9200 - recall: 0.9834 - val_accuracy: 0.9500 - val_auc: 0.9964 - val_loss: 0.1021 - val_precision: 0.9167 - val_recall: 0.9900
Epoch 14/50
63/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9450 - auc: 0.9852 - loss: 0.1361 - precision: 0.9140 - recall: 0.9796
Epoch 14: val_auc improved from 0.99640 to 0.99690, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 14: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9470 - auc: 0.9861 - loss: 0.1328 - precision: 0.9191 - recall: 0.9802 - val_accuracy: 0.9450 - val_auc: 0.9969 - val_loss: 0.0976 - val_precision: 0.9159 - val_recall: 0.9800
Epoch 15/50
62/79 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9562 - auc: 0.9848 - loss: 0.1298 - precision: 0.9236 - recall: 0.9924
Epoch 15: val_auc improved from 0.99690 to 0.99705, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 15: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9561 - auc: 0.9880 - loss: 0.1217 - precision: 0.9267 - recall: 0.9905 - val_accuracy: 0.9450 - val_auc: 0.9970 - val_loss: 0.0942 - val_precision: 0.9159 - val_recall: 0.9800
Epoch 16/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9583 - auc: 0.9909 - loss: 0.1113 - precision: 0.9262 - recall: 0.9940
Epoch 16: val_auc improved from 0.99705 to 0.99705, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 16: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9572 - auc: 0.9914 - loss: 0.1102 - precision: 0.9319 - recall: 0.9865 - val_accuracy: 0.9500 - val_auc: 0.9970 - val_loss: 0.0887 - val_precision: 0.9245 - val_recall: 0.9800
Epoch 17/50
66/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9604 - auc: 0.9911 - loss: 0.1102 - precision: 0.9294 - recall: 0.9948
Epoch 17: val_auc did not improve from 0.99705
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9588 - auc: 0.9914 - loss: 0.1080 - precision: 0.9321 - recall: 0.9897 - val_accuracy: 0.9500 - val_auc: 0.9969 - val_loss: 0.0872 - val_precision: 0.9245 - val_recall: 0.9800
Epoch 18/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9563 - auc: 0.9924 - loss: 0.1024 - precision: 0.9303 - recall: 0.9845
Epoch 18: val_auc improved from 0.99705 to 0.99715, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 18: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9553 - auc: 0.9920 - loss: 0.1047 - precision: 0.9310 - recall: 0.9834 - val_accuracy: 0.9500 - val_auc: 0.9972 - val_loss: 0.0823 - val_precision: 0.9245 - val_recall: 0.9800
Epoch 19/50
63/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9612 - auc: 0.9908 - loss: 0.1077 - precision: 0.9297 - recall: 0.9959
Epoch 19: val_auc improved from 0.99715 to 0.99735, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 19: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9596 - auc: 0.9923 - loss: 0.1028 - precision: 0.9348 - recall: 0.9881 - val_accuracy: 0.9550 - val_auc: 0.9973 - val_loss: 0.0804 - val_precision: 0.9252 - val_recall: 0.9900
Epoch 20/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9565 - auc: 0.9931 - loss: 0.1002 - precision: 0.9276 - recall: 0.9883
Epoch 20: val_auc did not improve from 0.99735
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9600 - auc: 0.9932 - loss: 0.0984 - precision: 0.9375 - recall: 0.9857 - val_accuracy: 0.9500 - val_auc: 0.9973 - val_loss: 0.0787 - val_precision: 0.9245 - val_recall: 0.9800
Epoch 21/50
66/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9578 - auc: 0.9923 - loss: 0.0992 - precision: 0.9284 - recall: 0.9899
Epoch 21: val_auc improved from 0.99735 to 0.99750, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 21: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9604 - auc: 0.9934 - loss: 0.0946 - precision: 0.9349 - recall: 0.9897 - val_accuracy: 0.9600 - val_auc: 0.9975 - val_loss: 0.0750 - val_precision: 0.9340 - val_recall: 0.9900
Epoch 22/50
65/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9586 - auc: 0.9938 - loss: 0.0950 - precision: 0.9321 - recall: 0.9872
Epoch 22: val_auc did not improve from 0.99750
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9592 - auc: 0.9937 - loss: 0.0937 - precision: 0.9367 - recall: 0.9850 - val_accuracy: 0.9600 - val_auc: 0.9972 - val_loss: 0.0755 - val_precision: 0.9340 - val_recall: 0.9900
Epoch 23/50
66/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9693 - auc: 0.9956 - loss: 0.0834 - precision: 0.9470 - recall: 0.9929
Epoch 23: val_auc did not improve from 0.99750
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9663 - auc: 0.9947 - loss: 0.0877 - precision: 0.9455 - recall: 0.9897 - val_accuracy: 0.9600 - val_auc: 0.9974 - val_loss: 0.0744 - val_precision: 0.9340 - val_recall: 0.9900
Epoch 24/50
65/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9688 - auc: 0.9965 - loss: 0.0799 - precision: 0.9457 - recall: 0.9929
Epoch 24: val_auc improved from 0.99750 to 0.99765, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 24: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9691 - auc: 0.9958 - loss: 0.0807 - precision: 0.9492 - recall: 0.9913 - val_accuracy: 0.9650 - val_auc: 0.9977 - val_loss: 0.0714 - val_precision: 0.9429 - val_recall: 0.9900
Epoch 25/50
63/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9642 - auc: 0.9956 - loss: 0.0840 - precision: 0.9428 - recall: 0.9867
Epoch 25: val_auc did not improve from 0.99765
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9652 - auc: 0.9955 - loss: 0.0821 - precision: 0.9488 - recall: 0.9834 - val_accuracy: 0.9550 - val_auc: 0.9976 - val_loss: 0.0711 - val_precision: 0.9333 - val_recall: 0.9800
Epoch 26/50
63/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9713 - auc: 0.9962 - loss: 0.0770 - precision: 0.9495 - recall: 0.9943
Epoch 26: val_auc improved from 0.99765 to 0.99775, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 26: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9671 - auc: 0.9963 - loss: 0.0775 - precision: 0.9456 - recall: 0.9913 - val_accuracy: 0.9600 - val_auc: 0.9977 - val_loss: 0.0681 - val_precision: 0.9423 - val_recall: 0.9800
Epoch 27/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9644 - auc: 0.9962 - loss: 0.0788 - precision: 0.9490 - recall: 0.9801
Epoch 27: val_auc improved from 0.99775 to 0.99795, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 27: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9660 - auc: 0.9963 - loss: 0.0772 - precision: 0.9537 - recall: 0.9794 - val_accuracy: 0.9600 - val_auc: 0.9979 - val_loss: 0.0687 - val_precision: 0.9340 - val_recall: 0.9900
Epoch 28/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9666 - auc: 0.9949 - loss: 0.0867 - precision: 0.9460 - recall: 0.9878
Epoch 28: val_auc improved from 0.99795 to 0.99810, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 28: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9715 - auc: 0.9962 - loss: 0.0753 - precision: 0.9563 - recall: 0.9881 - val_accuracy: 0.9650 - val_auc: 0.9981 - val_loss: 0.0655 - val_precision: 0.9429 - val_recall: 0.9900
Epoch 29/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9677 - auc: 0.9953 - loss: 0.0794 - precision: 0.9489 - recall: 0.9873
Epoch 29: val_auc improved from 0.99810 to 0.99845, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 29: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9679 - auc: 0.9964 - loss: 0.0743 - precision: 0.9532 - recall: 0.9842 - val_accuracy: 0.9700 - val_auc: 0.9984 - val_loss: 0.0647 - val_precision: 0.9434 - val_recall: 1.0000
Epoch 30/50
63/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9730 - auc: 0.9969 - loss: 0.0711 - precision: 0.9536 - recall: 0.9930
Epoch 30: val_auc did not improve from 0.99845
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9715 - auc: 0.9970 - loss: 0.0702 - precision: 0.9556 - recall: 0.9889 - val_accuracy: 0.9600 - val_auc: 0.9980 - val_loss: 0.0639 - val_precision: 0.9423 - val_recall: 0.9800
Epoch 31/50
63/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9727 - auc: 0.9955 - loss: 0.0773 - precision: 0.9590 - recall: 0.9864
Epoch 31: val_auc did not improve from 0.99845
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9691 - auc: 0.9961 - loss: 0.0743 - precision: 0.9589 - recall: 0.9802 - val_accuracy: 0.9750 - val_auc: 0.9983 - val_loss: 0.0617 - val_precision: 0.9524 - val_recall: 1.0000
Epoch 32/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9710 - auc: 0.9951 - loss: 0.0792 - precision: 0.9556 - recall: 0.9861
Epoch 32: val_auc improved from 0.99845 to 0.99870, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 32: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9723 - auc: 0.9964 - loss: 0.0711 - precision: 0.9599 - recall: 0.9857 - val_accuracy: 0.9700 - val_auc: 0.9987 - val_loss: 0.0585 - val_precision: 0.9434 - val_recall: 1.0000
Epoch 33/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9610 - auc: 0.9959 - loss: 0.0787 - precision: 0.9470 - recall: 0.9744
Epoch 33: val_auc improved from 0.99870 to 0.99880, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 33: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9660 - auc: 0.9960 - loss: 0.0760 - precision: 0.9537 - recall: 0.9794 - val_accuracy: 0.9650 - val_auc: 0.9988 - val_loss: 0.0572 - val_precision: 0.9515 - val_recall: 0.9800
Epoch 34/50
62/79 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9646 - auc: 0.9967 - loss: 0.0726 - precision: 0.9514 - recall: 0.9775
Epoch 34: val_auc improved from 0.99880 to 0.99895, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 34: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9683 - auc: 0.9967 - loss: 0.0719 - precision: 0.9554 - recall: 0.9826 - val_accuracy: 0.9700 - val_auc: 0.9989 - val_loss: 0.0556 - val_precision: 0.9519 - val_recall: 0.9900
Epoch 35/50
67/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9800 - auc: 0.9987 - loss: 0.0567 - precision: 0.9656 - recall: 0.9946
Epoch 35: val_auc improved from 0.99895 to 0.99900, saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras

Epoch 35: finished saving model to /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9751 - auc: 0.9978 - loss: 0.0619 - precision: 0.9637 - recall: 0.9873 - val_accuracy: 0.9650 - val_auc: 0.9990 - val_loss: 0.0553 - val_precision: 0.9429 - val_recall: 0.9900
Epoch 36/50
64/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9750 - auc: 0.9982 - loss: 0.0580 - precision: 0.9643 - recall: 0.9853
Epoch 36: val_auc did not improve from 0.99900

In [6]:

# Cell 24: Locate saved experiment files
import os

targets = {
    "mobilenetv2_best.keras",
    "mobilenetv2_test_results.json",
    "mobilenetv2_test_predictions.npz",
    "questionnaire_mlp_best.keras",
    "questionnaire_mlp_test_results.json",
    "questionnaire_mlp_test_predictions.npz",
    "efficientnetb0_best.keras",
}

roots = [
    "/kaggle/working",
    "/kaggle/input/datasets/shahbaz18/asd-full-backup",
    "/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset",
]

found = []
for root in roots:
    if not os.path.isdir(root):
        print("PATH NOT AVAILABLE:", root)
        continue

    print("\nSearching:", root)
    for current, dirs, files in os.walk(root):
        # Avoid descending into unrelated hidden folders
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        for name in files:
            if name in targets or (
                name.endswith(".keras") and
                any(key in name.lower() for key in
                    ["mobilenet", "questionnaire", "efficientnet"])
            ):
                path = os.path.join(current, name)
                found.append(path)
                print("FOUND:", path)

if not found:
    print("\nNo matching files found in these locations.")
else:
    print(f"\nTotal matching files: {len(found)}")

Searching: /kaggle/working
FOUND: /kaggle/working/asd_care_results/mobilenetv2_test_predictions.npz
FOUND: /kaggle/working/asd_care_results/questionnaire_mlp_best.keras
FOUND: /kaggle/working/asd_care_results/mobilenetv2_best.keras
FOUND: /kaggle/working/asd_care_results/mobilenetv2_test_results.json
PATH NOT AVAILABLE: /kaggle/input/datasets/shahbaz18/asd-full-backup

Searching: /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset

Total matching files: 4

In [22]:

# Cell: Verify checkpoints and create a recovery archive
import os
import zipfile

out = "/kaggle/working/asd_care_results"
os.makedirs(out, exist_ok=True)

required = [
    "mobilenetv2_best.keras",
    "questionnaire_mlp_best.keras",
    "mobilenetv2_test_predictions.npz",
    "mobilenetv2_test_results.json",
]

print("CHECKPOINT VERIFICATION")
for name in required:
    path = os.path.join(out, name)
    exists = os.path.isfile(path)
    size_mb = os.path.getsize(path) / (1024 * 1024) if exists else 0
    print(f"{'FOUND' if exists else 'MISSING'}: {name} ({size_mb:.2f} MB)")

archive = "/kaggle/working/asd_care_recovery.zip"
with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as z:
    for root, _, files in os.walk(out):
        for name in files:
            path = os.path.join(root, name)
            z.write(path, arcname=os.path.relpath(path, "/kaggle/working"))

print("\nRecovery ZIP:", archive)
print("ZIP size (MB):", round(os.path.getsize(archive) / (1024 * 1024), 2))

CHECKPOINT VERIFICATION
FOUND: mobilenetv2_best.keras (11.06 MB)
FOUND: questionnaire_mlp_best.keras (0.04 MB)
FOUND: mobilenetv2_test_predictions.npz (0.00 MB)
FOUND: mobilenetv2_test_results.json (0.00 MB)

Recovery ZIP: /kaggle/working/asd_care_recovery.zip
ZIP size (MB): 9.84

In [23]:

# Cell: Rebuild Questionnaire MLP Test Results — no training
import os
import json
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix
)

out = "/kaggle/working/asd_care_results"
csv_path = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset/"
    "Dataset_csv/test.csv"
)

# Load saved preprocessing configuration and test data
with open(os.path.join(out, "questionnaire_preprocessing.json")) as f:
    prep = json.load(f)

df = pd.read_csv(csv_path)

numeric = prep["numeric_features"]
categorical = prep["categorical_features"]

# Recreate numeric preprocessing
num = df[numeric].apply(pd.to_numeric, errors="coerce")
for col in numeric:
    num[col] = num[col].fillna(prep["numeric_medians"][col])

means = np.array(prep["scaler_mean"], dtype=float)
scales = np.array(prep["scaler_scale"], dtype=float)
X_num = (num.to_numpy(dtype=float) - means) / scales

# Recreate categorical one-hot encoding in saved order
cat_parts = []
for col in categorical:
    values = df[col].astype(str).str.strip().str.lower()
    levels = prep["category_levels"][col]
    encoded = np.column_stack([
        (values == level).astype(np.float32)
        for level in levels
    ])
    cat_parts.append(encoded)

X = np.concatenate([X_num, *cat_parts], axis=1).astype(np.float32)

# Validate before inference
assert X.shape[1] == prep["encoded_feature_count"] == 17, X.shape
assert len(X) == len(df)

y_true = (df["Class"].astype(str).str.strip().str.upper() == "YES").astype(int).to_numpy()

# Load checkpoint and predict
model = tf.keras.models.load_model(
    os.path.join(out, "questionnaire_mlp_best.keras")
)
y_prob = model.predict(X, verbose=0).reshape(-1)
y_pred = (y_prob >= 0.5).astype(int)

results = {
    "model": "Questionnaire-only MLP",
    "test_samples": int(len(y_true)),
    "accuracy": float(accuracy_score(y_true, y_pred)),
    "precision": float(precision_score(y_true, y_pred, zero_division=0)),
    "recall": float(recall_score(y_true, y_pred, zero_division=0)),
    "f1": float(f1_score(y_true, y_pred, zero_division=0)),
    "roc_auc": float(roc_auc_score(y_true, y_prob)),
    "confusion_matrix": confusion_matrix(
        y_true, y_pred, labels=[0, 1]
    ).tolist(),
    "threshold": 0.5,
    "note": "Re-evaluated from saved checkpoint and reconstructed preprocessing."
}

with open(os.path.join(out, "questionnaire_mlp_test_results.json"), "w") as f:
    json.dump(results, f, indent=2)

np.savez_compressed(
    os.path.join(out, "questionnaire_mlp_test_predictions.npz"),
    y_true=y_true,
    y_prob=y_prob,
    y_pred=y_pred
)

print(json.dumps(results, indent=2))
print("\nSaved questionnaire test results and predictions.")

{
  "model": "Questionnaire-only MLP",
  "test_samples": 200,
  "accuracy": 0.985,
  "precision": 0.970873786407767,
  "recall": 1.0,
  "f1": 0.9852216748768473,
  "roc_auc": 0.9998,
  "confusion_matrix": [
    [
      97,
      3
    ],
    [
      0,
      100
    ]
  ],
  "threshold": 0.5,
  "note": "Re-evaluated from saved checkpoint and reconstructed preprocessing."
}

Saved questionnaire test results and predictions.

In [24]:

# Cell: Backup all current experiment results
import os
import zipfile

out = "/kaggle/working/asd_care_results"
archive = "/kaggle/working/asd_care_recovery.zip"

assert os.path.isfile(os.path.join(out, "mobilenetv2_best.keras"))
assert os.path.isfile(os.path.join(out, "questionnaire_mlp_best.keras"))
assert os.path.isfile(os.path.join(out, "questionnaire_mlp_test_results.json"))
assert os.path.isfile(os.path.join(out, "questionnaire_mlp_test_predictions.npz"))

with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as z:
    for root, _, files in os.walk(out):
        for name in files:
            path = os.path.join(root, name)
            z.write(path, os.path.relpath(path, "/kaggle/working"))

print("Backup created:", archive)
print("Size (MB):", round(os.path.getsize(archive) / (1024 * 1024), 2))
print("\nFiles included:")
with zipfile.ZipFile(archive) as z:
    for name in z.namelist():
        print(name)

Backup created: /kaggle/working/asd_care_recovery.zip
Size (MB): 9.85

Files included:
asd_care_results/mobilenetv2_test_predictions.npz
asd_care_results/questionnaire_mlp_best.keras
asd_care_results/mobilenetv2_best.keras
asd_care_results/questionnaire_mlp_training_log.csv
asd_care_results/questionnaire_scaler.json
asd_care_results/mobilenetv2_test_results.json
asd_care_results/questionnaire_mlp_history.json
asd_care_results/mobilenetv2_training_log.csv
asd_care_results/questionnaire_mlp_test_results.json
asd_care_results/mobilenetv2_history.json
asd_care_results/questionnaire_preprocessing.json
asd_care_results/questionnaire_mlp_test_predictions.npz

In [25]:

# Cell: EfficientNetB0 Resume Check — no training
import os
import tensorflow as tf

out = "/kaggle/working/asd_care_results"

print("TensorFlow:", tf.__version__)
print("GPU devices:", tf.config.list_physical_devices("GPU"))

print("\nExisting EfficientNetB0 files:")
for name in [
    "efficientnetb0_best.keras",
    "efficientnetb0_history.json",
    "efficientnetb0_training_log.csv",
    "efficientnetb0_test_results.json",
    "efficientnetb0_test_predictions.npz",
]:
    path = os.path.join(out, name)
    print(("FOUND   " if os.path.isfile(path) else "MISSING "), name)

print("\nDataset split files:")
base = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)
for name in ["train.csv", "valid.csv", "test.csv"]:
    path = os.path.join(base, "Dataset_csv", name)
    print(("FOUND   " if os.path.isfile(path) else "MISSING "), path)

TensorFlow: 2.20.0
GPU devices: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

Existing EfficientNetB0 files:
MISSING  efficientnetb0_best.keras
MISSING  efficientnetb0_history.json
MISSING  efficientnetb0_training_log.csv
MISSING  efficientnetb0_test_results.json
MISSING  efficientnetb0_test_predictions.npz

Dataset split files:
FOUND    /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_csv/train.csv
FOUND    /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_csv/valid.csv
FOUND    /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_csv/test.csv

In [26]:

# Cell: EfficientNetB0 Dataset Preflight — no training
import os
import pandas as pd

base = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)
csv_dir = os.path.join(base, "Dataset_csv")

for split in ["train", "valid", "test"]:
    path = os.path.join(csv_dir, f"{split}.csv")
    df = pd.read_csv(path)

    print(f"\n=== {split.upper()} ===")
    print("Rows:", len(df))
    print("Columns:", df.columns.tolist())
    print("Class counts:")
    print(df["Class"].value_counts(dropna=False).to_dict())

    # Validate image paths without loading the images
    missing = []
    for p in df["image_path"].dropna().astype(str):
        if not os.path.isfile(p):
            missing.append(p)

    print("Missing image paths:", len(missing))
    if missing:
        print("Examples:", missing[:5])

print("\nPreflight complete. No model trained.")

=== TRAIN ===
Rows: 2526
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']
Class counts:
{'YES': 1263, 'NO': 1263}
Missing image paths: 0

=== VALID ===
Rows: 200
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']
Class counts:
{'YES': 100, 'NO': 100}
Missing image paths: 0

=== TEST ===
Rows: 200
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']
Class counts:
{'YES': 100, 'NO': 100}
Missing image paths: 0

Preflight complete. No model trained.

In [27]:

# Cell: Train EfficientNetB0 — checkpointed and resumable
import os
import json
import tensorflow as tf
import pandas as pd
import numpy as np

from tensorflow.keras import layers, Model
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.callbacks import (
    ModelCheckpoint, EarlyStopping, CSVLogger
)

SEED = 42
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
EPOCHS = 10

tf.keras.utils.set_random_seed(SEED)

out = "/kaggle/working/asd_care_results"
os.makedirs(out, exist_ok=True)

base = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)
csv_dir = os.path.join(base, "Dataset_csv")

# Load split manifests
train_df = pd.read_csv(os.path.join(csv_dir, "train.csv"))
valid_df = pd.read_csv(os.path.join(csv_dir, "valid.csv"))
test_df  = pd.read_csv(os.path.join(csv_dir, "test.csv"))

def make_dataset(df, training=False):
    paths = df["image_path"].astype(str).to_numpy()
    labels = (
        df["Class"].astype(str).str.strip().str.upper() == "YES"
    ).astype(np.float32).to_numpy()

    ds = tf.data.Dataset.from_tensor_slices((paths, labels))

    def load_image(path, label):
        image_bytes = tf.io.read_file(path)
        image = tf.io.decode_image(
            image_bytes, channels=3, expand_animations=False
        )
        image.set_shape([None, None, 3])
        image = tf.image.resize(image, IMG_SIZE)
        image = tf.cast(image, tf.float32)
        return image, label

    ds = ds.map(load_image, num_parallel_calls=tf.data.AUTOTUNE)
    if training:
        ds = ds.shuffle(len(df), seed=SEED, reshuffle_each_iteration=True)
    return ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

train_ds = make_dataset(train_df, training=True)
valid_ds = make_dataset(valid_df)
test_ds = make_dataset(test_df)

# Build model
backbone = EfficientNetB0(
    include_top=False,
    weights="imagenet",
    input_shape=(224, 224, 3)
)
backbone.trainable = False

inputs = layers.Input(shape=(224, 224, 3))
x = backbone(inputs, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model = Model(inputs, outputs, name="EfficientNetB0_ASD_image_only")

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.AUC(name="auc")
    ]
)

checkpoint = os.path.join(out, "efficientnetb0_best.keras")
history_path = os.path.join(out, "efficientnetb0_history.json")
log_path = os.path.join(out, "efficientnetb0_training_log.csv")

callbacks = [
    ModelCheckpoint(
        checkpoint, monitor="val_auc", mode="max",
        save_best_only=True, verbose=1
    ),
    EarlyStopping(
        monitor="val_auc", mode="max",
        patience=3, restore_best_weights=True, verbose=1
    ),
    CSVLogger(log_path, append=True)
]

print("Train:", len(train_df), "| Validation:", len(valid_df))
print("GPUs:", tf.config.list_physical_devices("GPU"))
print("Starting EfficientNetB0 training...")

hist = model.fit(
    train_ds,
    validation_data=valid_ds,
    epochs=EPOCHS,
    callbacks=callbacks,
    verbose=1
)

with open(history_path, "w") as f:
    json.dump(
        {k: [float(v) for v in values]
         for k, values in hist.history.items()},
        f, indent=2
    )

print("\nTraining finished.")
print("Best checkpoint exists:", os.path.isfile(checkpoint))
print("History saved:", os.path.isfile(history_path))
print("Training log saved:", os.path.isfile(log_path))

Downloading data from https://storage.googleapis.com/keras-applications/efficientnetb0_notop.h5
16705208/16705208 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Train: 2526 | Validation: 200
GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]
Starting EfficientNetB0 training...
Epoch 1/10

2026-10-23 01:16:57.693649: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:16:57.836442: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:16:58.184942: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:16:58.327104: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:16:59.132250: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:16:59.273217: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

77/79 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6712 - auc: 0.7318 - loss: 0.6080

2026-10-23 01:17:13.447469: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:17:13.589994: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:17:13.934163: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:17:14.076122: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:17:14.856897: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:17:14.998286: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step - accuracy: 0.6721 - auc: 0.7330 - loss: 0.6071

2026-10-23 01:17:33.516048: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:17:33.650792: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:17:33.964733: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:17:34.106072: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:17:34.864812: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-10-23 01:17:35.005136: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

Epoch 1: val_auc improved from None to 0.76995, saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras

Epoch 1: finished saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 109s 427ms/step - accuracy: 0.7067 - auc: 0.7803 - loss: 0.5709 - val_accuracy: 0.6750 - val_auc: 0.7700 - val_loss: 0.5888
Epoch 2/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7515 - auc: 0.8306 - loss: 0.5108
Epoch 2: val_auc improved from 0.76995 to 0.79750, saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras

Epoch 2: finished saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.7577 - auc: 0.8418 - loss: 0.4966 - val_accuracy: 0.7100 - val_auc: 0.7975 - val_loss: 0.5724
Epoch 3/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7544 - auc: 0.8433 - loss: 0.4909
Epoch 3: val_auc improved from 0.79750 to 0.81325, saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras

Epoch 3: finished saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.7716 - auc: 0.8559 - loss: 0.4750 - val_accuracy: 0.7350 - val_auc: 0.8133 - val_loss: 0.5509
Epoch 4/10
78/79 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7812 - auc: 0.8711 - loss: 0.4551
Epoch 4: val_auc improved from 0.81325 to 0.82025, saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras

Epoch 4: finished saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.7799 - auc: 0.8641 - loss: 0.4622 - val_accuracy: 0.7500 - val_auc: 0.8203 - val_loss: 0.5435
Epoch 5/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7946 - auc: 0.8872 - loss: 0.4283
Epoch 5: val_auc improved from 0.82025 to 0.83075, saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras

Epoch 5: finished saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.7846 - auc: 0.8733 - loss: 0.4477 - val_accuracy: 0.7650 - val_auc: 0.8307 - val_loss: 0.5248
Epoch 6/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7977 - auc: 0.8831 - loss: 0.4354
Epoch 6: val_auc improved from 0.83075 to 0.83745, saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras

Epoch 6: finished saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.7906 - auc: 0.8777 - loss: 0.4423 - val_accuracy: 0.7800 - val_auc: 0.8374 - val_loss: 0.5192
Epoch 7/10
78/79 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7988 - auc: 0.8887 - loss: 0.4256
Epoch 7: val_auc improved from 0.83745 to 0.84030, saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras

Epoch 7: finished saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.7993 - auc: 0.8819 - loss: 0.4352 - val_accuracy: 0.7800 - val_auc: 0.8403 - val_loss: 0.5215
Epoch 8/10
78/79 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8103 - auc: 0.8906 - loss: 0.4195
Epoch 8: val_auc improved from 0.84030 to 0.84180, saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras

Epoch 8: finished saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.7993 - auc: 0.8865 - loss: 0.4256 - val_accuracy: 0.8050 - val_auc: 0.8418 - val_loss: 0.5119
Epoch 9/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8080 - auc: 0.8999 - loss: 0.4080
Epoch 9: val_auc improved from 0.84180 to 0.84395, saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras

Epoch 9: finished saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.8005 - auc: 0.8898 - loss: 0.4220 - val_accuracy: 0.8250 - val_auc: 0.8440 - val_loss: 0.5087
Epoch 10/10
78/79 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8190 - auc: 0.8944 - loss: 0.4147
Epoch 10: val_auc improved from 0.84395 to 0.84705, saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras

Epoch 10: finished saving model to /kaggle/working/asd_care_results/efficientnetb0_best.keras
79/79 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.8116 - auc: 0.8940 - loss: 0.4135 - val_accuracy: 0.7900 - val_auc: 0.8471 - val_loss: 0.5104
Restoring model weights from the end of the best epoch: 10.

Training finished.
Best checkpoint exists: True
History saved: True
Training log saved: True

In [28]:

# Cell: Evaluate EfficientNetB0 on the held-out test set
import os
import json
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix
)

out = "/kaggle/working/asd_care_results"
base = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

test_df = pd.read_csv(os.path.join(base, "Dataset_csv", "test.csv"))
checkpoint = os.path.join(out, "efficientnetb0_best.keras")

assert os.path.isfile(checkpoint), "EfficientNetB0 checkpoint missing."

# Recreate test dataset with the same image processing
paths = test_df["image_path"].astype(str).to_numpy()
y_true = (
    test_df["Class"].astype(str).str.strip().str.upper() == "YES"
).astype(int).to_numpy()

def load_test_image(path, label):
    image = tf.io.read_file(path)
    image = tf.io.decode_image(image, channels=3, expand_animations=False)
    image.set_shape([None, None, 3])
    image = tf.image.resize(image, (224, 224))
    return tf.cast(image, tf.float32), label

test_ds = tf.data.Dataset.from_tensor_slices(
    (paths, y_true.astype(np.float32))
)
test_ds = test_ds.map(
    load_test_image, num_parallel_calls=tf.data.AUTOTUNE
).batch(32).prefetch(tf.data.AUTOTUNE)

# Load the saved best checkpoint; no training
model = tf.keras.models.load_model(checkpoint)
y_prob = model.predict(test_ds, verbose=1).reshape(-1)
y_pred = (y_prob >= 0.5).astype(int)

results = {
    "model": "EfficientNetB0 image-only",
    "test_samples": int(len(y_true)),
    "accuracy": float(accuracy_score(y_true, y_pred)),
    "precision": float(precision_score(y_true, y_pred, zero_division=0)),
    "recall": float(recall_score(y_true, y_pred, zero_division=0)),
    "f1": float(f1_score(y_true, y_pred, zero_division=0)),
    "roc_auc": float(roc_auc_score(y_true, y_prob)),
    "confusion_matrix": confusion_matrix(
        y_true, y_pred, labels=[0, 1]
    ).tolist(),
    "threshold": 0.5
}

with open(os.path.join(out, "efficientnetb0_test_results.json"), "w") as f:
    json.dump(results, f, indent=2)

np.savez_compressed(
    os.path.join(out, "efficientnetb0_test_predictions.npz"),
    y_true=y_true, y_prob=y_prob, y_pred=y_pred
)

print("\nTEST RESULTS")
print(json.dumps(results, indent=2))
print("\nSaved test metrics and predictions.")

WARNING:tensorflow:5 out of the last 15 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x79616811eac0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
7/7 ━━━━━━━━━━━━━━━━━━━━ 14s 1s/step

TEST RESULTS
{
  "model": "EfficientNetB0 image-only",
  "test_samples": 200,
  "accuracy": 0.815,
  "precision": 0.8888888888888888,
  "recall": 0.72,
  "f1": 0.7955801104972375,
  "roc_auc": 0.9347,
  "confusion_matrix": [
    [
      91,
      9
    ],
    [
      28,
      72
    ]
  ],
  "threshold": 0.5
}

Saved test metrics and predictions.

In [30]:

# Cell: Train ResNet50 — checkpointed, no duplicate training
import os
import json
import tensorflow as tf
import pandas as pd
import numpy as np

from tensorflow.keras import layers, Model
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, CSVLogger

SEED = 42
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
EPOCHS = 10

tf.keras.utils.set_random_seed(SEED)

out = "/kaggle/working/asd_care_results"
os.makedirs(out, exist_ok=True)

checkpoint = os.path.join(out, "resnet50_best.keras")
history_path = os.path.join(out, "resnet50_history.json")
log_path = os.path.join(out, "resnet50_training_log.csv")

if os.path.isfile(checkpoint):
    print("ResNet50 checkpoint already exists — skipping training.")
    print("Checkpoint:", checkpoint)
else:
    base = (
        "/kaggle/input/datasets/ajithdari/"
        "autism-spectrum-disorder-multi-modal-dataset"
    )
    csv_dir = os.path.join(base, "Dataset_csv")
    train_df = pd.read_csv(os.path.join(csv_dir, "train.csv"))
    valid_df = pd.read_csv(os.path.join(csv_dir, "valid.csv"))

    def make_dataset(df, training=False):
        paths = df["image_path"].astype(str).to_numpy()
        labels = (
            df["Class"].astype(str).str.strip().str.upper() == "YES"
        ).astype(np.float32).to_numpy()

        ds = tf.data.Dataset.from_tensor_slices((paths, labels))

        def load_image(path, label):
            image = tf.io.read_file(path)
            image = tf.io.decode_image(
                image, channels=3, expand_animations=False
            )
            image.set_shape([None, None, 3])
            image = tf.image.resize(image, IMG_SIZE)
            image = preprocess_input(tf.cast(image, tf.float32))
            return image, label

        ds = ds.map(load_image, num_parallel_calls=tf.data.AUTOTUNE)
        if training:
            ds = ds.shuffle(
                len(df), seed=SEED, reshuffle_each_iteration=True
            )
        return ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

    train_ds = make_dataset(train_df, training=True)
    valid_ds = make_dataset(valid_df)

    backbone = ResNet50(
        include_top=False,
        weights="imagenet",
        input_shape=(224, 224, 3)
    )
    backbone.trainable = False

    inputs = layers.Input(shape=(224, 224, 3))
    x = backbone(inputs, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(1, activation="sigmoid")(x)
    model = Model(inputs, outputs, name="ResNet50_ASD_image_only")

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=["accuracy", tf.keras.metrics.AUC(name="auc")]
    )

    callbacks = [
        ModelCheckpoint(
            checkpoint, monitor="val_auc", mode="max",
            save_best_only=True, verbose=1
        ),
        EarlyStopping(
            monitor="val_auc", mode="max",
            patience=3, restore_best_weights=True, verbose=1
        ),
        CSVLogger(log_path, append=False)
    ]

    print("Train rows:", len(train_df))
    print("Validation rows:", len(valid_df))
    print("GPUs:", tf.config.list_physical_devices("GPU"))
    print("Starting ResNet50 training...")

    hist = model.fit(
        train_ds,
        validation_data=valid_ds,
        epochs=EPOCHS,
        callbacks=callbacks,
        verbose=1
    )

    with open(history_path, "w") as f:
        json.dump(
            {k: [float(v) for v in values]
             for k, values in hist.history.items()},
            f, indent=2
        )

    print("\nTraining complete.")
    print("Checkpoint saved:", os.path.isfile(checkpoint))
    print("History saved:", os.path.isfile(history_path))
    print("Training log saved:", os.path.isfile(log_path))

ResNet50 checkpoint already exists — skipping training.
Checkpoint: /kaggle/working/asd_care_results/resnet50_best.keras

In [31]:

# Cell: Evaluate ResNet50 on held-out test data
import os
import json
import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow.keras.applications.resnet50 import preprocess_input
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix
)

out = "/kaggle/working/asd_care_results"
base = (
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)

test_df = pd.read_csv(os.path.join(base, "Dataset_csv", "test.csv"))
checkpoint = os.path.join(out, "resnet50_best.keras")
assert os.path.isfile(checkpoint), "ResNet50 checkpoint missing."

paths = test_df["image_path"].astype(str).to_numpy()
y_true = (
    test_df["Class"].astype(str).str.strip().str.upper() == "YES"
).astype(int).to_numpy()

def load_test_image(path, label):
    image = tf.io.read_file(path)
    image = tf.io.decode_image(image, channels=3, expand_animations=False)
    image.set_shape([None, None, 3])
    image = tf.image.resize(image, (224, 224))
    image = preprocess_input(tf.cast(image, tf.float32))
    return image, label

test_ds = tf.data.Dataset.from_tensor_slices(
    (paths, y_true.astype(np.float32))
)
test_ds = test_ds.map(
    load_test_image, num_parallel_calls=tf.data.AUTOTUNE
).batch(32).prefetch(tf.data.AUTOTUNE)

model = tf.keras.models.load_model(checkpoint)
y_prob = model.predict(test_ds, verbose=1).reshape(-1)
y_pred = (y_prob >= 0.5).astype(int)

results = {
    "model": "ResNet50 image-only",
    "test_samples": int(len(y_true)),
    "accuracy": float(accuracy_score(y_true, y_pred)),
    "precision": float(precision_score(y_true, y_pred, zero_division=0)),
    "recall": float(recall_score(y_true, y_pred, zero_division=0)),
    "f1": float(f1_score(y_true, y_pred, zero_division=0)),
    "roc_auc": float(roc_auc_score(y_true, y_prob)),
    "confusion_matrix": confusion_matrix(
        y_true, y_pred, labels=[0, 1]
    ).tolist(),
    "threshold": 0.5
}

with open(os.path.join(out, "resnet50_test_results.json"), "w") as f:
    json.dump(results, f, indent=2)

np.savez_compressed(
    os.path.join(out, "resnet50_test_predictions.npz"),
    y_true=y_true, y_prob=y_prob, y_pred=y_pred
)

print("\nTEST RESULTS")
print(json.dumps(results, indent=2))
print("\nSaved ResNet50 test metrics and predictions.")

WARNING:tensorflow:5 out of the last 15 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x79613977c900> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
7/7 ━━━━━━━━━━━━━━━━━━━━ 8s 670ms/step

TEST RESULTS
{
  "model": "ResNet50 image-only",
  "test_samples": 200,
  "accuracy": 0.89,
  "precision": 0.8979591836734694,
  "recall": 0.88,
  "f1": 0.8888888888888888,
  "roc_auc": 0.9509,
  "confusion_matrix": [
    [
      90,
      10
    ],
    [
      12,
      88
    ]
  ],
  "threshold": 0.5
}

Saved ResNet50 test metrics and predictions.

In [32]:

# Cell: Final Ablation Comparison + Recovery Backup
import os
import json
import zipfile
import pandas as pd

out = "/kaggle/working/asd_care_results"
os.makedirs(out, exist_ok=True)

models = {
    "MobileNetV2": "mobilenetv2_test_results.json",
    "Questionnaire MLP": "questionnaire_mlp_test_results.json",
    "EfficientNetB0": "efficientnetb0_test_results.json",
    "ResNet50": "resnet50_test_results.json",
}

rows = []
missing = []

for model_name, filename in models.items():
    path = os.path.join(out, filename)
    if not os.path.isfile(path):
        missing.append(filename)
        continue

    with open(path, "r") as f:
        result = json.load(f)

    rows.append({
        "model": model_name,
        "test_samples": result.get("test_samples"),
        "accuracy": result.get("accuracy"),
        "precision": result.get("precision"),
        "recall": result.get("recall"),
        "f1": result.get("f1"),
        "roc_auc": result.get("roc_auc"),
        "confusion_matrix": json.dumps(result.get("confusion_matrix"))
    })

if missing:
    print("Missing results:", missing)

comparison = pd.DataFrame(rows)

if not comparison.empty:
    comparison = comparison.sort_values("roc_auc", ascending=False)

    csv_path = os.path.join(out, "final_model_comparison.csv")
    json_path = os.path.join(out, "final_model_comparison.json")

    comparison.to_csv(csv_path, index=False)
    comparison.to_json(json_path, orient="records", indent=2)

    print("=== MODEL COMPARISON ===")
    display(comparison)

    print("\nSaved:", csv_path)
    print("Saved:", json_path)

# Record research limitations alongside the results
notes = {
    "purpose": "Experimental ASD image-only and questionnaire-only model comparison",
    "test_split_size": 200,
    "decision_threshold": 0.5,
    "important_limitations": [
        "Results are from one held-out split and do not establish generalization.",
        "Questionnaire performance is unusually high and warrants leakage and provenance checks.",
        "Participant-level correspondence between facial images and questionnaire records has not been established.",
        "Do not describe the prototype as clinically validated.",
        "The questionnaire-only model is not a multimodal fusion model."
    ]
}
with open(os.path.join(out, "research_limitations.json"), "w") as f:
    json.dump(notes, f, indent=2)

# Package all experiment artifacts into one recovery ZIP
archive = "/kaggle/working/asd_care_final_backup.zip"
with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as z:
    for root, _, files in os.walk(out):
        for name in files:
            path = os.path.join(root, name)
            z.write(path, os.path.relpath(path, "/kaggle/working"))

print("\nBackup ZIP:", archive)
print("Backup size (MB):", round(os.path.getsize(archive) / (1024 * 1024), 2))
print("Files packaged:", len(zipfile.ZipFile(archive).namelist()))
print("\nIMPORTANT: Download this ZIP to your computer.")

=== MODEL COMPARISON ===

,model,test_samples,accuracy,precision,recall,f1,roc_auc,confusion_matrix
1,Questionnaire MLP,200,0.985,0.970874,1.00,0.985222,0.9998,"[[97, 3], [0, 100]]"
3,ResNet50,200,0.890,0.897959,0.88,0.888889,0.9509,"[[90, 10], [12, 88]]"
2,EfficientNetB0,200,0.815,0.888889,0.72,0.795580,0.9347,"[[91, 9], [28, 72]]"
0,MobileNetV2,200,0.850,0.857143,0.84,0.848485,0.9307,"[[86, 14], [16, 84]]"

Saved: /kaggle/working/asd_care_results/final_model_comparison.csv
Saved: /kaggle/working/asd_care_results/final_model_comparison.json

Backup ZIP: /kaggle/working/asd_care_final_backup.zip
Backup size (MB): 107.72
Files packaged: 25

IMPORTANT: Download this ZIP to your computer.

In [17]:

# Cell: Audit Image + Questionnaire Pairing
import os
import pandas as pd

DATA_DIR = "/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_csv"
FILES = {
    "train": os.path.join(DATA_DIR, "train.csv"),
    "valid": os.path.join(DATA_DIR, "valid.csv"),
    "test":  os.path.join(DATA_DIR, "test.csv"),
}

dfs = {}
for split, path in FILES.items():
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing {split} CSV: {path}")
    dfs[split] = pd.read_csv(path)

features = [
    c for c in dfs["train"].columns
    if c not in ["image_path", "Class"]
]

print("=== 1. DATASET STRUCTURE ===")
for split, df in dfs.items():
    print(f"\n{split.upper()}: {df.shape}")
    print("Columns:", df.columns.tolist())
    print("Class counts:")
    print(df["Class"].value_counts(dropna=False).to_dict())
    print("Missing values:", int(df.isna().sum().sum()))
    print("Missing image paths:", int((~df["image_path"].astype(str).map(os.path.exists)).sum()))

print("\n=== 2. IMAGE PATH OVERLAP ACROSS SPLITS ===")
for a, b in [("train", "valid"), ("train", "test"), ("valid", "test")]:
    paths_a = set(dfs[a]["image_path"].astype(str).str.strip())
    paths_b = set(dfs[b]["image_path"].astype(str).str.strip())
    print(f"{a} vs {b}: {len(paths_a & paths_b)} shared paths")

print("\n=== 3. DUPLICATE IMAGE PATHS WITHIN EACH SPLIT ===")
for split, df in dfs.items():
    print(f"{split}: {int(df['image_path'].astype(str).duplicated().sum())}")

print("\n=== 4. QUESTIONNAIRE PATTERN AUDIT ===")
for split, df in dfs.items():
    available = [c for c in features if c in df.columns]
    pattern_counts = df[available].astype(str).value_counts()
    print(
        f"{split}: {len(pattern_counts)} unique questionnaire patterns "
        f"out of {len(df)} rows; repeated-pattern rows = "
        f"{int(df[available].astype(str).duplicated(keep=False).sum())}"
    )

print("\n=== 5. IDENTICAL QUESTIONNAIRE PATTERNS ACROSS SPLITS ===")
pattern_sets = {}
for split, df in dfs.items():
    available = [c for c in features if c in df.columns]
    pattern_sets[split] = set(
        map(tuple, df[available].fillna("<MISSING>").astype(str).to_numpy())
    )

for a, b in [("train", "valid"), ("train", "test"), ("valid", "test")]:
    shared = pattern_sets[a] & pattern_sets[b]
    print(f"{a} vs {b}: {len(shared)} shared questionnaire patterns")

print("\n=== 6. IMAGE / QUESTIONNAIRE / LABEL ROW CHECK ===")
for split, df in dfs.items():
    print(f"\n{split.upper()} first 5 rows:")
    display(df[["image_path"] + features + ["Class"]].head())

print("\nAUDIT COMPLETE.")
print("Important: matching rows in a CSV shows dataset-level association,")
print("but does not independently prove participant identity or clinical pairing.")

=== 1. DATASET STRUCTURE ===

TRAIN: (2526, 16)
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']
Class counts:
{'YES': 1263, 'NO': 1263}
Missing values: 0
Missing image paths: 0

VALID: (200, 16)
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']
Class counts:
{'YES': 100, 'NO': 100}
Missing values: 0
Missing image paths: 0

TEST: (200, 16)
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']
Class counts:
{'YES': 100, 'NO': 100}
Missing values: 0
Missing image paths: 0

=== 2. IMAGE PATH OVERLAP ACROSS SPLITS ===
train vs valid: 0 shared paths
train vs test: 0 shared paths
valid vs test: 0 shared paths

=== 3. DUPLICATE IMAGE PATHS WITHIN EACH SPLIT ===
train: 0
valid: 0
test: 0

=== 4. QUESTIONNAIRE PATTERN AUDIT ===
train: 2313 unique questionnaire patterns out of 2526 rows; repeated-pattern rows = 374
valid: 200 unique questionnaire patterns out of 200 rows; repeated-pattern rows = 0
test: 200 unique questionnaire patterns out of 200 rows; repeated-pattern rows = 0

=== 5. IDENTICAL QUESTIONNAIRE PATTERNS ACROSS SPLITS ===
train vs valid: 200 shared questionnaire patterns
train vs test: 200 shared questionnaire patterns
valid vs test: 200 shared questionnaire patterns

=== 6. IMAGE / QUESTIONNAIRE / LABEL ROW CHECK ===

TRAIN first 5 rows:

,image_path,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,Age,Sex,Jauundice,Family_ASD,Class
0,/kaggle/input/datasets/prayashdas/autistic-chi...,1,0,1,1,1,1,0,1,0,1,4,m,no,no,YES
1,/kaggle/input/datasets/prayashdas/autistic-chi...,1,1,0,1,1,1,1,1,1,1,16,m,no,no,YES
2,/kaggle/input/datasets/prayashdas/autistic-chi...,1,1,1,1,1,1,1,1,1,1,41,f,yes,yes,YES
3,/kaggle/input/datasets/prayashdas/autistic-chi...,0,1,1,1,1,1,0,1,1,1,33,m,no,yes,YES
4,/kaggle/input/datasets/prayashdas/autistic-chi...,1,1,1,1,1,1,1,1,1,1,22,m,yes,no,YES

VALID first 5 rows:

,image_path,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,Age,Sex,Jauundice,Family_ASD,Class
0,/kaggle/input/datasets/prayashdas/autistic-chi...,1,0,1,1,1,1,0,1,0,1,4,m,no,no,YES
1,/kaggle/input/datasets/prayashdas/autistic-chi...,1,1,0,1,1,1,1,1,1,1,16,m,no,no,YES
2,/kaggle/input/datasets/prayashdas/autistic-chi...,1,1,1,1,1,1,1,1,1,1,41,f,yes,yes,YES
3,/kaggle/input/datasets/prayashdas/autistic-chi...,0,1,1,1,1,1,0,1,1,1,33,m,no,yes,YES
4,/kaggle/input/datasets/prayashdas/autistic-chi...,1,1,1,1,1,1,1,1,1,1,22,m,yes,no,YES

TEST first 5 rows:

,image_path,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,Age,Sex,Jauundice,Family_ASD,Class
0,/kaggle/input/datasets/prayashdas/autistic-chi...,1,0,1,1,1,1,0,1,0,1,4,m,no,no,YES
1,/kaggle/input/datasets/prayashdas/autistic-chi...,1,1,0,1,1,1,1,1,1,1,16,m,no,no,YES
2,/kaggle/input/datasets/prayashdas/autistic-chi...,1,1,1,1,1,1,1,1,1,1,41,f,yes,yes,YES
3,/kaggle/input/datasets/prayashdas/autistic-chi...,0,1,1,1,1,1,0,1,1,1,33,m,no,yes,YES
4,/kaggle/input/datasets/prayashdas/autistic-chi...,1,1,1,1,1,1,1,1,1,1,22,m,yes,no,YES

AUDIT COMPLETE.
Important: matching rows in a CSV shows dataset-level association,
but does not independently prove participant identity or clinical pairing.

In [18]:

# Cell: Create a clickable download link inside Kaggle
import os
from IPython.display import FileLink, display

path = "/kaggle/working/asd_care_final_backup_v2.zip"

if not os.path.isfile(path):
    path = "/kaggle/working/asd_care_final_backup.zip"

if os.path.isfile(path):
    print("Backup found:", path)
    print("Size:", round(os.path.getsize(path) / (1024 * 1024), 2), "MB")
    display(FileLink(path))
else:
    print("ZIP not found. Files currently in /kaggle/working:")
    print(os.listdir("/kaggle/working"))

Backup found: /kaggle/working/asd_care_final_backup.zip
Size: 107.72 MB

/kaggle/working/asd_care_final_backup.zip

In [19]:

# Cell: Split FYP Backup into Downloadable ZIP Batches
import os
import json
import zipfile

SOURCE_DIR = "/kaggle/working/asd_care_results"
BATCH_DIR = "/kaggle/working/asd_care_download_batches"
MAX_BATCH_MB = 20
MAX_BATCH_BYTES = MAX_BATCH_MB * 1024 * 1024

if not os.path.isdir(SOURCE_DIR):
    raise FileNotFoundError(
        f"Results folder missing: {SOURCE_DIR}\n"
        "Run: print(os.listdir('/kaggle/working'))"
    )

os.makedirs(BATCH_DIR, exist_ok=True)

# Collect existing files
files = []
for root, _, names in os.walk(SOURCE_DIR):
    for name in names:
        path = os.path.join(root, name)
        rel = os.path.relpath(path, SOURCE_DIR)
        files.append((path, rel, os.path.getsize(path)))

if not files:
    raise RuntimeError("No saved result files found to package.")

# Group files by uncompressed size. Large individual files get their own batch.
batches = []
current = []
current_size = 0

for item in sorted(files, key=lambda x: x[2], reverse=True):
    path, rel, size = item

    if current and current_size + size > MAX_BATCH_BYTES:
        batches.append(current)
        current = []
        current_size = 0

    current.append(item)
    current_size += size

if current:
    batches.append(current)

manifest = []

for i, batch in enumerate(batches, start=1):
    zip_path = os.path.join(BATCH_DIR, f"asd_fyp_batch_{i:02d}.zip")

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for path, rel, _ in batch:
            z.write(path, arcname=rel)

    with zipfile.ZipFile(zip_path, "r") as z:
        bad = z.testzip()
        if bad is not None:
            raise RuntimeError(f"ZIP integrity check failed: {zip_path}, {bad}")

    info = {
        "batch": i,
        "filename": os.path.basename(zip_path),
        "zip_path": zip_path,
        "size_mb": round(os.path.getsize(zip_path) / (1024 * 1024), 2),
        "files": [rel for _, rel, _ in batch],
    }
    manifest.append(info)
    print(
        f"Batch {i:02d}: {info['filename']} | "
        f"{info['size_mb']} MB | {len(batch)} files"
    )

manifest_path = os.path.join(BATCH_DIR, "download_manifest.json")
with open(manifest_path, "w") as f:
    json.dump(manifest, f, indent=2)

print("\nTotal source files:", len(files))
print("Total batches:", len(batches))
print("Batch folder:", BATCH_DIR)
print("\nNext: run the download cell below.")

Batch 01: asd_fyp_batch_01.zip | 83.51 MB | 1 files
Batch 02: asd_fyp_batch_02.zip | 14.36 MB | 1 files
Batch 03: asd_fyp_batch_03.zip | 9.85 MB | 23 files

Total source files: 25
Total batches: 3
Batch folder: /kaggle/working/asd_care_download_batches

Next: run the download cell below.

In [20]:

# Cell: Display Download Links for Every Batch
import os
from IPython.display import display, FileLink

folder = "/kaggle/working/asd_care_download_batches"

for name in sorted(os.listdir(folder)):
    if name.endswith(".zip"):
        path = os.path.join(folder, name)
        print(f"{name} ({os.path.getsize(path)/(1024*1024):.2f} MB)")
        display(FileLink(path))

asd_fyp_batch_01.zip (83.51 MB)

/kaggle/working/asd_care_download_batches/asd_fyp_batch_01.zip

asd_fyp_batch_02.zip (14.36 MB)

/kaggle/working/asd_care_download_batches/asd_fyp_batch_02.zip

asd_fyp_batch_03.zip (9.85 MB)

/kaggle/working/asd_care_download_batches/asd_fyp_batch_03.zip

In [21]:

# Cell: Locate All Existing FYP Backups
import os

root = "/kaggle/working"

print("=== WORKING DIRECTORY ===")
for name in sorted(os.listdir(root)):
    path = os.path.join(root, name)
    if os.path.isfile(path):
        print(f"FILE   {name}  |  {os.path.getsize(path)/(1024*1024):.2f} MB")
    elif os.path.isdir(path):
        print(f"FOLDER {name}/")

print("\n=== FYP RESULT FILES ===")
results = os.path.join(root, "asd_care_results")
if os.path.isdir(results):
    for current, _, names in os.walk(results):
        for name in sorted(names):
            path = os.path.join(current, name)
            print(
                os.path.relpath(path, root),
                f"| {os.path.getsize(path)/(1024*1024):.2f} MB"
            )
else:
    print("asd_care_results folder not found.")

print("\n=== DOWNLOAD BATCHES ===")
batches = os.path.join(root, "asd_care_download_batches")
if os.path.isdir(batches):
    for name in sorted(os.listdir(batches)):
        path = os.path.join(batches, name)
        if os.path.isfile(path):
            print(name, f"| {os.path.getsize(path)/(1024*1024):.2f} MB")
else:
    print("Batch folder not found.")

=== WORKING DIRECTORY ===
FOLDER .virtual_documents/
FOLDER asd_care_download_batches/
FILE   asd_care_final_backup.zip  |  107.72 MB
FILE   asd_care_recovery.zip  |  9.85 MB
FOLDER asd_care_results/

=== FYP RESULT FILES ===
asd_care_results/efficientnetb0_best.keras | 16.27 MB
asd_care_results/efficientnetb0_history.json | 0.00 MB
asd_care_results/efficientnetb0_test_predictions.npz | 0.00 MB
asd_care_results/efficientnetb0_test_results.json | 0.00 MB
asd_care_results/efficientnetb0_training_log.csv | 0.00 MB
asd_care_results/final_model_comparison.csv | 0.00 MB
asd_care_results/final_model_comparison.json | 0.00 MB
asd_care_results/mobilenetv2_best.keras | 11.06 MB
asd_care_results/mobilenetv2_history.json | 0.00 MB
asd_care_results/mobilenetv2_test_predictions.npz | 0.00 MB
asd_care_results/mobilenetv2_test_results.json | 0.00 MB
asd_care_results/mobilenetv2_training_log.csv | 0.00 MB
asd_care_results/questionnaire_mlp_best.keras | 0.04 MB
asd_care_results/questionnaire_mlp_history.json | 0.01 MB
asd_care_results/questionnaire_mlp_test_predictions.npz | 0.00 MB
asd_care_results/questionnaire_mlp_test_results.json | 0.00 MB
asd_care_results/questionnaire_mlp_training_log.csv | 0.01 MB
asd_care_results/questionnaire_preprocessing.json | 0.00 MB
asd_care_results/questionnaire_scaler.json | 0.00 MB
asd_care_results/research_limitations.json | 0.00 MB
asd_care_results/resnet50_best.keras | 90.63 MB
asd_care_results/resnet50_history.json | 0.00 MB
asd_care_results/resnet50_test_predictions.npz | 0.00 MB
asd_care_results/resnet50_test_results.json | 0.00 MB
asd_care_results/resnet50_training_log.csv | 0.00 MB

=== DOWNLOAD BATCHES ===
asd_fyp_batch_01.zip | 83.51 MB
asd_fyp_batch_02.zip | 14.36 MB
asd_fyp_batch_03.zip | 9.85 MB
download_manifest.json | 0.00 MB

In [58]:
from pathlib import Path

for folder in [
    Path("/kaggle/working"),
    Path("/kaggle/working/asd_care_results"),
    Path("/kaggle/working/asd_care_download_batches"),
]:
    print(f"\n--- {folder} ---")
    if folder.exists():
        for item in sorted(folder.iterdir()):
            if item.is_file():
                print(f"{item.name} | {item.stat().st_size / (1024**2):.2f} MB")
            else:
                print(f"{item.name}/")
    else:
        print("Folder does not exist")

--- /kaggle/working ---
.virtual_documents/
asd_care_final_backup.zip | 107.72 MB
asd_care_metrics_only.zip | 0.01 MB
asd_care_recovery.zip | 9.85 MB
asd_care_results/
asd_transfer_parts/
github_backup_parts/

--- /kaggle/working/asd_care_results ---
efficientnetb0_best.keras | 16.27 MB
efficientnetb0_history.json | 0.00 MB
efficientnetb0_test_predictions.npz | 0.00 MB
efficientnetb0_test_results.json | 0.00 MB
efficientnetb0_training_log.csv | 0.00 MB
final_model_comparison.csv | 0.00 MB
final_model_comparison.json | 0.00 MB
mobilenetv2_best.keras | 11.06 MB
mobilenetv2_history.json | 0.00 MB
mobilenetv2_test_predictions.npz | 0.00 MB
mobilenetv2_test_results.json | 0.00 MB
mobilenetv2_training_log.csv | 0.00 MB
questionnaire_mlp_best.keras | 0.04 MB
questionnaire_mlp_history.json | 0.01 MB
questionnaire_mlp_test_predictions.npz | 0.00 MB
questionnaire_mlp_test_results.json | 0.00 MB
questionnaire_mlp_training_log.csv | 0.01 MB
questionnaire_preprocessing.json | 0.00 MB
questionnaire_scaler.json | 0.00 MB
research_limitations.json | 0.00 MB
resnet50_best.keras | 90.63 MB
resnet50_history.json | 0.00 MB
resnet50_test_predictions.npz | 0.00 MB
resnet50_test_results.json | 0.00 MB
resnet50_training_log.csv | 0.00 MB

--- /kaggle/working/asd_care_download_batches ---
Folder does not exist

In [60]:

# Cell 2 — Inspect backup contents
from pathlib import Path

backup = Path("/kaggle/input/datasets/shahbaz18/backup")

print("=== ALL BACKUP FILES ===")
for p in sorted(backup.rglob("*")):
    if p.is_file():
        print(f"{p.relative_to(backup)}  |  {p.stat().st_size / 1024:.1f} KB")

print("\n=== RESULT / PREDICTION FILES ===")
keywords = ("result", "predict", "history", "metric", "comparison",
            "test", "label", "scaler", "preprocess", "class")

for p in sorted(backup.rglob("*")):
    if p.is_file() and any(k in p.name.lower() for k in keywords):
        print(p)

=== ALL BACKUP FILES ===
asd_care_results/efficientnetb0_best.keras  |  16660.3 KB
asd_care_results/efficientnetb0_history.json  |  1.5 KB
asd_care_results/efficientnetb0_test_predictions.npz  |  1.4 KB
asd_care_results/efficientnetb0_test_results.json  |  0.3 KB
asd_care_results/efficientnetb0_training_log.csv  |  1.2 KB
asd_care_results/final_model_comparison.csv  |  0.4 KB
asd_care_results/final_model_comparison.json  |  0.9 KB
asd_care_results/mobilenetv2_best.keras  |  11326.2 KB
asd_care_results/mobilenetv2_history.json  |  2.1 KB
asd_care_results/mobilenetv2_test_predictions.npz  |  1.4 KB
asd_care_results/mobilenetv2_test_results.json  |  0.3 KB
asd_care_results/mobilenetv2_training_log.csv  |  1.6 KB
asd_care_results/questionnaire_mlp_best.keras  |  42.9 KB
asd_care_results/questionnaire_mlp_history.json  |  10.6 KB
asd_care_results/questionnaire_mlp_test_predictions.npz  |  1.3 KB
asd_care_results/questionnaire_mlp_test_results.json  |  0.4 KB
asd_care_results/questionnaire_mlp_training_log.csv  |  8.4 KB
asd_care_results/questionnaire_preprocessing.json  |  1.2 KB
asd_care_results/questionnaire_scaler.json  |  1.0 KB
asd_care_results/research_limitations.json  |  0.6 KB
asd_care_results/resnet50_best.keras  |  92807.3 KB
asd_care_results/resnet50_history.json  |  1.5 KB
asd_care_results/resnet50_test_predictions.npz  |  1.4 KB
asd_care_results/resnet50_test_results.json  |  0.3 KB
asd_care_results/resnet50_training_log.csv  |  1.2 KB

=== RESULT / PREDICTION FILES ===
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/efficientnetb0_history.json
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/efficientnetb0_test_predictions.npz
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/efficientnetb0_test_results.json
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/final_model_comparison.csv
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/final_model_comparison.json
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/mobilenetv2_history.json
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/mobilenetv2_test_predictions.npz
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/mobilenetv2_test_results.json
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/questionnaire_mlp_history.json
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/questionnaire_mlp_test_predictions.npz
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/questionnaire_mlp_test_results.json
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/questionnaire_preprocessing.json
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/questionnaire_scaler.json
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/resnet50_history.json
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/resnet50_test_predictions.npz
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/resnet50_test_results.json

In [61]:

# Cell 3 — Audit saved metrics, predictions, and comparison
from pathlib import Path
import json
import numpy as np

results_dir = Path(
    "/kaggle/input/datasets/shahbaz18/backup/asd_care_results"
)

for name in [
    "mobilenetv2_test_results.json",
    "efficientnetb0_test_results.json",
    "resnet50_test_results.json",
    "questionnaire_mlp_test_results.json",
    "final_model_comparison.json",
    "research_limitations.json",
]:
    path = results_dir / name
    print(f"\n{'=' * 15} {name} {'=' * 15}")
    if path.exists():
        try:
            print(json.dumps(json.loads(path.read_text()), indent=2))
        except Exception as e:
            print("Could not read JSON:", e)
    else:
        print("NOT FOUND")

print("\n========== PREDICTION ARRAYS ==========")
for path in sorted(results_dir.glob("*_test_predictions.npz")):
    print(f"\n{path.name}")
    with np.load(path, allow_pickle=False) as data:
        for key in data.files:
            arr = data[key]
            print(f"  {key}: shape={arr.shape}, dtype={arr.dtype}")
            if arr.size <= 12:
                print("   values:", arr.tolist())

print("\nAudit complete. No models were trained or modified.")

=============== mobilenetv2_test_results.json ===============
{
  "model": "MobileNetV2 image-only",
  "test_samples": 200,
  "accuracy": 0.85,
  "precision": 0.8571428571428571,
  "recall": 0.84,
  "f1": 0.8484848484848485,
  "roc_auc": 0.9307,
  "confusion_matrix": [
    [
      86,
      14
    ],
    [
      16,
      84
    ]
  ]
}

=============== efficientnetb0_test_results.json ===============
{
  "model": "EfficientNetB0 image-only",
  "test_samples": 200,
  "accuracy": 0.815,
  "precision": 0.8888888888888888,
  "recall": 0.72,
  "f1": 0.7955801104972375,
  "roc_auc": 0.9347,
  "confusion_matrix": [
    [
      91,
      9
    ],
    [
      28,
      72
    ]
  ],
  "threshold": 0.5
}

=============== resnet50_test_results.json ===============
{
  "model": "ResNet50 image-only",
  "test_samples": 200,
  "accuracy": 0.89,
  "precision": 0.8979591836734694,
  "recall": 0.88,
  "f1": 0.8888888888888888,
  "roc_auc": 0.9509,
  "confusion_matrix": [
    [
      90,
      10
    ],
    [
      12,
      88
    ]
  ],
  "threshold": 0.5
}

=============== questionnaire_mlp_test_results.json ===============
{
  "model": "Questionnaire-only MLP",
  "test_samples": 200,
  "accuracy": 0.985,
  "precision": 0.970873786407767,
  "recall": 1.0,
  "f1": 0.9852216748768473,
  "roc_auc": 0.9998,
  "confusion_matrix": [
    [
      97,
      3
    ],
    [
      0,
      100
    ]
  ],
  "threshold": 0.5,
  "note": "Re-evaluated from saved checkpoint and reconstructed preprocessing."
}

=============== final_model_comparison.json ===============
[
  {
    "model": "Questionnaire MLP",
    "test_samples": 200,
    "accuracy": 0.985,
    "precision": 0.9708737864,
    "recall": 1.0,
    "f1": 0.9852216749,
    "roc_auc": 0.9998,
    "confusion_matrix": "[[97, 3], [0, 100]]"
  },
  {
    "model": "ResNet50",
    "test_samples": 200,
    "accuracy": 0.89,
    "precision": 0.8979591837,
    "recall": 0.88,
    "f1": 0.8888888889,
    "roc_auc": 0.9509,
    "confusion_matrix": "[[90, 10], [12, 88]]"
  },
  {
    "model": "EfficientNetB0",
    "test_samples": 200,
    "accuracy": 0.815,
    "precision": 0.8888888889,
    "recall": 0.72,
    "f1": 0.7955801105,
    "roc_auc": 0.9347,
    "confusion_matrix": "[[91, 9], [28, 72]]"
  },
  {
    "model": "MobileNetV2",
    "test_samples": 200,
    "accuracy": 0.85,
    "precision": 0.8571428571,
    "recall": 0.84,
    "f1": 0.8484848485,
    "roc_auc": 0.9307,
    "confusion_matrix": "[[86, 14], [16, 84]]"
  }
]

=============== research_limitations.json ===============
{
  "purpose": "Experimental ASD image-only and questionnaire-only model comparison",
  "test_split_size": 200,
  "decision_threshold": 0.5,
  "important_limitations": [
    "Results are from one held-out split and do not establish generalization.",
    "Questionnaire performance is unusually high and warrants leakage and provenance checks.",
    "Participant-level correspondence between facial images and questionnaire records has not been established.",
    "Do not describe the prototype as clinically validated.",
    "The questionnaire-only model is not a multimodal fusion model."
  ]
}

========== PREDICTION ARRAYS ==========

efficientnetb0_test_predictions.npz
  y_true: shape=(200,), dtype=int64
  y_prob: shape=(200,), dtype=float32
  y_pred: shape=(200,), dtype=int64

mobilenetv2_test_predictions.npz
  y_true: shape=(200,), dtype=int64
  y_prob: shape=(200,), dtype=float32
  y_pred: shape=(200,), dtype=int64

questionnaire_mlp_test_predictions.npz
  y_true: shape=(200,), dtype=int64
  y_prob: shape=(200,), dtype=float32
  y_pred: shape=(200,), dtype=int64

resnet50_test_predictions.npz
  y_true: shape=(200,), dtype=int64
  y_prob: shape=(200,), dtype=float32
  y_pred: shape=(200,), dtype=int64

Audit complete. No models were trained or modified.

In [62]:

# Cell 4 — Verify saved predictions and recompute metrics
from pathlib import Path
import numpy as np
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix
)

results_dir = Path(
    "/kaggle/input/datasets/shahbaz18/backup/asd_care_results"
)

models = [
    "mobilenetv2",
    "efficientnetb0",
    "resnet50",
    "questionnaire_mlp",
]

saved_labels = {}

for model in models:
    path = results_dir / f"{model}_test_predictions.npz"

    with np.load(path, allow_pickle=False) as data:
        y_true = data["y_true"].astype(int)
        y_prob = data["y_prob"].astype(float).ravel()
        y_pred = data["y_pred"].astype(int).ravel()

    saved_labels[model] = y_true

    # Check stored predictions against the 0.5 threshold
    threshold_check = np.array_equal(y_pred, (y_prob >= 0.5).astype(int))

    print(f"\n=== {model.upper()} ===")
    print("Samples:", len(y_true))
    print("Positive labels:", int(y_true.sum()))
    print("Probability range:", (float(y_prob.min()), float(y_prob.max())))
    print("Stored predictions match threshold 0.5:", threshold_check)
    print("Accuracy:", round(accuracy_score(y_true, y_pred), 4))
    print("Precision:", round(precision_score(y_true, y_pred, zero_division=0), 4))
    print("Recall:", round(recall_score(y_true, y_pred, zero_division=0), 4))
    print("F1:", round(f1_score(y_true, y_pred, zero_division=0), 4))
    print("ROC-AUC:", round(roc_auc_score(y_true, y_prob), 4))
    print("Confusion matrix:\n", confusion_matrix(y_true, y_pred))

print("\n=== TEST LABEL CONSISTENCY ===")
reference = saved_labels[models[0]]

for model in models[1:]:
    same = np.array_equal(reference, saved_labels[model])
    print(f"{model}: same test labels as MobileNetV2 = {same}")

print("\nAudit finished. No model training performed.")

=== MOBILENETV2 ===
Samples: 200
Positive labels: 100
Probability range: (0.0034293627832084894, 0.9967033267021179)
Stored predictions match threshold 0.5: True
Accuracy: 0.85
Precision: 0.8571
Recall: 0.84
F1: 0.8485
ROC-AUC: 0.9307
Confusion matrix:
 [[86 14]
 [16 84]]

=== EFFICIENTNETB0 ===
Samples: 200
Positive labels: 100
Probability range: (0.005501154810190201, 0.9884946942329407)
Stored predictions match threshold 0.5: True
Accuracy: 0.815
Precision: 0.8889
Recall: 0.72
F1: 0.7956
ROC-AUC: 0.9347
Confusion matrix:
 [[91  9]
 [28 72]]

=== RESNET50 ===
Samples: 200
Positive labels: 100
Probability range: (0.010782212018966675, 0.9998396635055542)
Stored predictions match threshold 0.5: True
Accuracy: 0.89
Precision: 0.898
Recall: 0.88
F1: 0.8889
ROC-AUC: 0.9509
Confusion matrix:
 [[90 10]
 [12 88]]

=== QUESTIONNAIRE_MLP ===
Samples: 200
Positive labels: 100
Probability range: (0.0, 1.0)
Stored predictions match threshold 0.5: True
Accuracy: 0.985
Precision: 0.9709
Recall: 1.0
F1: 0.9852
ROC-AUC: 0.9998
Confusion matrix:
 [[ 97   3]
 [  0 100]]

=== TEST LABEL CONSISTENCY ===
efficientnetb0: same test labels as MobileNetV2 = True
resnet50: same test labels as MobileNetV2 = True
questionnaire_mlp: same test labels as MobileNetV2 = True

Audit finished. No model training performed.

In [63]:

# Cell 5 — Audit questionnaire preprocessing and data provenance
from pathlib import Path
import json

backup = Path("/kaggle/input/datasets/shahbaz18/backup/asd_care_results")

for filename in [
    "questionnaire_preprocessing.json",
    "questionnaire_scaler.json",
    "questionnaire_mlp_history.json",
]:
    path = backup / filename
    print(f"\n{'=' * 12} {filename} {'=' * 12}")

    if path.exists():
        try:
            obj = json.loads(path.read_text())
            print(json.dumps(obj, indent=2)[:12000])
        except Exception as e:
            print("Read error:", e)
    else:
        print("File not found")

print("\n========== CSV FILES IN ATTACHED DATASETS ==========")
root = Path("/kaggle/input/datasets")
csv_files = list(root.rglob("*.csv"))

if not csv_files:
    print("No CSV files found in attached datasets.")
else:
    for p in csv_files[:100]:
        print(p)

print(f"\nCSV files found: {len(csv_files)}")
print("\nAudit only — no training or file changes.")

============ questionnaire_preprocessing.json ============
{
  "numeric_features": [
    "A1",
    "A2",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "A9",
    "A10",
    "Age"
  ],
  "categorical_features": [
    "Sex",
    "Jauundice",
    "Family_ASD"
  ],
  "category_levels": {
    "Sex": [
      "f",
      "m"
    ],
    "Jauundice": [
      "no",
      "yes"
    ],
    "Family_ASD": [
      "no",
      "yes"
    ]
  },
  "numeric_medians": {
    "A1": 1.0,
    "A2": 1.0,
    "A3": 1.0,
    "A4": 1.0,
    "A5": 1.0,
    "A6": 1.0,
    "A7": 1.0,
    "A8": 1.0,
    "A9": 1.0,
    "A10": 1.0,
    "Age": 19.0
  },
  "scaler_mean": [
    0.7450514647664291,
    0.5324623911322248,
    0.6417260490894695,
    0.6441013460015835,
    0.6528107680126682,
    0.5566112430720507,
    0.5629453681710214,
    0.6084718923198733,
    0.5344418052256532,
    0.6809184481393508,
    20.507917656373714
  ],
  "scaler_scale": [
    0.435832283815492,
    0.49894508030641854,
    0.47949319808469576,
    0.47878471370808395,
    0.4760765371023639,
    0.49678482983867095,
    0.4960220565920578,
    0.48809204928634703,
    0.49881235154394304,
    0.46612070874704664,
    14.777089294960096
  ],
  "encoded_feature_count": 17
}

============ questionnaire_scaler.json ============
{
  "features": [
    "A1",
    "A2",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "A9",
    "A10",
    "Age",
    "Sex",
    "Jauundice",
    "Family_ASD"
  ],
  "mean": [
    0.7450514647664291,
    0.5324623911322248,
    0.6417260490894695,
    0.6441013460015835,
    0.6528107680126682,
    0.5566112430720507,
    0.5629453681710214,
    0.6084718923198733,
    0.5344418052256532,
    0.6809184481393508,
    20.507917656373714,
    NaN,
    NaN,
    NaN
  ],
  "scale": [
    0.435832283815492,
    0.49894508030641854,
    0.47949319808469576,
    0.47878471370808395,
    0.4760765371023639,
    0.49678482983867095,
    0.4960220565920578,
    0.48809204928634703,
    0.49881235154394304,
    0.46612070874704664,
    14.777089294960096,
    NaN,
    NaN,
    NaN
  ],
  "imputation_medians": {
    "A1": 1.0,
    "A2": 1.0,
    "A3": 1.0,
    "A4": 1.0,
    "A5": 1.0,
    "A6": 1.0,
    "A7": 1.0,
    "A8": 1.0,
    "A9": 1.0,
    "A10": 1.0,
    "Age": 19.0,
    "Sex": NaN,
    "Jauundice": NaN,
    "Family_ASD": NaN
  }
}

============ questionnaire_mlp_history.json ============
{
  "accuracy": [
    0.7545526623725891,
    0.8760886788368225,
    0.9069675207138062,
    0.9081552028656006,
    0.925574004650116,
    0.9303246140480042,
    0.9334917068481445,
    0.9398258328437805,
    0.9382422566413879,
    0.940617561340332,
    0.9481393694877625,
    0.9509105086326599,
    0.948931097984314,
    0.946951687335968,
    0.9560570120811462,
    0.9572446346282959,
    0.9588282108306885,
    0.95526522397995,
    0.95961993932724,
    0.9600158333778381,
    0.9604117274284363,
    0.9592240452766418,
    0.9663499593734741,
    0.9691211581230164,
    0.9651623368263245,
    0.9671417474746704,
    0.965954065322876,
    0.9714964628219604,
    0.9679334759712219,
    0.9714964628219604,
    0.9691211581230164,
    0.972288191318512,
    0.965954065322876,
    0.9683293700218201,
    0.9750593900680542,
    0.9714964628219604,
    0.9762470126152039,
    0.9742676019668579,
    0.978622317314148,
    0.9802058339118958,
    0.9778305888175964,
    0.9774346947669983,
    0.9798099994659424,
    0.9762470126152039,
    0.9802058339118958
  ],
  "auc": [
    0.8470970988273621,
    0.9322379231452942,
    0.9563591480255127,
    0.9596657156944275,
    0.9633286595344543,
    0.965471625328064,
    0.9673795700073242,
    0.975376546382904,
    0.9753962755203247,
    0.9795354604721069,
    0.983555018901825,
    0.9843204617500305,
    0.9872354865074158,
    0.9860870838165283,
    0.9880301356315613,
    0.9914360046386719,
    0.9914072155952454,
    0.9920033812522888,
    0.9923152923583984,
    0.9932336807250977,
    0.993423342704773,
    0.9937441945075989,
    0.9947463274002075,
    0.9958171248435974,
    0.9954885244369507,
    0.9962561726570129,
    0.99627685546875,
    0.9962337017059326,
    0.9963719248771667,
    0.9969965815544128,
    0.9960509538650513,
    0.9964137673377991,
    0.9960094690322876,
    0.9966955780982971,
    0.9978212118148804,
    0.9979245662689209,
    0.9977754950523376,
    0.9972096681594849,
    0.9978870749473572,
    0.9983540177345276,
    0.9984130263328552,
    0.9978009462356567,
    0.9978773593902588,
    0.9975278973579407,
    0.9985057711601257
  ],
  "loss": [
    0.5183326601982117,
    0.33225324749946594,
    0.2521948218345642,
    0.23683199286460876,
    0.2177293449640274,
    0.20458023250102997,
    0.19720758497714996,
    0.17167861759662628,
    0.17032162845134735,
    0.159319669008255,
    0.1419064700603485,
    0.13811925053596497,
    0.12764248251914978,
    0.1328023374080658,
    0.12172192335128784,
    0.1101856380701065,
    0.10797187685966492,
    0.10465041548013687,
    0.10276518017053604,
    0.09841547161340714,
    0.09460442513227463,
    0.09372573345899582,
    0.0876614898443222,
    0.08065486699342728,
    0.08205433934926987,
    0.07753577828407288,
    0.07722771912813187,
    0.07533156871795654,
    0.07434292137622833,
    0.07019970566034317,
    0.07430001348257065,
    0.0710882842540741,
    0.07600400596857071,
    0.07186071574687958,
    0.06192861869931221,
    0.06119454652070999,
    0.0590643510222435,
    0.06321772187948227,
    0.05591703578829765,
    0.052560094743967056,
    0.05176914483308792,
    0.05907347798347473,
    0.054369330406188965,
    0.06024665758013725,
    0.05110759660601616
  ],
  "precision": [
    0.771766722202301,
    0.8539493083953857,
    0.877386212348938,
    0.8832713961601257,
    0.897853434085846,
    0.9005158543586731,
    0.9052553772926331,
    0.9111769199371338,
    0.9096965193748474,
    0.9094922542572021,
    0.919881284236908,
    0.9209164977073669,
    0.9200000166893005,
    0.9190794229507446,
    0.9266666769981384,
    0.9319371581077576,
    0.9321401715278625,
    0.931034505367279,
    0.934831440448761,
    0.9375,
    0.9349289536476135,
    0.9367470145225525,
    0.9455370903015137,
    0.9492039680480957,
    0.9488158822059631,
    0.9456193447113037,
    0.9537394046783447,
    0.9563218355178833,
    0.9532208442687988,
    0.9556235671043396,
    0.9589465260505676,
    0.9599074721336365,
    0.9537394046783447,
    0.9553502798080444,
    0.9636785387992859,
    0.9591364860534668,
    0.966640830039978,
    0.9629057049751282,
    0.9696969985961914,
    0.9697908759117126,
    0.9703819155693054,
    0.9681677222251892,
    0.9719626307487488,
    0.9659178853034973,
    0.9705197811126709
  ],
  "recall": [
    0.7228820323944092,
    0.9073634147644043,
    0.9461599588394165,
    0.940617561340332,
    0.9604117274284363,
    0.9675375819206238,
    0.9683293700218201,
    0.974663496017456,
    0.9730799794197083,
    0.978622317314148,
    0.9817894101142883,
    0.9865399599075317,
    0.9833729267120361,
    0.9802058339118958,
    0.9904988408088684,
    0.9865399599075317,
    0.9897070527076721,
    0.9833729267120361,
    0.9881235361099243,
    0.9857482314109802,
    0.9897070527076721,
    0.9849564433097839,
    0.9897070527076721,
    0.9912905693054199,
    0.9833729267120361,
    0.9912905693054199,
    0.9794141054153442,
    0.9881235361099243,
    0.9841647148132324,
    0.9889152646064758,
    0.9802058339118958,
    0.9857482314109802,
    0.9794141054153442,
    0.9825811386108398,
    0.987331748008728,
    0.9849564433097839,
    0.9865399599075317,
    0.9865399599075317,
    0.9881235361099243,
    0.9912905693054199,
    0.9857482314109802,
    0.987331748008728,
    0.9881235361099243,
    0.987331748008728,
    0.9904988408088684
  ],
  "val_accuracy": [
    0.8700000047683716,
    0.9200000166893005,
    0.9350000023841858,
    0.9399999976158142,
    0.949999988079071,
    0.949999988079071,
    0.949999988079071,
    0.949999988079071,
    0.949999988079071,
    0.949999988079071,
    0.949999988079071,
    0.949999988079071,
    0.949999988079071,
    0.9449999928474426,
    0.9449999928474426,
    0.949999988079071,
    0.949999988079071,
    0.949999988079071,
    0.9549999833106995,
    0.949999988079071,
    0.9599999785423279,
    0.9599999785423279,
    0.9599999785423279,
    0.9649999737739563,
    0.9549999833106995,
    0.9599999785423279,
    0.9599999785423279,
    0.9649999737739563,
    0.9700000286102295,
    0.9599999785423279,
    0.9750000238418579,
    0.9700000286102295,
    0.9649999737739563,
    0.9700000286102295,
    0.9649999737739563,
    0.9700000286102295,
    0.9700000286102295,
    0.9700000286102295,
    0.9850000143051147,
    0.9850000143051147,
    0.9700000286102295,
    0.9750000238418579,
    0.9750000238418579,
    0.9850000143051147,
    0.9850000143051147
  ],
  "val_auc": [
    0.9400500059127808,
    0.9577499628067017,
    0.9645999670028687,
    0.9678000211715698,
    0.9704499840736389,
    0.9755999445915222,
    0.9801999926567078,
    0.9832499623298645,
    0.9871500134468079,
    0.9891499876976013,
    0.9934999346733093,
    0.9957500100135803,
    0.996399998664856,
    0.9968999624252319,
    0.9970499277114868,
    0.9970499873161316,
    0.9968999624252319,
    0.9971500635147095,
    0.9973499774932861,
    0.9972500205039978,
    0.9975000023841858,
    0.9971999526023865,
    0.9973999857902527,
    0.9976500272750854,
    0.9976499676704407,
    0.997749924659729,
    0.9979498982429504,
    0.9980999231338501,
    0.998449981212616,
    0.9980499148368835,
    0.9983499646186829,
    0.9986999034881592,
    0.9987999200820923,
    0.9989499449729919,
    0.9989999532699585,
    0.9989498853683472,
    0.9990999102592468,
    0.9993999004364014,
    0.9993999600410461,
    0.999799907207489,
    0.9993999004364014,
    0.999299943447113,
    0.9995998740196228,
    0.9995998740196228,
    0.9996998906135559
  ],
  "val_loss": [
    0.35407131910324097,
    0.24523203074932098,
    0.2105613648891449,
    0.191690593957901,
    0.17697513103485107,
    0.16224105656147003,
    0.1499718278646469,
    0.13935215771198273,
    0.13005103170871735,
    0.12347472459077835,
    0.11347558349370956,
    0.10757958143949509,
    0.10208253562450409,
    0.09760779142379761,
    0.09423058480024338,
    0.08866896480321884,
    0.08715683221817017,
    0.08233100175857544,
    0.08040262013673782,
    0.07870893180370331,
    0.07496409118175507,
    0.07549633085727692,
    0.07444672286510468,
    0.07143230736255646,
    0.07108566164970398,
    0.06810055673122406,
    0.06874348968267441,
    0.0655287429690361,
    0.06474564224481583,
    0.06386646628379822,
    0.06168309599161148,
    0.0584702305495739,
    0.05723975598812103,
    0.05563129112124443,
    0.05526445433497429,
    0.05403861403465271,
    0.051239028573036194,
    0.052858781069517136,
    0.04773183912038803,
    0.04382484406232834,
    0.04866347834467888,
    0.04562385007739067,
    0.04527899622917175,
    0.04167601466178894,
    0.04224291816353798
  ],
  "val_precision": [
    0.849056601524353,
    0.8684210777282715,
    0.8918918967247009,
    0.8999999761581421,
    0.9166666865348816,
    0.9166666865348816,
    0.9166666865348816,
    0.9166666865348816,
    0.9166666865348816,
    0.9166666865348816,
    0.9166666865348816,
    0.9166666865348816,
    0.9166666865348816,
    0.9158878326416016,
    0.9158878326416016,
    0.9245283007621765,
    0.9245283007621765,
    0.9245283007621765,
    0.9252336621284485,
    0.9245283007621765,
    0.9339622855186462,
    0.9339622855186462,
    0.9339622855186462,
    0.9428571462631226,
    0.9333333373069763,
    0.942307710647583,
    0.9339622855186462,
    0.9428571462631226,
    0.9433962106704712,
    0.942307710647583,
    0.9523809552192688,
    0.9433962106704712,
    0.9514563083648682,
    0.9519230723381042,
    0.9428571462631226,
    0.9433962106704712,
    0.9433962106704712,
    0.9433962106704712,
    0.9708737730979919,
    0.9708737730979919,
    0.9433962106704712,
    0.9523809552192688,
    0.9523809552192688,
    0.9708737730979919,
    0.9708737730979919
  ],
  "val_recall": [
    0.8999999761581421,
    0.9900000095367432,
    0.9900000095367432,
    0.9900000095367432,
    0.9900000095367432,
    0.9900000095367432,
    0.9900000095367432,
    0.9900000095367432,
    0.9900000095367432,
    0.9900000095367432,
    0.9900000095367432,
    0.9900000095367432,
    0.9900000095367432,
    0.9800000190734863,
    0.9800000190734863,
    0.9800000190734863,
    0.9800000190734863,
    0.9800000190734863,
    0.9900000095367432,
    0.9800000190734863,
    0.9900000095367432,
    0.9900000095367432,
    0.9900000095367432,
    0.9900000095367432,
    0.9800000190734863,
    0.9800000190734863,
    0.9900000095367432,
    0.9900000095367432,
    1.0,
    0.9800000190734863,
    1.0,
    1.0,
    0.9800000190734863,
    0.9900000095367432,
    0.9900000095367432,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0
  ]
}

========== CSV FILES IN ATTACHED DATASETS ==========
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/efficientnetb0_training_log.csv
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/final_model_comparison.csv
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/mobilenetv2_training_log.csv
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/questionnaire_mlp_training_log.csv
/kaggle/input/datasets/shahbaz18/backup/asd_care_results/resnet50_training_log.csv
/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_csv/test.csv
/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_csv/train.csv
/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset/Dataset_csv/valid.csv

CSV files found: 8

Audit only — no training or file changes.

In [64]:

# Cell 6 — Audit questionnaire dataset splits
import pandas as pd
from pathlib import Path

data_dir = Path(
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset/Dataset_csv"
)

files = {
    "train": data_dir / "train.csv",
    "valid": data_dir / "valid.csv",
    "test": data_dir / "test.csv",
}

dfs = {}

for split, path in files.items():
    print(f"\n{'=' * 18} {split.upper()} {'=' * 18}")

    if not path.exists():
        print("FILE NOT FOUND:", path)
        continue

    df = pd.read_csv(path)
    dfs[split] = df

    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())

    # Show distributions only for likely target/label columns
    targets = [
        c for c in df.columns
        if any(k in c.lower() for k in
               ["class", "label", "target", "autism", "asd", "diagnos", "dx_group"])
    ]

    for col in targets:
        print(f"\nPossible label: {col}")
        print(df[col].value_counts(dropna=False).head(15).to_dict())

# Check overlaps using shared columns that look like participant identifiers
if len(dfs) >= 2:
    print("\n========== POSSIBLE ID OVERLAP ==========")

    splits = list(dfs.keys())
    for i in range(len(splits)):
        for j in range(i + 1, len(splits)):
            a_name, b_name = splits[i], splits[j]
            a, b = dfs[a_name], dfs[b_name]

            common = set(a.columns) & set(b.columns)
            id_cols = [
                c for c in common
                if any(k in c.lower() for k in
                       ["participant", "subject", "person_id", "patient_id",
                        "record_id", "sample_id", "nd ar", "guid", "id"])
            ]

            if not id_cols:
                print(f"{a_name} vs {b_name}: no obvious shared ID column")
                continue

            for col in id_cols:
                av = set(a[col].dropna().astype(str))
                bv = set(b[col].dropna().astype(str))
                overlap = av & bv
                print(
                    f"{a_name} vs {b_name} | {col}: "
                    f"{len(overlap)} overlapping values "
                    f"(A unique={len(av)}, B unique={len(bv)})"
                )

print("\nAudit complete — no data or models modified.")

================== TRAIN ==================
Shape: (2526, 16)
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']

Possible label: Family_ASD
{'no': 2017, 'yes': 509}

Possible label: Class
{'YES': 1263, 'NO': 1263}

================== VALID ==================
Shape: (200, 16)
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']

Possible label: Family_ASD
{'no': 155, 'yes': 45}

Possible label: Class
{'YES': 100, 'NO': 100}

================== TEST ==================
Shape: (200, 16)
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']

Possible label: Family_ASD
{'no': 155, 'yes': 45}

Possible label: Class
{'YES': 100, 'NO': 100}

========== POSSIBLE ID OVERLAP ==========
train vs valid: no obvious shared ID column
train vs test: no obvious shared ID column
valid vs test: no obvious shared ID column

Audit complete — no data or models modified.

In [65]:

# Cell 7 — Audit questionnaire labels and image-path overlap
# AUDIT ONLY: does not train models or modify saved files.

import pandas as pd
from pathlib import Path
from collections import Counter

data_dir = Path(
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset/Dataset_csv"
)

dfs = {
    split: pd.read_csv(data_dir / f"{split}.csv")
    for split in ["train", "valid", "test"]
}

# 1. Check whether Class is directly determined by A1–A10
for split, df in dfs.items():
    print(f"\n===== {split.upper()}: LABEL RELATIONSHIP =====")

    answers = [f"A{i}" for i in range(1, 11)]
    missing = [c for c in answers + ["Class", "image_path"] if c not in df.columns]

    if missing:
        print("Missing columns:", missing)
        continue

    print("Class distribution:")
    print(df["Class"].value_counts(dropna=False).to_dict())

    df["_answer_sum"] = df[answers].apply(
        pd.to_numeric, errors="coerce"
    ).sum(axis=1, min_count=10)

    print("\nAnswer-sum summary by Class:")
    print(df.groupby("Class")["_answer_sum"].agg(
        ["count", "min", "median", "max", "mean"]
    ).to_string())

    print("\nClass vs answer sum (top combinations):")
    print(pd.crosstab(df["_answer_sum"], df["Class"]).head(20).to_string())

    print("\nA1–A10 missing-value counts:")
    print(df[answers].isna().sum().to_dict())

# 2. Check exact image path overlap between splits
print("\n===== EXACT IMAGE-PATH OVERLAP =====")

path_sets = {}
for split, df in dfs.items():
    paths = df["image_path"].dropna().astype(str).str.strip()
    path_sets[split] = set(paths)
    print(
        f"{split}: rows={len(df)}, unique_paths={paths.nunique()}, "
        f"missing_paths={df['image_path'].isna().sum()}"
    )

for a, b in [("train", "valid"), ("train", "test"), ("valid", "test")]:
    common = path_sets[a] & path_sets[b]
    print(f"{a} vs {b}: {len(common)} identical image_path values")
    if common:
        print("Examples:", list(common)[:5])

# 3. Check whether answer patterns repeat with conflicting labels
print("\n===== REPEATED ANSWER PATTERNS =====")
all_df = pd.concat(
    [df.assign(_split=split) for split, df in dfs.items()],
    ignore_index=True
)

answers = [f"A{i}" for i in range(1, 11)]
all_df["_answer_pattern"] = (
    all_df[answers].astype(str).agg("|".join, axis=1)
)

pattern_label_counts = all_df.groupby("_answer_pattern")["Class"].nunique()
conflicting = pattern_label_counts[pattern_label_counts > 1]

print("Unique answer patterns:", all_df["_answer_pattern"].nunique())
print("Patterns associated with multiple Class labels:", len(conflicting))

print("\nAudit complete. No models or source CSVs modified.")

===== TRAIN: LABEL RELATIONSHIP =====
Class distribution:
{'YES': 1263, 'NO': 1263}

Answer-sum summary by Class:
       count  min  median  max      mean
Class
NO      1263    0     4.0   10  4.159145
YES     1263    7     8.0   10  8.159937

Class vs answer sum (top combinations):
Class         NO  YES
_answer_sum
0             47    0
1             90    0
2            147    0
3            208    0
4            225    0
5            205    0
6            219    0
7             44  409
8             27  402
9             28  293
10            23  159

A1–A10 missing-value counts:
{'A1': 0, 'A2': 0, 'A3': 0, 'A4': 0, 'A5': 0, 'A6': 0, 'A7': 0, 'A8': 0, 'A9': 0, 'A10': 0}

===== VALID: LABEL RELATIONSHIP =====
Class distribution:
{'YES': 100, 'NO': 100}

Answer-sum summary by Class:
       count  min  median  max  mean
Class
NO       100    0     4.0   10  4.15
YES      100    7     8.0   10  8.16

Class vs answer sum (top combinations):
Class        NO  YES
_answer_sum
0             4    0
1            11    0
2             6    0
3            16    0
4            22    0
5            16    0
6            15    0
7             2   32
8             2   32
9             4   24
10            2   12

A1–A10 missing-value counts:
{'A1': 0, 'A2': 0, 'A3': 0, 'A4': 0, 'A5': 0, 'A6': 0, 'A7': 0, 'A8': 0, 'A9': 0, 'A10': 0}

===== TEST: LABEL RELATIONSHIP =====
Class distribution:
{'YES': 100, 'NO': 100}

Answer-sum summary by Class:
       count  min  median  max  mean
Class
NO       100    0     4.0   10  4.15
YES      100    7     8.0   10  8.16

Class vs answer sum (top combinations):
Class        NO  YES
_answer_sum
0             4    0
1            11    0
2             6    0
3            16    0
4            22    0
5            16    0
6            15    0
7             2   32
8             2   32
9             4   24
10            2   12

A1–A10 missing-value counts:
{'A1': 0, 'A2': 0, 'A3': 0, 'A4': 0, 'A5': 0, 'A6': 0, 'A7': 0, 'A8': 0, 'A9': 0, 'A10': 0}

===== EXACT IMAGE-PATH OVERLAP =====
train: rows=2526, unique_paths=2526, missing_paths=0
valid: rows=200, unique_paths=200, missing_paths=0
test: rows=200, unique_paths=200, missing_paths=0
train vs valid: 0 identical image_path values
train vs test: 0 identical image_path values
valid vs test: 0 identical image_path values

===== REPEATED ANSWER PATTERNS =====
Unique answer patterns: 622
Patterns associated with multiple Class labels: 56

Audit complete. No models or source CSVs modified.

In [66]:

# Cell 8 — Verify saved models and final results
# No training. No files modified.

from pathlib import Path
import json
import pandas as pd

root = Path("/kaggle/input/datasets/shahbaz18/backup/asd_care_results")

assert root.exists(), (
    f"Backup not found: {root}\n"
    "Make sure the Kaggle dataset 'backup' is attached."
)

comparison = root / "final_model_comparison.csv"

if comparison.exists():
    print("===== SAVED MODEL COMPARISON =====")
    print(pd.read_csv(comparison).to_string(index=False))
else:
    print("Comparison CSV not found; listing individual results.")

    for p in sorted(root.glob("*test_results.json")):
        print(f"\n===== {p.name} =====")
        with open(p, "r") as f:
            print(json.dumps(json.load(f), indent=2))

print("\n===== REQUIRED ARTIFACTS =====")
for pattern in [
    "*best.keras",
    "*test_predictions.npz",
    "*history.json",
    "questionnaire_preprocessing.json",
    "research_limitations.json"
]:
    found = sorted(root.glob(pattern))
    print(f"\n{pattern}: {len(found)} file(s)")
    for p in found:
        print(f"  {p.name} ({p.stat().st_size / 1024 / 1024:.2f} MB)")

===== SAVED MODEL COMPARISON =====
            model  test_samples  accuracy  precision  recall       f1  roc_auc     confusion_matrix
Questionnaire MLP           200     0.985   0.970874    1.00 0.985222   0.9998  [[97, 3], [0, 100]]
         ResNet50           200     0.890   0.897959    0.88 0.888889   0.9509 [[90, 10], [12, 88]]
   EfficientNetB0           200     0.815   0.888889    0.72 0.795580   0.9347  [[91, 9], [28, 72]]
      MobileNetV2           200     0.850   0.857143    0.84 0.848485   0.9307 [[86, 14], [16, 84]]

===== REQUIRED ARTIFACTS =====

*best.keras: 4 file(s)
  efficientnetb0_best.keras (16.27 MB)
  mobilenetv2_best.keras (11.06 MB)
  questionnaire_mlp_best.keras (0.04 MB)
  resnet50_best.keras (90.63 MB)

*test_predictions.npz: 4 file(s)
  efficientnetb0_test_predictions.npz (0.00 MB)
  mobilenetv2_test_predictions.npz (0.00 MB)
  questionnaire_mlp_test_predictions.npz (0.00 MB)
  resnet50_test_predictions.npz (0.00 MB)

*history.json: 4 file(s)
  efficientnetb0_history.json (0.00 MB)
  mobilenetv2_history.json (0.00 MB)
  questionnaire_mlp_history.json (0.01 MB)
  resnet50_history.json (0.00 MB)

questionnaire_preprocessing.json: 1 file(s)
  questionnaire_preprocessing.json (0.00 MB)

research_limitations.json: 1 file(s)
  research_limitations.json (0.00 MB)

In [69]:

# Cell 9 — Save final results and limitations in Kaggle
# Uses the existing comparison CSV; no model training.

from pathlib import Path
import json
import pandas as pd

root = Path("/kaggle/input/datasets/shahbaz18/backup/asd_care_results")
out = Path("/kaggle/working/asd_care_final_report")
out.mkdir(parents=True, exist_ok=True)

comparison_path = root / "final_model_comparison.csv"
assert comparison_path.exists(), f"Missing: {comparison_path}"

comparison = pd.read_csv(comparison_path)
comparison.to_csv(out / "final_model_comparison.csv", index=False)
comparison.to_json(
    out / "final_model_comparison.json",
    orient="records",
    indent=2
)

limitations = {
    "project_type": "Research prototype",
    "clinical_validation": False,
    "image_models": ["MobileNetV2", "EfficientNetB0", "ResNet50"],
    "questionnaire_model": "Separate questionnaire-only baseline",
    "questionnaire_caveat": (
        "Class labels are strongly associated with the sum of A1-A10. "
        "The high questionnaire accuracy may reflect label construction."
    ),
    "fusion_caveat": (
        "Participant-level image-questionnaire matching is unverified. "
        "Do not report fused multimodal performance without verified pairs."
    ),
    "generalization_caveat": (
        "Results come from one held-out test split and do not establish "
        "external generalization."
    )
}

with open(out / "research_limitations.json", "w", encoding="utf-8") as f:
    json.dump(limitations, f, indent=2)

print("Saved final comparison and limitations to:", out)
print("\nComparison:")
print(comparison.to_string(index=False))
print("\nCreated files:")
for p in sorted(out.iterdir()):
    print(p.name, f"{p.stat().st_size:,} bytes")

Saved final comparison and limitations to: /kaggle/working/asd_care_final_report

Comparison:
            model  test_samples  accuracy  precision  recall       f1  roc_auc     confusion_matrix
Questionnaire MLP           200     0.985   0.970874    1.00 0.985222   0.9998  [[97, 3], [0, 100]]
         ResNet50           200     0.890   0.897959    0.88 0.888889   0.9509 [[90, 10], [12, 88]]
   EfficientNetB0           200     0.815   0.888889    0.72 0.795580   0.9347  [[91, 9], [28, 72]]
      MobileNetV2           200     0.850   0.857143    0.84 0.848485   0.9307 [[86, 14], [16, 84]]

Created files:
final_model_comparison.csv 453 bytes
final_model_comparison.json 891 bytes
research_limitations.json 643 bytes

In [71]:

# Cell 10 — Create one final ZIP package (no training)

from pathlib import Path
import shutil
import json

source = Path("/kaggle/input/datasets/shahbaz18/backup/asd_care_results")
report = Path("/kaggle/working/asd_care_final_report")
package = Path("/kaggle/working/asd_care_final_package")

package.mkdir(parents=True, exist_ok=True)

# Copy final comparison and research limitations
for name in [
    "final_model_comparison.csv",
    "final_model_comparison.json",
    "research_limitations.json"
]:
    src = report / name
    if src.exists():
        shutil.copy2(src, package / name)

# Include saved models, prediction files, histories and result JSONs
patterns = [
    "*_best.keras",
    "*_test_predictions.npz",
    "*_test_results.json",
    "*history*.json",
    "*training*.log",
    "questionnaire_preprocessing.json",
    "questionnaire_scaler.json",
]

copied = set()
for pattern in patterns:
    for src in source.glob(pattern):
        if src.is_file() and src.name not in copied:
            shutil.copy2(src, package / src.name)
            copied.add(src.name)

# Include any existing training logs with other extensions
for src in source.glob("*"):
    if src.is_file() and (
        "training" in src.name.lower()
        or "history" in src.name.lower()
    ):
        if src.name not in copied:
            shutil.copy2(src, package / src.name)
            copied.add(src.name)

# Write a README with interpretation cautions
readme = """
ASD CARE — FINAL RESEARCH ARTIFACTS

Included:
- Final model comparison
- Research limitations
- Saved model checkpoints
- Test prediction arrays and test result JSON files
- Available training histories/logs
- Questionnaire preprocessing/scaler files, if present

IMAGE-ONLY TEST RESULTS:
ResNet50:       Accuracy 0.890, ROC-AUC 0.9509
MobileNetV2:    Accuracy 0.850, ROC-AUC 0.9307
EfficientNetB0: Accuracy 0.815, ROC-AUC 0.9347

QUESTIONNAIRE BASELINE:
Accuracy 0.985, ROC-AUC 0.9998.
Important: questionnaire labels are strongly associated with A1-A10
answer sums. This result may reflect label construction and should not
be presented as independent proof of autism detection.

IMPORTANT LIMITATIONS:
- Research prototype only; not clinically validated.
- Participant-level matching of images and questionnaire records
  has not been verified.
- Do not claim multimodal fusion results without verified paired data.
- One held-out test split does not establish external generalization.

Use the saved predictions for further analysis; do not retrain unless needed.
"""
(package / "README.txt").write_text(readme.strip() + "\n", encoding="utf-8")

# Create downloadable archive
zip_base = Path("/kaggle/working/asd_care_final_package")
zip_path = shutil.make_archive(str(zip_base), "zip", root_dir=package)

print("PACKAGE CREATED:", zip_path)
print("Package size (MB):", round(Path(zip_path).stat().st_size / (1024**2), 2))
print("\nIncluded files:")
for p in sorted(package.iterdir()):
    print(f"{p.name} — {p.stat().st_size:,} bytes")

PACKAGE CREATED: /kaggle/working/asd_care_final_package.zip
Package size (MB): 107.72

Included files:
README.txt — 1,071 bytes
efficientnetb0_best.keras — 17,060,174 bytes
efficientnetb0_history.json — 1,535 bytes
efficientnetb0_test_predictions.npz — 1,453 bytes
efficientnetb0_test_results.json — 299 bytes
efficientnetb0_training_log.csv — 1,204 bytes
final_model_comparison.csv — 453 bytes
final_model_comparison.json — 891 bytes
mobilenetv2_best.keras — 11,598,058 bytes
mobilenetv2_history.json — 2,108 bytes
mobilenetv2_test_predictions.npz — 1,456 bytes
mobilenetv2_test_results.json — 276 bytes
mobilenetv2_training_log.csv — 1,627 bytes
questionnaire_mlp_best.keras — 43,974 bytes
questionnaire_mlp_history.json — 10,820 bytes
questionnaire_mlp_test_predictions.npz — 1,354 bytes
questionnaire_mlp_test_results.json — 375 bytes
questionnaire_mlp_training_log.csv — 8,635 bytes
questionnaire_preprocessing.json — 1,196 bytes
questionnaire_scaler.json — 1,060 bytes
research_limitations.json — 643 bytes
resnet50_best.keras — 95,034,718 bytes
resnet50_history.json — 1,557 bytes
resnet50_test_predictions.npz — 1,438 bytes
resnet50_test_results.json — 293 bytes
resnet50_training_log.csv — 1,226 bytes

In [72]:

# Cell 11 — Verify whether questionnaire records link to real images

from pathlib import Path
import pandas as pd

data_dir = Path(
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset/Dataset_csv"
)

for split in ["train", "valid", "test"]:
    csv_path = data_dir / f"{split}.csv"
    df = pd.read_csv(csv_path)

    print(f"\n===== {split.upper()} =====")
    print("Rows:", len(df))
    print("Columns:", df.columns.tolist())

    if "image_path" not in df.columns:
        print("STOP: No image_path column.")
        continue

    paths = df["image_path"].dropna().astype(str)
    print("Example image paths:")
    for p in paths.head(5):
        print(" ", p)

    exists_count = 0
    for p in paths:
        candidate = Path(p)
        if candidate.is_file():
            exists_count += 1
        elif (data_dir / p).is_file():
            exists_count += 1

    print(f"Image files found: {exists_count}/{len(paths)}")
    print("Unique image paths:", paths.nunique())
    print("Label counts:")
    print(df["Class"].value_counts(dropna=False).to_string())

print("\nAudit complete. No models were trained or changed.")

===== TRAIN =====
Rows: 2526
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']
Example image paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0851.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0779.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1063.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/0164.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/train/autistic/1080.jpg
Image files found: 2526/2526
Unique image paths: 2526
Label counts:
Class
YES    1263
NO     1263

===== VALID =====
Rows: 200
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']
Example image paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/003.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/097.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/064.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/071.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/valid/autistic/005.jpg
Image files found: 200/200
Unique image paths: 200
Label counts:
Class
YES    100
NO     100

===== TEST =====
Rows: 200
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']
Example image paths:
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/001.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/067.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/049.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/074.jpg
  /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset/test/autistic/089.jpg
Image files found: 200/200
Unique image paths: 200
Label counts:
Class
YES    100
NO     100

Audit complete. No models were trained or changed.

In [73]:

# Cell 12 — Final pairing and label-leakage audit (no training)

from pathlib import Path
import pandas as pd

data_dir = Path(
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset/Dataset_csv"
)

answer_cols = [f"A{i}" for i in range(1, 11)]

for split in ["train", "valid", "test"]:
    df = pd.read_csv(data_dir / f"{split}.csv")
    df["Class"] = df["Class"].astype(str).str.strip().str.upper()
    df["answer_sum"] = df[answer_cols].apply(
        pd.to_numeric, errors="coerce"
    ).sum(axis=1)

    # Infer image label from the parent folder name.
    folder = df["image_path"].astype(str).apply(
        lambda p: Path(p).parent.name.lower()
    )

    def infer_image_label(name):
        if "typical" in name or name in {"td", "control", "controls"}:
            return "NO"
        if "autistic" in name or name == "asd":
            return "YES"
        return "UNKNOWN"

    df["image_label"] = folder.apply(infer_image_label)

    print(f"\n===== {split.upper()} =====")
    print("Image-folder labels:")
    print(df["image_label"].value_counts().to_string())

    known = df[df["image_label"] != "UNKNOWN"]
    if len(known):
        print("\nImage-folder label vs CSV Class:")
        print(pd.crosstab(known["image_label"], known["Class"]).to_string())
        print(
            "Agreement:",
            f"{(known['image_label'] == known['Class']).mean():.1%}"
        )

    print("\nQuestionnaire answer-sum ranges by Class:")
    print(
        df.groupby("Class")["answer_sum"]
          .agg(["count", "min", "median", "max", "mean"])
          .to_string()
    )

    print("\nClass by answer-sum range:")
    bins = [-1, 5, 6, 10, 100]
    labels = ["0–5", "6", "7–10", "11+"]
    df["sum_range"] = pd.cut(
        df["answer_sum"], bins=bins, labels=labels
    )
    print(pd.crosstab(df["sum_range"], df["Class"]).to_string())

print(
    "\nIMPORTANT: Matching file paths and matching labels do not prove "
    "that the questionnaire respondent is the person pictured."
)

===== TRAIN =====
Image-folder labels:
image_label
YES    2526

Image-folder label vs CSV Class:
Class          NO   YES
image_label
YES          1263  1263
Agreement: 50.0%

Questionnaire answer-sum ranges by Class:
       count  min  median  max      mean
Class
NO      1263    0     4.0   10  4.159145
YES     1263    7     8.0   10  8.159937

Class by answer-sum range:
Class       NO   YES
sum_range
0–5        922     0
6          219     0
7–10       122  1263

===== VALID =====
Image-folder labels:
image_label
YES    200

Image-folder label vs CSV Class:
Class         NO  YES
image_label
YES          100  100
Agreement: 50.0%

Questionnaire answer-sum ranges by Class:
       count  min  median  max  mean
Class
NO       100    0     4.0   10  4.15
YES      100    7     8.0   10  8.16

Class by answer-sum range:
Class      NO  YES
sum_range
0–5        75    0
6          15    0
7–10       10  100

===== TEST =====
Image-folder labels:
image_label
YES    200

Image-folder label vs CSV Class:
Class         NO  YES
image_label
YES          100  100
Agreement: 50.0%

Questionnaire answer-sum ranges by Class:
       count  min  median  max  mean
Class
NO       100    0     4.0   10  4.15
YES      100    7     8.0   10  8.16

Class by answer-sum range:
Class      NO  YES
sum_range
0–5        75    0
6          15    0
7–10       10  100

IMPORTANT: Matching file paths and matching labels do not prove that the questionnaire respondent is the person pictured.

In [74]:

# Cell 13 — Inspect image folders and dataset documentation (no training)

from pathlib import Path

roots = [
    Path("/kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset"),
    Path("/kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset"),
]

for root in roots:
    print(f"\n===== ROOT: {root} =====")
    print("Exists:", root.exists())

    if not root.exists():
        continue

    # Show directory structure to depth 3
    for p in sorted(root.rglob("*")):
        if p.is_dir():
            try:
                depth = len(p.relative_to(root).parts)
            except ValueError:
                depth = 99
            if depth <= 3:
                print("DIR ", p.relative_to(root))

    # Show likely documentation files
    docs = [
        p for p in root.rglob("*")
        if p.is_file()
        and p.suffix.lower() in {".txt", ".md", ".pdf", ".json"}
        and p.stat().st_size < 2_000_000
    ]

    print("\nPossible documentation files:")
    for p in docs[:30]:
        print("FILE", p.relative_to(root))

===== ROOT: /kaggle/input/datasets/prayashdas/autistic-children-facial-image-dataset =====
Exists: True
DIR  test
DIR  test/autistic
DIR  test/non_autistic
DIR  train
DIR  train/autistic
DIR  train/non_autistic
DIR  valid
DIR  valid/autistic
DIR  valid/non_autistic

Possible documentation files:

===== ROOT: /kaggle/input/datasets/ajithdari/autism-spectrum-disorder-multi-modal-dataset =====
Exists: True
DIR  Dataset_csv
DIR  Dataset_img
DIR  Dataset_img/test
DIR  Dataset_img/test/autistic
DIR  Dataset_img/test/non_autistic
DIR  Dataset_img/train
DIR  Dataset_img/train/autistic
DIR  Dataset_img/train/non_autistic
DIR  Dataset_img/valid
DIR  Dataset_img/valid/autistic
DIR  Dataset_img/valid/non_autistic

Possible documentation files:

In [75]:

# Cell 14 — Verify CSV rows against actual Dataset_img class folders
# Read-only audit; no training or file changes.

from pathlib import Path
import pandas as pd

base = Path(
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)
csv_dir = base / "Dataset_csv"
img_root = base / "Dataset_img"

for split in ["train", "valid", "test"]:
    df = pd.read_csv(csv_dir / f"{split}.csv")
    df["Class"] = df["Class"].astype(str).str.strip().str.upper()

    checked = 0
    found = 0
    matching = 0
    missing = []
    mismatches = []

    for _, row in df.iterrows():
        raw = str(row["image_path"])
        filename = Path(raw).name
        label = row["Class"]

        # Resolve the image inside this dataset's own image folders.
        candidates = [
            img_root / split / "autistic" / filename,
            img_root / split / "non_autistic" / filename,
        ]
        existing = [p for p in candidates if p.is_file()]

        checked += 1
        if len(existing) == 1:
            found += 1
            actual = existing[0].parent.name
            expected = "autistic" if label == "YES" else "non_autistic"

            if actual == expected:
                matching += 1
            elif len(mismatches) < 10:
                mismatches.append(
                    (filename, label, actual)
                )
        else:
            if len(missing) < 10:
                missing.append((filename, len(existing)))

    print(f"\n===== {split.upper()} =====")
    print("CSV rows checked:", checked)
    print("Unique image files found in Dataset_img:", found)
    print("Class-folder agreement:", f"{matching}/{found}" if found else "N/A")
    print("Example missing/ambiguous files:", missing)
    print("Example class mismatches:", mismatches)

print("\nThis verifies filename and class-folder consistency only.")
print("It cannot prove participant identity or questionnaire provenance.")

===== TRAIN =====
CSV rows checked: 2526
Unique image files found in Dataset_img: 0
Class-folder agreement: N/A
Example missing/ambiguous files: [('0851.jpg', 2), ('0779.jpg', 2), ('1063.jpg', 2), ('0164.jpg', 2), ('1080.jpg', 2), ('0179.jpg', 2), ('0010.jpg', 2), ('0265.jpg', 2), ('1173.jpg', 2), ('0884.jpg', 2)]
Example class mismatches: []

===== VALID =====
CSV rows checked: 200
Unique image files found in Dataset_img: 0
Class-folder agreement: N/A
Example missing/ambiguous files: [('003.jpg', 2), ('097.jpg', 2), ('064.jpg', 2), ('071.jpg', 2), ('005.jpg', 2), ('036.jpg', 2), ('096.jpg', 2), ('039.jpg', 2), ('023.jpg', 2), ('037.jpg', 2)]
Example class mismatches: []

===== TEST =====
CSV rows checked: 200
Unique image files found in Dataset_img: 0
Class-folder agreement: N/A
Example missing/ambiguous files: [('001.jpg', 2), ('067.jpg', 2), ('049.jpg', 2), ('074.jpg', 2), ('089.jpg', 2), ('011.jpg', 2), ('047.jpg', 2), ('013.jpg', 2), ('093.jpg', 2), ('079.jpg', 2)]
Example class mismatches: []

This verifies filename and class-folder consistency only.
It cannot prove participant identity or questionnaire provenance.

In [77]:

# Cell 14 — Verify CSV rows against actual Dataset_img class folders
# Read-only audit; no training or file changes.

from pathlib import Path
import pandas as pd

base = Path(
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)
csv_dir = base / "Dataset_csv"
img_root = base / "Dataset_img"

for split in ["train", "valid", "test"]:
    df = pd.read_csv(csv_dir / f"{split}.csv")
    df["Class"] = df["Class"].astype(str).str.strip().str.upper()

    checked = 0
    found = 0
    matching = 0
    missing = []
    mismatches = []

    for _, row in df.iterrows():
        raw = str(row["image_path"])
        filename = Path(raw).name
        label = row["Class"]

        # Resolve the image inside this dataset's own image folders.
        candidates = [
            img_root / split / "autistic" / filename,
            img_root / split / "non_autistic" / filename,
        ]
        existing = [p for p in candidates if p.is_file()]

        checked += 1
        if len(existing) == 1:
            found += 1
            actual = existing[0].parent.name
            expected = "autistic" if label == "YES" else "non_autistic"

            if actual == expected:
                matching += 1
            elif len(mismatches) < 10:
                mismatches.append(
                    (filename, label, actual)
                )
        else:
            if len(missing) < 10:
                missing.append((filename, len(existing)))

    print(f"\n===== {split.upper()} =====")
    print("CSV rows checked:", checked)
    print("Unique image files found in Dataset_img:", found)
    print("Class-folder agreement:", f"{matching}/{found}" if found else "N/A")
    print("Example missing/ambiguous files:", missing)
    print("Example class mismatches:", mismatches)

print("\nThis verifies filename and class-folder consistency only.")
print("It cannot prove participant identity or questionnaire provenance.")

===== TRAIN =====
CSV rows checked: 2526
Unique image files found in Dataset_img: 0
Class-folder agreement: N/A
Example missing/ambiguous files: [('0851.jpg', 2), ('0779.jpg', 2), ('1063.jpg', 2), ('0164.jpg', 2), ('1080.jpg', 2), ('0179.jpg', 2), ('0010.jpg', 2), ('0265.jpg', 2), ('1173.jpg', 2), ('0884.jpg', 2)]
Example class mismatches: []

===== VALID =====
CSV rows checked: 200
Unique image files found in Dataset_img: 0
Class-folder agreement: N/A
Example missing/ambiguous files: [('003.jpg', 2), ('097.jpg', 2), ('064.jpg', 2), ('071.jpg', 2), ('005.jpg', 2), ('036.jpg', 2), ('096.jpg', 2), ('039.jpg', 2), ('023.jpg', 2), ('037.jpg', 2)]
Example class mismatches: []

===== TEST =====
CSV rows checked: 200
Unique image files found in Dataset_img: 0
Class-folder agreement: N/A
Example missing/ambiguous files: [('001.jpg', 2), ('067.jpg', 2), ('049.jpg', 2), ('074.jpg', 2), ('089.jpg', 2), ('011.jpg', 2), ('047.jpg', 2), ('013.jpg', 2), ('093.jpg', 2), ('079.jpg', 2)]
Example class mismatches: []

This verifies filename and class-folder consistency only.
It cannot prove participant identity or questionnaire provenance.

In [78]:

# Cell 15 — Check actual image filenames in both classes

from pathlib import Path
import pandas as pd

base = Path(
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset"
)
img_root = base / "Dataset_img"
csv_dir = base / "Dataset_csv"

for split in ["train", "valid", "test"]:
    print(f"\n===== {split.upper()} =====")

    df = pd.read_csv(csv_dir / f"{split}.csv")

    for cls in ["autistic", "non_autistic"]:
        folder = img_root / split / cls
        files = sorted(
            p.name for p in folder.iterdir()
            if p.is_file()
        ) if folder.exists() else []

        print(f"{cls}: {len(files)} files")
        print("Examples:", files[:8])

    autistic = {
        p.name for p in (img_root / split / "autistic").iterdir()
        if p.is_file()
    }
    non_autistic = {
        p.name for p in (img_root / split / "non_autistic").iterdir()
        if p.is_file()
    }

    print("Filenames present in BOTH classes:", len(autistic & non_autistic))
    print("CSV rows:", len(df))
    print("CSV image filename examples:",
          [Path(str(p)).name for p in df["image_path"].head(8)])

print("\nNo files modified; no training performed.")

===== TRAIN =====
autistic: 1263 files
Examples: ['0001.jpg', '0002.jpg', '0003.jpg', '0004.jpg', '0005.jpg', '0006.jpg', '0007.jpg', '0008.jpg']
non_autistic: 1263 files
Examples: ['0001.jpg', '0002.jpg', '0003.jpg', '0004.jpg', '0005.jpg', '0006.jpg', '0007.jpg', '0008.jpg']
Filenames present in BOTH classes: 1263
CSV rows: 2526
CSV image filename examples: ['0851.jpg', '0779.jpg', '1063.jpg', '0164.jpg', '1080.jpg', '0179.jpg', '0010.jpg', '0265.jpg']

===== VALID =====
autistic: 100 files
Examples: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg', '006.jpg', '007.jpg', '008.jpg']
non_autistic: 100 files
Examples: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg', '006.jpg', '007.jpg', '008.jpg']
Filenames present in BOTH classes: 100
CSV rows: 200
CSV image filename examples: ['003.jpg', '097.jpg', '064.jpg', '071.jpg', '005.jpg', '036.jpg', '096.jpg', '039.jpg']

===== TEST =====
autistic: 100 files
Examples: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg', '006.jpg', '007.jpg', '008.jpg']
non_autistic: 100 files
Examples: ['001.jpg', '002.jpg', '003.jpg', '004.jpg', '005.jpg', '006.jpg', '007.jpg', '008.jpg']
Filenames present in BOTH classes: 100
CSV rows: 200
CSV image filename examples: ['001.jpg', '067.jpg', '049.jpg', '074.jpg', '089.jpg', '011.jpg', '047.jpg', '013.jpg']

No files modified; no training performed.

In [79]:

# Cell 16 — Build an auditable pseudo-paired multimodal manifest
# No model training. Original files and checkpoints remain unchanged.
# IMPORTANT: Pairing is by class, NOT verified participant identity.

from pathlib import Path
import pandas as pd
import numpy as np
import json

csv_root = Path(
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset/Dataset_csv"
)
image_root = Path(
    "/kaggle/input/datasets/prayashdas/"
    "autistic-children-facial-image-dataset"
)
out = Path("/kaggle/working/asd_pseudo_multimodal")
out.mkdir(parents=True, exist_ok=True)

rng = np.random.default_rng(2026)
all_parts = []
audit = {
    "pairing_type": "synthetic class-stratified pseudo-pairing",
    "participant_identity_verified": False,
    "clinical_multimodal_validity_established": False,
    "seed": 2026,
    "splits": {}
}

for split in ["train", "valid", "test"]:
    df = pd.read_csv(csv_root / f"{split}.csv").copy()
    df["Class"] = df["Class"].astype(str).str.strip().str.upper()

    if not set(df["Class"].unique()).issubset({"YES", "NO"}):
        raise ValueError(f"Unexpected Class values in {split}")

    df["image_filename"] = df["image_path"].astype(str).map(
        lambda p: Path(p).name
    )

    # Use the correct class-specific folder.
    # This selects an image by its class label; it does NOT establish identity.
    df["image_class_folder"] = df["Class"].map({
        "YES": "autistic",
        "NO": "non_autistic"
    })
    df["resolved_image_path"] = df.apply(
        lambda r: str(
            image_root / split / r["image_class_folder"] /
            r["image_filename"]
        ),
        axis=1
    )

    missing = [
        p for p in df["resolved_image_path"]
        if not Path(p).is_file()
    ]
    if missing:
        raise FileNotFoundError(
            f"{split}: {len(missing)} class-specific images missing. "
            f"Examples: {missing[:5]}"
        )

    # Unique row ID; not a real participant ID.
    df["sample_id"] = [
        f"{split.upper()}_{i:05d}" for i in range(1, len(df) + 1)
    ]

    # Explicitly label pairing status for downstream reporting.
    df["pairing_status"] = "synthetic_class_stratified_unverified"
    df["participant_id"] = pd.NA

    # Keep all source questionnaire features and provenance columns.
    all_parts.append(df)

    audit["splits"][split] = {
        "rows": int(len(df)),
        "class_counts": {
            str(k): int(v) for k, v in df["Class"].value_counts().items()
        },
        "missing_resolved_images": 0,
        "unique_sample_ids": int(df["sample_id"].nunique()),
        "participant_ids_verified": False
    }

manifest = pd.concat(all_parts, ignore_index=True)

assert manifest["sample_id"].is_unique
assert manifest["resolved_image_path"].map(
    lambda p: Path(p).is_file()
).all()

manifest_path = out / "pseudo_multimodal_manifest.csv"
manifest.to_csv(manifest_path, index=False)

with open(out / "pairing_audit.json", "w", encoding="utf-8") as f:
    json.dump(audit, f, indent=2)

print("Manifest saved:", manifest_path)
print("Audit saved:", out / "pairing_audit.json")
print("Total rows:", len(manifest))
print("Unique sample IDs:", manifest["sample_id"].nunique())
print("All resolved images exist: YES")
print("\nPairing status:")
print(manifest["pairing_status"].value_counts().to_string())
print("\nClass counts by split:")
print(pd.crosstab(manifest["image_class_folder"], manifest["Class"]))
print(
    "\nWARNING: IDs identify dataset rows only. They do not identify people. "
    "This manifest is suitable for a synthetic pairing experiment only."
)

Manifest saved: /kaggle/working/asd_pseudo_multimodal/pseudo_multimodal_manifest.csv
Audit saved: /kaggle/working/asd_pseudo_multimodal/pairing_audit.json
Total rows: 2926
Unique sample IDs: 2926
All resolved images exist: YES

Pairing status:
pairing_status
synthetic_class_stratified_unverified    2926

Class counts by split:
Class                 NO   YES
image_class_folder
autistic               0  1463
non_autistic        1463     0

WARNING: IDs identify dataset rows only. They do not identify people. This manifest is suitable for a synthetic pairing experiment only.

In [80]:

# Cell 17 — Prepare multimodal prototype inputs
# Existing models remain untouched.

from pathlib import Path
import pandas as pd
import numpy as np
import tensorflow as tf

CSV_ROOT = Path(
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset/Dataset_csv"
)
IMAGE_ROOT = Path(
    "/kaggle/input/datasets/prayashdas/"
    "autistic-children-facial-image-dataset"
)
MODEL_ROOT = Path(
    "/kaggle/input/datasets/shahbaz18/backup/asd_care_results"
)
WORK = Path("/kaggle/working/asd_multimodal_prototype")
WORK.mkdir(parents=True, exist_ok=True)

image_model_path = MODEL_ROOT / "resnet50_best.keras"
questionnaire_model_path = MODEL_ROOT / "questionnaire_mlp_best.keras"

for p in [image_model_path, questionnaire_model_path]:
    assert p.exists(), f"Missing saved model: {p}"
    print(f"Found {p.name}: {p.stat().st_size / 1e6:.2f} MB")

# Load saved models for inference only.
image_model = tf.keras.models.load_model(image_model_path, compile=False)
questionnaire_model = tf.keras.models.load_model(
    questionnaire_model_path, compile=False
)

print("\nImage model input/output:", image_model.input_shape, image_model.output_shape)
print("Questionnaire model input/output:",
      questionnaire_model.input_shape, questionnaire_model.output_shape)

feature_cols = [
    "A1", "A2", "A3", "A4", "A5",
    "A6", "A7", "A8", "A9", "A10",
    "Age", "Sex", "Jauundice", "Family_ASD"
]

prepared = {}

for split in ["train", "valid", "test"]:
    df = pd.read_csv(CSV_ROOT / f"{split}.csv")
    df["Class"] = df["Class"].astype(str).str.strip().str.upper()
    df["label"] = df["Class"].map({"NO": 0, "YES": 1})

    if df["label"].isna().any():
        raise ValueError(f"Unexpected labels in {split}")

    # Resolve each image by the row's class label.
    df["image_path_resolved"] = df.apply(
        lambda r: str(
            IMAGE_ROOT / split /
            ("autistic" if r["label"] == 1 else "non_autistic") /
            Path(str(r["image_path"])).name
        ),
        axis=1
    )

    missing = [
        p for p in df["image_path_resolved"]
        if not Path(p).is_file()
    ]
    if missing:
        raise FileNotFoundError(
            f"{split}: missing images, examples: {missing[:5]}"
        )

    # Numeric, finite questionnaire features.
    Xq = df[feature_cols].copy()
    for c in feature_cols:
        Xq[c] = pd.to_numeric(Xq[c], errors="coerce")
        Xq[c] = Xq[c].fillna(Xq[c].median())
    Xq = Xq.astype("float32")

    prepared[split] = {
        "df": df,
        "image_paths": df["image_path_resolved"].tolist(),
        "Xq": Xq.to_numpy(),
        "y": df["label"].to_numpy(dtype="int32")
    }

    print(
        f"{split}: {len(df)} rows | "
        f"labels={dict(df['label'].value_counts().sort_index())} | "
        f"all images exist"
    )

print("\nPreparation complete. No training performed yet.")
print("Prototype outputs will be saved under:", WORK)
print("Note: this is class-based synthetic pairing, not verified participant matching.")

Found resnet50_best.keras: 95.03 MB
Found questionnaire_mlp_best.keras: 0.04 MB

Image model input/output: (None, 224, 224, 3) (None, 1)
Questionnaire model input/output: (None, 17) (None, 1)
train: 2526 rows | labels={0: np.int64(1263), 1: np.int64(1263)} | all images exist
valid: 200 rows | labels={0: np.int64(100), 1: np.int64(100)} | all images exist
test: 200 rows | labels={0: np.int64(100), 1: np.int64(100)} | all images exist

Preparation complete. No training performed yet.
Prototype outputs will be saved under: /kaggle/working/asd_multimodal_prototype
Note: this is class-based synthetic pairing, not verified participant matching.

In [82]:

# Cell 18A — Diagnose questionnaire input mismatch (no training)

import json
from pathlib import Path

import pandas as pd

MODEL_ROOT = Path(
    "/kaggle/input/datasets/shahbaz18/backup/asd_care_results"
)
CSV_ROOT = Path(
    "/kaggle/input/datasets/ajithdari/"
    "autism-spectrum-disorder-multi-modal-dataset/Dataset_csv"
)

for filename in [
    "questionnaire_preprocessing.json",
    "questionnaire_scaler.json",
]:
    path = MODEL_ROOT / filename
    print(f"\n===== {filename} =====")
    if path.exists():
        print(path.read_text(encoding="utf-8")[:12000])
    else:
        print("Not found")

print("\n===== CSV FEATURES =====")
df = pd.read_csv(CSV_ROOT / "train.csv")
print("Columns:", df.columns.tolist())
print("\nData types:")
print(df.dtypes.to_string())

print("\n===== SAVED MLP INPUT =====")
print("Expected feature count:", questionnaire_model.input_shape[-1])

print("\nDiagnostic complete. No models or files changed.")

===== questionnaire_preprocessing.json =====
{
  "numeric_features": [
    "A1",
    "A2",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "A9",
    "A10",
    "Age"
  ],
  "categorical_features": [
    "Sex",
    "Jauundice",
    "Family_ASD"
  ],
  "category_levels": {
    "Sex": [
      "f",
      "m"
    ],
    "Jauundice": [
      "no",
      "yes"
    ],
    "Family_ASD": [
      "no",
      "yes"
    ]
  },
  "numeric_medians": {
    "A1": 1.0,
    "A2": 1.0,
    "A3": 1.0,
    "A4": 1.0,
    "A5": 1.0,
    "A6": 1.0,
    "A7": 1.0,
    "A8": 1.0,
    "A9": 1.0,
    "A10": 1.0,
    "Age": 19.0
  },
  "scaler_mean": [
    0.7450514647664291,
    0.5324623911322248,
    0.6417260490894695,
    0.6441013460015835,
    0.6528107680126682,
    0.5566112430720507,
    0.5629453681710214,
    0.6084718923198733,
    0.5344418052256532,
    0.6809184481393508,
    20.507917656373714
  ],
  "scaler_scale": [
    0.435832283815492,
    0.49894508030641854,
    0.47949319808469576,
    0.47878471370808395,
    0.4760765371023639,
    0.49678482983867095,
    0.4960220565920578,
    0.48809204928634703,
    0.49881235154394304,
    0.46612070874704664,
    14.777089294960096
  ],
  "encoded_feature_count": 17
}

===== questionnaire_scaler.json =====
{
  "features": [
    "A1",
    "A2",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "A9",
    "A10",
    "Age",
    "Sex",
    "Jauundice",
    "Family_ASD"
  ],
  "mean": [
    0.7450514647664291,
    0.5324623911322248,
    0.6417260490894695,
    0.6441013460015835,
    0.6528107680126682,
    0.5566112430720507,
    0.5629453681710214,
    0.6084718923198733,
    0.5344418052256532,
    0.6809184481393508,
    20.507917656373714,
    NaN,
    NaN,
    NaN
  ],
  "scale": [
    0.435832283815492,
    0.49894508030641854,
    0.47949319808469576,
    0.47878471370808395,
    0.4760765371023639,
    0.49678482983867095,
    0.4960220565920578,
    0.48809204928634703,
    0.49881235154394304,
    0.46612070874704664,
    14.777089294960096,
    NaN,
    NaN,
    NaN
  ],
  "imputation_medians": {
    "A1": 1.0,
    "A2": 1.0,
    "A3": 1.0,
    "A4": 1.0,
    "A5": 1.0,
    "A6": 1.0,
    "A7": 1.0,
    "A8": 1.0,
    "A9": 1.0,
    "A10": 1.0,
    "Age": 19.0,
    "Sex": NaN,
    "Jauundice": NaN,
    "Family_ASD": NaN
  }
}

===== CSV FEATURES =====
Columns: ['image_path', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age', 'Sex', 'Jauundice', 'Family_ASD', 'Class']

Data types:
image_path    object
A1             int64
A2             int64
A3             int64
A4             int64
A5             int64
A6             int64
A7             int64
A8             int64
A9             int64
A10            int64
Age            int64
Sex           object
Jauundice     object
Family_ASD    object
Class         object

===== SAVED MLP INPUT =====
Expected feature count: 17

Diagnostic complete. No models or files changed.

In [83]:

# Cell 18B — Fix questionnaire preprocessing and verify predictions
# Safe: does not train or overwrite any saved model.

import json
import numpy as np
import pandas as pd
from pathlib import Path

MODEL_ROOT = Path("/kaggle/input/datasets/shahbaz18/backup/asd_care_results")
with open(MODEL_ROOT / "questionnaire_preprocessing.json", "r") as f:
    prep = json.load(f)

numeric_cols = prep["numeric_features"]
categorical_cols = prep["categorical_features"]
category_levels = prep["category_levels"]

def encode_questionnaire(df):
    df = df.copy()
    parts = []

    # Numeric columns: impute using saved medians, then saved scaling.
    numeric = df[numeric_cols].apply(pd.to_numeric, errors="coerce")
    for col in numeric_cols:
        numeric[col] = numeric[col].fillna(prep["numeric_medians"][col])

    means = np.asarray(prep["scaler_mean"], dtype=np.float32)
    scales = np.asarray(prep["scaler_scale"], dtype=np.float32)
    numeric_array = (numeric.to_numpy(dtype=np.float32) - means) / scales
    parts.append(numeric_array)

    # Categorical columns: preserve saved category order and all levels.
    for col in categorical_cols:
        values = df[col].astype("string").str.strip().str.lower()
        values = values.fillna("unknown")
        levels = category_levels[col]
        encoded = np.column_stack([
            (values.to_numpy() == level).astype(np.float32)
            for level in levels
        ])
        parts.append(encoded)

    X = np.concatenate(parts, axis=1).astype(np.float32)
    expected = int(questionnaire_model.input_shape[-1])
    assert X.shape[1] == expected, (
        f"Feature mismatch: created {X.shape[1]}, expected {expected}"
    )
    return X

for split, data in prepared.items():
    data["Xq"] = encode_questionnaire(data["df"])
    print(f"{split}: questionnaire features = {data['Xq'].shape}")

# Verify one split first; no need to rerun image predictions.
test_data = prepared["test"]
p_q_test = questionnaire_model.predict(
    test_data["Xq"], batch_size=32, verbose=0
).reshape(-1)

print("\nQuestionnaire inference successful.")
print("Test predictions:", p_q_test.shape)
print("Prediction range:", float(p_q_test.min()), "to", float(p_q_test.max()))
print("First 10 probabilities:", np.round(p_q_test[:10], 4))

train: questionnaire features = (2526, 17)
valid: questionnaire features = (200, 17)
test: questionnaire features = (200, 17)

Questionnaire inference successful.
Test predictions: (200,)
Prediction range: 0.0 to 1.0
First 10 probabilities: [0.9692 0.9956 1.     1.     0.9998 0.9989 0.9995 0.8614 1.     0.9998]

In [84]:

# Cell 19 — Prepare cached image and questionnaire predictions

import numpy as np
from pathlib import Path

WORK = Path("/kaggle/working/asd_multimodal_prototype")
WORK.mkdir(parents=True, exist_ok=True)

for split, data in prepared.items():
    cache = WORK / f"{split}_branch_predictions.npz"

    if cache.exists():
        with np.load(cache) as saved:
            print(f"\n{split}: existing cache found")
            print("Keys:", saved.files)
            for key in saved.files:
                print(f"  {key}: {saved[key].shape}")
    else:
        print(f"\n{split}: no prediction cache yet")

print("\nPrepared splits:", list(prepared.keys()))
print("Image model:", image_model.input_shape, "->", image_model.output_shape)
print("Questionnaire model:", questionnaire_model.input_shape,
      "->", questionnaire_model.output_shape)

train: no prediction cache yet

valid: no prediction cache yet

test: no prediction cache yet

Prepared splits: ['train', 'valid', 'test']
Image model: (None, 224, 224, 3) -> (None, 1)
Questionnaire model: (None, 17) -> (None, 1)

In [85]:

# Cell 20 — Generate and save branch predictions (no training)

import json
import numpy as np
import pandas as pd
import tensorflow as tf
from pathlib import Path
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.utils import load_img, img_to_array

WORK = Path("/kaggle/working/asd_multimodal_prototype")
WORK.mkdir(parents=True, exist_ok=True)

BATCH_SIZE = 32
IMG_SIZE = (224, 224)

def predict_images(paths):
    results = []
    for start in range(0, len(paths), BATCH_SIZE):
        batch_paths = paths[start:start + BATCH_SIZE]
        batch = np.stack([
            img_to_array(load_img(p, target_size=IMG_SIZE))
            for p in batch_paths
        ]).astype(np.float32)

        batch = preprocess_input(batch)
        pred = image_model.predict(batch, verbose=0).reshape(-1)
        results.extend(pred.tolist())

    return np.asarray(results, dtype=np.float32)

for split, data in prepared.items():
    cache = WORK / f"{split}_branch_predictions.npz"

    # Reuse a complete cache if present.
    if cache.exists():
        with np.load(cache) as z:
            if all(k in z.files for k in ["p_img", "p_q", "y"]):
                print(f"{split}: complete cache already exists; skipping.")
                continue

    print(f"\nProcessing {split} ({len(data['y'])} samples)...")

    p_img = predict_images(data["image_paths"])
    p_q = questionnaire_model.predict(
        data["Xq"], batch_size=BATCH_SIZE, verbose=0
    ).reshape(-1)

    y = np.asarray(data["y"]).reshape(-1).astype(np.int32)

    assert len(p_img) == len(p_q) == len(y)
    np.savez_compressed(
        cache,
        p_img=p_img,
        p_q=p_q,
        y=y
    )

    print("Saved:", cache)
    print("Image probabilities:", p_img.shape,
          "range:", (float(p_img.min()), float(p_img.max())))
    print("Questionnaire probabilities:", p_q.shape,
          "range:", (float(p_q.min()), float(p_q.max())))

print("\nAll split predictions processed.")
print("Cache directory:", WORK)

Processing train (2526 samples)...
Saved: /kaggle/working/asd_multimodal_prototype/train_branch_predictions.npz
Image probabilities: (2526,) range: (0.002214286010712385, 0.9999196529388428)
Questionnaire probabilities: (2526,) range: (0.0, 1.0)

Processing valid (200 samples)...
Saved: /kaggle/working/asd_multimodal_prototype/valid_branch_predictions.npz
Image probabilities: (200,) range: (0.006430472247302532, 0.9991971850395203)
Questionnaire probabilities: (200,) range: (0.0, 1.0)

Processing test (200 samples)...
Saved: /kaggle/working/asd_multimodal_prototype/test_branch_predictions.npz
Image probabilities: (200,) range: (0.009344414807856083, 0.9998607635498047)
Questionnaire probabilities: (200,) range: (0.0, 1.0)

All split predictions processed.
Cache directory: /kaggle/working/asd_multimodal_prototype

In [86]:

# Cell 21 — Test-set ablation comparison (no training)

import json
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix
)

WORK = Path("/kaggle/working/asd_multimodal_prototype")
RESULTS = []

def evaluate(name, y_true, probabilities):
    probabilities = np.asarray(probabilities).reshape(-1)
    predictions = (probabilities >= 0.5).astype(int)
    return {
        "model": name,
        "accuracy": accuracy_score(y_true, predictions),
        "precision": precision_score(y_true, predictions, zero_division=0),
        "recall": recall_score(y_true, predictions, zero_division=0),
        "f1": f1_score(y_true, predictions, zero_division=0),
        "roc_auc": roc_auc_score(y_true, probabilities),
        "confusion_matrix": confusion_matrix(
            y_true, predictions
        ).tolist()
    }

with np.load(WORK / "test_branch_predictions.npz") as z:
    y_test = z["y"].astype(int)
    p_img = z["p_img"]
    p_q = z["p_q"]

assert len(y_test) == len(p_img) == len(p_q) == 200
assert set(np.unique(y_test)).issubset({0, 1})

# Simple late fusion: equal weights, fixed before test evaluation.
p_fusion = 0.5 * p_img + 0.5 * p_q

RESULTS.append(evaluate("ResNet50 image-only", y_test, p_img))
RESULTS.append(evaluate("Questionnaire MLP", y_test, p_q))
RESULTS.append(evaluate("Late fusion (50:50)", y_test, p_fusion))

comparison = pd.DataFrame([
    {k: v for k, v in row.items() if k != "confusion_matrix"}
    for row in RESULTS
])

print("TEST SET COMPARISON")
display(comparison.round(4))

for row in RESULTS:
    print(f"\n{row['model']}")
    print("Confusion matrix [[TN, FP], [FN, TP]]:")
    print(np.array(row["confusion_matrix"]))

comparison.to_csv(WORK / "test_ablation_comparison.csv", index=False)

with open(WORK / "test_ablation_results.json", "w") as f:
    json.dump(RESULTS, f, indent=2)

print("\nSaved comparison and detailed metrics to:", WORK)
print("IMPORTANT: image-questionnaire pairing is synthetic and unverified.")

TEST SET COMPARISON

                 model  accuracy  precision  recall      f1  roc_auc
0  ResNet50 image-only     0.895     0.8835    0.91  0.8966   0.9463
1    Questionnaire MLP     0.985     0.9709    1.00  0.9852   0.9998
2  Late fusion (50:50)     0.985     0.9709    1.00  0.9852   0.9988

ResNet50 image-only
Confusion matrix [[TN, FP], [FN, TP]]:
[[88 12]
 [ 9 91]]

Questionnaire MLP
Confusion matrix [[TN, FP], [FN, TP]]:
[[ 97   3]
 [  0 100]]

Late fusion (50:50)
Confusion matrix [[TN, FP], [FN, TP]]:
[[ 97   3]
 [  0 100]]

Saved comparison and detailed metrics to: /kaggle/working/asd_multimodal_prototype
IMPORTANT: image-questionnaire pairing is synthetic and unverified.

In [87]:
# Cell 23 — Final artifact check (no training)

from pathlib import Path

BACKUP = Path(
    "/kaggle/input/datasets/shahbaz18/backup/asd_care_results"
)
FUSION = Path(
    "/kaggle/working/asd_multimodal_prototype"
)

required = {
    "MobileNetV2 model": BACKUP / "mobilenetv2_best.keras",
    "EfficientNetB0 model": BACKUP / "efficientnetb0_best.keras",
    "ResNet50 model": BACKUP / "resnet50_best.keras",
    "Questionnaire model": BACKUP / "questionnaire_mlp_best.keras",
    "Fusion test predictions": FUSION / "test_branch_predictions.npz",
    "Fusion comparison CSV": FUSION / "test_ablation_comparison.csv",
    "Fusion detailed results": FUSION / "test_ablation_results.json",
}

for name, path in required.items():
    print(f"{'OK' if path.exists() else 'MISSING'} | {name}")

print("\nCheck complete. No models trained.")

OK | MobileNetV2 model
OK | EfficientNetB0 model
OK | ResNet50 model
OK | Questionnaire model
OK | Fusion test predictions
OK | Fusion comparison CSV
OK | Fusion detailed results

Check complete. No models trained.

In [88]:
# Cell 24 — Final report and downloadable package (no training)

from pathlib import Path
import json
import shutil
import zipfile
import pandas as pd

BACKUP = Path("/kaggle/input/datasets/shahbaz18/backup/asd_care_results")
FUSION = Path("/kaggle/working/asd_multimodal_prototype")
OUT = Path("/kaggle/working/asd_fyp_final_results")
ZIP_PATH = Path("/kaggle/working/asd_fyp_final_results.zip")

OUT.mkdir(parents=True, exist_ok=True)
(OUT / "models").mkdir(exist_ok=True)
(OUT / "fusion_results").mkdir(exist_ok=True)

# 1. Copy the three image models and questionnaire model
model_files = [
    "mobilenetv2_best.keras",
    "efficientnetb0_best.keras",
    "resnet50_best.keras",
    "questionnaire_mlp_best.keras",
]

for name in model_files:
    src = BACKUP / name
    if src.exists():
        shutil.copy2(src, OUT / "models" / name)
        print("Copied:", name)
    else:
        print("MISSING MODEL:", name)

# 2. Copy fusion evaluation artifacts
for name in [
    "train_branch_predictions.npz",
    "valid_branch_predictions.npz",
    "test_branch_predictions.npz",
    "test_ablation_comparison.csv",
    "test_ablation_results.json",
]:
    src = FUSION / name
    if src.exists():
        shutil.copy2(src, OUT / "fusion_results" / name)
        print("Copied:", name)
    else:
        print("Not found (skipped):", name)

# 3. Copy available model metrics, histories, and research notes
for pattern in [
    "*comparison*.csv",
    "*comparison*.json",
    "*history*.json",
    "*predictions*.npz",
    "research_limitations.json",
    "questionnaire_preprocessing.json",
    "questionnaire_scaler.json",
]:
    for src in BACKUP.glob(pattern):
        if src.is_file():
            dest = OUT / src.name
            if not dest.exists():
                shutil.copy2(src, dest)

# 4. Consolidate known image-model results
image_results = [
    {
        "section": "1. MobileNetV2",
        "accuracy": 0.8500,
        "precision": 0.8571,
        "recall": 0.8400,
        "f1_score": 0.8485,
        "roc_auc": 0.9307,
        "evaluation": "Image-only",
    },
    {
        "section": "2. EfficientNetB0",
        "accuracy": 0.8150,
        "precision": 0.8889,
        "recall": 0.7200,
        "f1_score": 0.7956,
        "roc_auc": 0.9347,
        "evaluation": "Image-only",
    },
    {
        "section": "3. ResNet50",
        "accuracy": 0.8950,
        "precision": 0.90099,
        "recall": 0.9100,
        "f1_score": 0.90547,
        "roc_auc": 0.9509,
        "evaluation": "Image-only",
    },
]

# Rebuild ResNet metrics from the verified confusion matrix:
# [[88, 12], [9, 91]]
# Precision = 91/(91+12); recall = 91/(91+9).

# Read fusion metrics from the saved detailed results, not from guessed values.
fusion_json = FUSION / "test_ablation_results.json"
fusion_results = json.loads(fusion_json.read_text()) if fusion_json.exists() else []

fusion_rows = []
for row in fusion_results:
    fusion_rows.append({
        "section": "4. " + row["model"],
        "accuracy": row.get("accuracy"),
        "precision": row.get("precision"),
        "recall": row.get("recall"),
        "f1_score": row.get("f1"),
        "roc_auc": row.get("roc_auc"),
        "evaluation": "Test-set fusion comparison",
    })

all_results = image_results + fusion_rows
pd.DataFrame(all_results).to_csv(
    OUT / "final_four_section_results.csv", index=False
)

with open(OUT / "final_four_section_results.json", "w") as f:
    json.dump(all_results, f, indent=2)

# 5. Write a project README with methodological caveat
readme = """ASD FYP — Final Results Package

Main result sections:
1. MobileNetV2 image-only
2. EfficientNetB0 image-only
3. ResNet50 image-only
4. Image-questionnaire late fusion

The image-model metrics are copied from the previously recorded evaluation
results. Fusion metrics are loaded from the saved test-ablation JSON.

Important methodological note:
The image-questionnaire pairing used in the current prototype was
class-stratified and participant identity was not verified. Consequently,
the fusion experiment should be described as an exploratory prototype
experiment, not as validated participant-level multimodal evaluation.
Questionnaire results may also be affected by strong association between
questionnaire answers and class labels.

These results do not establish clinical validity.
No model training or inference was performed by the packaging cell.
"""
(OUT / "README.txt").write_text(readme, encoding="utf-8")

# 6. Create ZIP
if ZIP_PATH.exists():
    ZIP_PATH.unlink()

with zipfile.ZipFile(ZIP_PATH, "w", zipfile.ZIP_DEFLATED) as zf:
    for file in OUT.rglob("*"):
        if file.is_file():
            zf.write(file, file.relative_to(OUT))

print("\nFINAL PACKAGE CREATED")
print("Folder:", OUT)
print("ZIP:", ZIP_PATH)
print("ZIP size (MB):", round(ZIP_PATH.stat().st_size / (1024**2), 2))
print("\nFinal comparison preview:")
display(pd.DataFrame(all_results).round(4))
print("\nDownload asad_fyp_final_results.zip from Kaggle's Output panel.")

Copied: mobilenetv2_best.keras
Copied: efficientnetb0_best.keras
Copied: resnet50_best.keras
Copied: questionnaire_mlp_best.keras
Copied: train_branch_predictions.npz
Copied: valid_branch_predictions.npz
Copied: test_branch_predictions.npz
Copied: test_ablation_comparison.csv
Copied: test_ablation_results.json

FINAL PACKAGE CREATED
Folder: /kaggle/working/asd_fyp_final_results
ZIP: /kaggle/working/asd_fyp_final_results.zip
ZIP size (MB): 107.74

Final comparison preview:

,section,accuracy,precision,recall,f1_score,roc_auc,evaluation
0,1. MobileNetV2,0.850,0.8571,0.84,0.8485,0.9307,Image-only
1,2. EfficientNetB0,0.815,0.8889,0.72,0.7956,0.9347,Image-only
2,3. ResNet50,0.895,0.9010,0.91,0.9055,0.9509,Image-only
3,4. ResNet50 image-only,0.895,0.8835,0.91,0.8966,0.9463,Test-set fusion comparison
4,4. Questionnaire MLP,0.985,0.9709,1.00,0.9852,0.9998,Test-set fusion comparison
5,4. Late fusion (50:50),0.985,0.9709,1.00,0.9852,0.9988,Test-set fusion comparison

Download asad_fyp_final_results.zip from Kaggle's Output panel.